DNG SDK 1.5: dng_abort_sniffer Class Reference
dng_abort_sniffer Class Reference abstract
Class for signaling user cancellation and receiving progress updates.
#include <dng_abort_sniffer.h>
Public Member Functions
dng_priority Priority () const
Getter for priority level.
void SetPriority (dng_priority priority)
Setter for priority level.
void SniffNoPriorityWait ()
virtual bool ThreadSafe () const
virtual bool SupportsPriorityWait () const
Static Public Member Functions
static void SniffForAbort (dng_abort_sniffer *sniffer)
Protected Member Functions
virtual void Sniff ()=0
virtual void StartTask (const char *name, real64 fract)
virtual void EndTask ()
Signals the end of the innermost task that has been started.
virtual void UpdateProgress (real64 fract)
Friends
class dng_sniffer_task
Detailed Description
Class for signaling user cancellation and receiving progress updates.
DNG SDK clients should derive a host application specific implementation from this class.
Member Function Documentation
Sniff()
virtual void dng_abort_sniffer::Sniff () protected pure virtual
Should be implemented by derived classes to check for an user cancellation.
Referenced by SniffForAbort().
SniffForAbort()
void dng_abort_sniffer::SniffForAbort (dng_abort_sniffer * sniffer) static
Check for pending user cancellation or other abort. ThrowUserCanceled will be called if one is pending. This static method is provided as a convenience for quickly testing for an abort and throwing an exception if one is pending.
Parameters
sniffer The dng_sniffer to test for a pending abort. Can be NULL, in which case there an abort is never signalled.
References Sniff().
Referenced by dng_stream::Flush(), dng_jpeg_image_encode_task::Process(), dng_jpeg_image_find_digest_task::Process(), dng_area_task::ProcessOnThread(), dng_sniffer_task::Sniff(), and dng_host::SniffForAbort().
StartTask()
void dng_abort_sniffer::StartTask (const char * name, real64 fract) protected virtual
Signals the start of a named task withn processing in the DNG SDK. Tasks may be nested.
Parameters
name of the task
fract Percentage of total processing this task is expected to take. From 0.0 to 1.0 .
Referenced by dng_sniffer_task::dng_sniffer_task().
UpdateProgress()
void dng_abort_sniffer::UpdateProgress (real64 fract) protected virtual
Signals progress made on current task.
Parameters
fract percentage of processing completed on current task. From 0.0 to 1.0 .
Referenced by dng_sniffer_task::UpdateProgress().
The documentation for this class was generated from the following files:
dng_abort_sniffer.h
dng_abort_sniffer.cpp