DNG SDK 1.5: dng_warp_params_rectilinear Class Reference
dng_warp_params_rectilinear Class Reference
Warp parameters for pinhole perspective rectilinear (not fisheye) camera model. Supports radial and tangential (decentering) distortion correction parameters.
#include <dng_lens_correction.h>
Public Member Functions
dng_warp_params_rectilinear ()
Create empty (invalid) rectilinear warp parameters.
dng_warp_params_rectilinear (uint32 planes, const dng_vector radParams [], const dng_vector tanParams [], const dng_point_real64 &fCenter)
virtual bool IsRadNOP (uint32 plane) const
Is the radial correction a NOP for the specified plane?
virtual bool IsTanNOP (uint32 plane) const
Is the tangential correction a NOP for the specified plane?
virtual bool IsValid () const
Do these warp params appear valid?
virtual void PropagateToAllPlanes (uint32 totalPlanes)
Propagate warp parameters from first plane to all other planes.
virtual real64 Evaluate (uint32 plane, real64 r) const
virtual real64 EvaluateRatio (uint32 plane, real64 r2) const
virtual dng_point_real64 EvaluateTangential (uint32 plane, real64 r2, const dng_point_real64 &diff, const dng_point_real64 &diff2) const
virtual real64 MaxSrcRadiusGap (real64 maxDstGap) const
virtual dng_point_real64 MaxSrcTanGap (dng_point_real64 minDst, dng_point_real64 maxDst) const
virtual real64 SafeMinRatio () const
virtual real64 SafeMaxRatio () const
virtual void Dump () const
Debug parameters.
Public Member Functions inherited from dng_warp_params
dng_warp_params ()
Create empty (invalid) warp parameters.
dng_warp_params (uint32 planes, const dng_point_real64 &fCenter)
virtual bool IsNOPAll () const
Is the entire correction a NOP for all planes?
virtual bool IsNOP (uint32 plane) const
Is the entire correction a NOP for the specified plane?
virtual bool IsRadNOPAll () const
Is the radial correction a NOP for all planes?
virtual bool IsTanNOPAll () const
Is the tangential correction a NOP for all planes?
virtual bool IsValidForNegative (const dng_negative &negative) const
Are these warp params valid for the specified negative?
virtual real64 EvaluateInverse (uint32 plane, real64 r) const
dng_point_real64 EvaluateTangential2 (uint32 plane, const dng_point_real64 &diff) const
dng_point_real64 EvaluateTangential3 (uint32 plane, real64 r2, const dng_point_real64 &diff) const
Public Attributes
dng_vector fRadParams [kMaxColorPlanes]
dng_vector fTanParams [kMaxColorPlanes]
Public Attributes inherited from dng_warp_params
uint32 fPlanes
dng_point_real64 fCenter
Detailed Description
Warp parameters for pinhole perspective rectilinear (not fisheye) camera model. Supports radial and tangential (decentering) distortion correction parameters.
Note the restrictions described below.
Constructor & Destructor Documentation
dng_warp_params_rectilinear()
dng_warp_params_rectilinear::dng_warp_params_rectilinear (uint32 planes, const dng_vector radParams[], const dng_vector tanParams[], const dng_point_real64 & fCenter)
Create rectilinear warp parameters with the specified number of planes, radial component terms, tangential component terms, and image center in relative coordinates.
Member Function Documentation
Evaluate()
real64 dng_warp_params_rectilinear::Evaluate (uint32 plane, real64 r) const virtual
Evaluate the 1D radial warp function for the specified plane. Parameter r is the destination (i.e., corrected) normalized radius, i.e., the normalized Euclidean distance between a corrected pixel position and the optical center in the image. r lies in the range [0,1]. The returned result is non-negative.
Implements dng_warp_params.
Referenced by MaxSrcRadiusGap().
EvaluateRatio()
real64 dng_warp_params_rectilinear::EvaluateRatio (uint32 plane, real64 r2) const virtual
Evaluate the 1D radial warp ratio function for the specified plane. Parameter r2 is the square of the destination (i.e., corrected) normalized radius, i.e., the square of the normalized Euclidean distance between a corrected pixel position and the optical center in the image. r2 must lie in the range [0,1]. Note that this is different than the Evaluate () function, above, in that the argument to EvaluateRatio () is the square of the radius, not the radius itself. The returned result is non-negative. Mathematically, EvaluateRatio (r * r) is the same as Evaluate (r) / r.
Implements dng_warp_params.
EvaluateTangential()
dng_point_real64 dng_warp_params_rectilinear::EvaluateTangential (uint32 plane, real64 r2, const dng_point_real64 & diff, const dng_point_real64 & diff2) const virtual
Evaluate the 2D tangential warp for the specified plane. Parameter r2 is the square of the destination (i.e., corrected) normalized radius, i.e., the square of the normalized Euclidean distance between a corrected pixel position P and the optical center in the image. r2 must lie in the range [0,1]. diff contains the vertical and horizontal Euclidean distances (in pixels) between P and the optical center. diff2 contains the squares of the vertical and horizontal Euclidean distances (in pixels) between P and the optical center. The returned result is the tangential warp offset, measured in pixels.
Implements dng_warp_params.
MaxSrcRadiusGap()
real64 dng_warp_params_rectilinear::MaxSrcRadiusGap (real64 maxDstGap) const virtual
Compute and return the maximum warped radius gap. Let D be a rectangle in a destination (corrected) image. Let rDstFar and rDstNear be the farthest and nearest points to the image center, respectively. Then the specified parameter maxDstGap is the Euclidean distance between rDstFar and rDstNear. Warp D through this warp function to a closed and bounded (generally not rectangular) region S. Let rSrcfar and rSrcNear be the farthest and nearest points to the image center, respectively. This routine returns a value that is at least (rSrcFar - rSrcNear).
Implements dng_warp_params.
References Evaluate().
MaxSrcTanGap()
dng_point_real64 dng_warp_params_rectilinear::MaxSrcTanGap (dng_point_real64 minDst, dng_point_real64 maxDst) const virtual
Compute and return the maximum warped tangential gap. minDst is the top-left pixel of the image in normalized pixel coordinates. maxDst is the bottom-right pixel of the image in normalized pixel coordinates. MaxSrcTanGap () computes the maximum absolute shift in normalized pixels in the horizontal and vertical directions that can occur as a result of the tangential warp.
Implements dng_warp_params.
References dng_warp_params::EvaluateTangential2().
SafeMaxRatio()
real64 dng_warp_params_rectilinear::SafeMaxRatio () const virtual
Compute and return the maximum src/dst ratio that should be used for this warp.
Implements dng_warp_params.
SafeMinRatio()
real64 dng_warp_params_rectilinear::SafeMinRatio () const virtual
Compute and return the minimum src/dst ratio that should be used for this warp.
Implements dng_warp_params.
The documentation for this class was generated from the following files:
dng_lens_correction.h
dng_lens_correction.cpp