DNG SDK 1.5: dng_ref_counted_block Class Reference
dng_ref_counted_block Class Reference
Class to provide resource acquisition is instantiation discipline for small memory allocations.
#include <dng_ref_counted_block.h>
Public Member Functions
dng_ref_counted_block ()
dng_ref_counted_block (uint32 size)
~dng_ref_counted_block ()
Release memory buffer using free.
dng_ref_counted_block (const dng_ref_counted_block &data)
Copy constructore, which takes a reference to data and does not copy the block.
dng_ref_counted_block & operator= (const dng_ref_counted_block &data)
Assignment operatore takes a reference to right hand side and does not copy the data.
void Allocate (uint32 size)
void Clear ()
void EnsureWriteable ()
If there is only one reference, do nothing, otherwise copy the data into a new block and return an object with that block as the data.
uint32 LogicalSize () const
void * Buffer ()
const void * Buffer () const
char * Buffer_char ()
const char * Buffer_char () const
uint8 * Buffer_uint8 ()
const uint8 * Buffer_uint8 () const
uint16 * Buffer_uint16 ()
const uint16 * Buffer_uint16 () const
int16 * Buffer_int16 ()
const int16 * Buffer_int16 () const
uint32 * Buffer_uint32 ()
const uint32 * Buffer_uint32 () const
int32 * Buffer_int32 ()
const int32 * Buffer_int32 () const
uint64 * Buffer_uint64 ()
const uint64 * Buffer_uint64 () const
int64 * Buffer_int64 ()
const int64 * Buffer_int64 () const
real32 * Buffer_real32 ()
const real32 * Buffer_real32 () const
real64 * Buffer_real64 ()
const real64 * Buffer_real64 () const
Detailed Description
Class to provide resource acquisition is instantiation discipline for small memory allocations.
Support for a refcounted block, with optional copy-on-writeThis class does not use dng_memory_allocator for memory allocation.
Constructor & Destructor Documentation
dng_ref_counted_block() [1/2]
dng_ref_counted_block::dng_ref_counted_block ()
Construct an empty memory buffer using malloc.
Exceptions
dng_memory_full with fErrorCode equal to dng_error_memory.
dng_ref_counted_block() [2/2]
dng_ref_counted_block::dng_ref_counted_block (uint32 size)
Construct memory buffer of size bytes using malloc.
Parameters
size Number of bytes of memory needed.
Exceptions
dng_memory_full with fErrorCode equal to dng_error_memory.
References Allocate().
Member Function Documentation
Allocate()
void dng_ref_counted_block::Allocate (uint32 size)
Clear existing memory buffer and allocate new memory of size bytes.
Parameters
size Number of bytes of memory needed.
Exceptions
dng_memory_full with fErrorCode equal to dng_error_memory.
References Clear(), and ThrowMemoryFull().
Referenced by dng_ref_counted_block(), EnsureWriteable(), and dng_hue_sat_map::SetDivisions().
Buffer()
const void* dng_ref_counted_block::Buffer () const inline
Return pointer to allocated memory as a const void *.
Return values
const void * valid for as many bytes as were allocated.
Buffer_char() [1/2]
char* dng_ref_counted_block::Buffer_char () inline
Return pointer to allocated memory as a char *.
Return values
char * valid for as many bytes as were allocated.
Buffer_char() [2/2]
const char* dng_ref_counted_block::Buffer_char () const inline
Return pointer to allocated memory as a const char *.
Return values
const char * valid for as many bytes as were allocated.
Buffer_int16() [1/2]
int16* dng_ref_counted_block::Buffer_int16 () inline
Return pointer to allocated memory as a int16 *.
Return values
int16 * valid for as many bytes as were allocated.
Buffer_int16() [2/2]
const int16* dng_ref_counted_block::Buffer_int16 () const inline
Return pointer to allocated memory as a const int16 *.
Return values
const int16 * valid for as many bytes as were allocated.
Buffer_int32() [1/2]
int32* dng_ref_counted_block::Buffer_int32 () inline
Return pointer to allocated memory as a const int32 *.
Return values
const int32 * valid for as many bytes as were allocated.
Buffer_int32() [2/2]
const int32* dng_ref_counted_block::Buffer_int32 () const inline
Return pointer to allocated memory as a const int32 *.
Return values
const int32 * valid for as many bytes as were allocated.
Buffer_int64() [1/2]
int64* dng_ref_counted_block::Buffer_int64 () inline
Return pointer to allocated memory as a const int64 *.
Return values
const int64 * valid for as many bytes as were allocated.
Buffer_int64() [2/2]
const int64* dng_ref_counted_block::Buffer_int64 () const inline
Return pointer to allocated memory as a const int64 *.
Return values
const int64 * valid for as many bytes as were allocated.
Buffer_real32() [1/2]
real32* dng_ref_counted_block::Buffer_real32 () inline
Return pointer to allocated memory as a real32 *.
Return values
real32 * valid for as many bytes as were allocated.
Referenced by dng_hue_sat_map::GetConstDeltas(), and dng_hue_sat_map::GetDeltas().
Buffer_real32() [2/2]
const real32* dng_ref_counted_block::Buffer_real32 () const inline
Return pointer to allocated memory as a const real32 *.
Return values
const real32 * valid for as many bytes as were allocated.
Buffer_real64() [1/2]
real64* dng_ref_counted_block::Buffer_real64 () inline
Return pointer to allocated memory as a real64 *.
Return values
real64 * valid for as many bytes as were allocated.
Buffer_real64() [2/2]
const real64* dng_ref_counted_block::Buffer_real64 () const inline
Return pointer to allocated memory as a const real64 *.
Return values
const real64 * valid for as many bytes as were allocated.
Buffer_uint16() [1/2]
uint16* dng_ref_counted_block::Buffer_uint16 () inline
Return pointer to allocated memory as a uint16 *.
Return values
uint16 * valid for as many bytes as were allocated.
Buffer_uint16() [2/2]
const uint16* dng_ref_counted_block::Buffer_uint16 () const inline
Return pointer to allocated memory as a const uint16 *.
Return values
const uint16 * valid for as many bytes as were allocated.
Buffer_uint32() [1/2]
uint32* dng_ref_counted_block::Buffer_uint32 () inline
Return pointer to allocated memory as a uint32 *.
Return values
uint32 * valid for as many bytes as were allocated.
Buffer_uint32() [2/2]
const uint32* dng_ref_counted_block::Buffer_uint32 () const inline
Return pointer to allocated memory as a uint32 *.
Return values
uint32 * valid for as many bytes as were allocated.
Buffer_uint64() [1/2]
uint64* dng_ref_counted_block::Buffer_uint64 () inline
Return pointer to allocated memory as a uint64 *.
Return values
uint64 * valid for as many bytes as were allocated.
Buffer_uint64() [2/2]
const uint64* dng_ref_counted_block::Buffer_uint64 () const inline
Return pointer to allocated memory as a uint64 *.
Return values
uint64 * valid for as many bytes as were allocated.
Buffer_uint8() [1/2]
uint8* dng_ref_counted_block::Buffer_uint8 () inline
Return pointer to allocated memory as a uint8 *.
Return values
uint8 * valid for as many bytes as were allocated.
Buffer_uint8() [2/2]
const uint8* dng_ref_counted_block::Buffer_uint8 () const inline
Return pointer to allocated memory as a const uint8 *.
Return values
const uint8 * valid for as many bytes as were allocated.
Clear()
void dng_ref_counted_block::Clear ()
Release any allocated memory using free. Object is still valid and Allocate can be called again.
Referenced by Allocate(), operator=(), dng_hue_sat_map::SetInvalid(), and ~dng_ref_counted_block().
LogicalSize()
uint32 dng_ref_counted_block::LogicalSize () const inline
Return pointer to allocated memory as a void *..
Return values
void * valid for as many bytes as were allocated.
The documentation for this class was generated from the following files:
dng_ref_counted_block.h
dng_ref_counted_block.cpp