DNG SDK 1.5: dng_hue_sat_map Class Reference
dng_hue_sat_map Class Reference
A 3D table that maps HSV (hue, saturation, and value) floating-point input coordinates in the range [0,1] to delta signals. The table must have at least 1 sample in the hue dimension, at least 2 samples in the saturation dimension, and at least 1 sample in the value dimension. Tables are stored in value-hue-saturation order.
#include <dng_hue_sat_map.h>
Classes
struct HSBModify
Public Member Functions
dng_hue_sat_map ()
Construct an empty (and invalid) hue sat map.
dng_hue_sat_map (const dng_hue_sat_map &src)
Copy an existing hue sat map.
dng_hue_sat_map & operator= (const dng_hue_sat_map &rhs)
Copy an existing hue sat map.
virtual ~dng_hue_sat_map ()
Destructor.
bool IsNull () const
Is this hue sat map invalid?
bool IsValid () const
Is this hue sat map valid?
void SetInvalid ()
Clear the hue sat map, making it invalid.
void GetDivisions (uint32 &hueDivisions, uint32 &satDivisions, uint32 &valDivisions) const
Get the table dimensions (number of samples in each dimension).
void SetDivisions (uint32 hueDivisions, uint32 satDivisions, uint32 valDivisions=1)
void GetDelta (uint32 hueDiv, uint32 satDiv, uint32 valDiv, HSBModify &modify) const
Get a specific table entry, specified by table indices.
void EnsureWriteable ()
Make sure the table is writeable.
void SetDelta (uint32 hueDiv, uint32 satDiv, uint32 valDiv, const HSBModify &modify)
Set a specific table entry, specified by table indices.
void SetDeltaKnownWriteable (uint32 hueDiv, uint32 satDiv, uint32 valDiv, const HSBModify &modify)
Same as SetDelta, without checking that the table is writeable.
uint32 DeltasCount () const
Get the total number of samples (across all dimensions).
HSBModify * GetDeltas ()
const HSBModify * GetConstDeltas () const
void AssignNewUniqueRuntimeFingerprint ()
void SetRuntimeFingerprint (const dng_fingerprint fingerprint)
Set Fingerprint. Rare use cases want to set the fingerprint.
const dng_fingerprint & RuntimeFingerprint () const
Get the runtime fingerprint of this hue sat map.
bool operator== (const dng_hue_sat_map &rhs) const
Equality test.
Static Public Member Functions
static dng_hue_sat_map * Interpolate (const dng_hue_sat_map &map1, const dng_hue_sat_map &map2, real64 weight1)
Detailed Description
A 3D table that maps HSV (hue, saturation, and value) floating-point input coordinates in the range [0,1] to delta signals. The table must have at least 1 sample in the hue dimension, at least 2 samples in the saturation dimension, and at least 1 sample in the value dimension. Tables are stored in value-hue-saturation order.
Member Function Documentation
GetConstDeltas()
const HSBModify* dng_hue_sat_map::GetConstDeltas () const inline
Direct read-only access to table entries. The entries are stored in value-hue-saturation order (outer to inner).
References dng_ref_counted_block::Buffer_real32().
Referenced by GetDelta(), Interpolate(), and operator==().
GetDeltas()
HSBModify* dng_hue_sat_map::GetDeltas () inline
Direct read/write access to table entries. The entries are stored in value-hue-saturation order (outer to inner).
References dng_ref_counted_block::Buffer_real32(), and EnsureWriteable().
Interpolate()
dng_hue_sat_map * dng_hue_sat_map::Interpolate (const dng_hue_sat_map & map1, const dng_hue_sat_map & map2, real64 weight1) static
Compute a linearly-interpolated hue sat map (i.e., delta and scale factors) from the specified tables, with the specified weight. map1 and map2 must have the same dimensions.
References DeltasCount(), dng_hue_sat_map(), DNG_REPORT, GetConstDeltas(), IsValid(), dng_md5_printer::Process(), AutoPtr< T >::Release(), dng_md5_printer::Result(), RuntimeFingerprint(), SetDivisions(), SetRuntimeFingerprint(), and ThrowProgramError().
Referenced by dng_camera_profile::HueSatMapForWhite().
SetDivisions()
void dng_hue_sat_map::SetDivisions (uint32 hueDivisions, uint32 satDivisions, uint32 valDivisions = 1)
Set the table dimensions (number of samples in each dimension). This erases any existing table data.
References dng_ref_counted_block::Allocate(), DeltasCount(), and DNG_ASSERT.
Referenced by Interpolate().
The documentation for this class was generated from the following files:
dng_hue_sat_map.h
dng_hue_sat_map.cpp