DNG SDK 1.5: dng_read_tiles_task Class Reference
dng_read_tiles_task Class Reference
Public Member Functions
dng_read_tiles_task (dng_read_image &readImage, dng_host &host, const dng_ifd &ifd, dng_stream &stream, dng_image &image, dng_jpeg_image *jpegImage, dng_fingerprint *jpegTileDigest, uint32 outerSamples, uint32 innerSamples, uint32 tilesDown, uint32 tilesAcross, uint64 *tileOffset, uint32 *tileByteCount, uint32 compressedSize, uint32 uncompressedSize)
void Process (uint32 threadIndex, const dng_rect &tile, dng_abort_sniffer *sniffer)
and progress updates.
Public Member Functions inherited from dng_area_task
dng_area_task (const char *name="unnamed dng_area_task")
const char * Name () const
virtual uint32 MaxThreads () const
virtual uint32 MinTaskArea () const
operation. (Partitions can be smaller due to small inputs and edge cases.)
virtual dng_point UnitCell () const
virtual dng_point MaxTileSize () const
virtual dng_rect RepeatingTile1 () const
virtual dng_rect RepeatingTile2 () const
virtual dng_rect RepeatingTile3 () const
virtual void Start (uint32 threadCount, const dng_rect &dstArea, const dng_point &tileSize, dng_memory_allocator *allocator, dng_abort_sniffer *sniffer)
virtual void Finish (uint32 threadCount)
dng_point FindTileSize (const dng_rect &area) const
void ProcessOnThread (uint32 threadIndex, const dng_rect &area, const dng_point &tileSize, dng_abort_sniffer *sniffer, dng_area_task_progress *progress)
virtual dng_base_tile_iterator * MakeTileIterator (uint32 threadIndex, const dng_rect &tile, const dng_rect &area) const
virtual dng_base_tile_iterator * MakeTileIterator (uint32 threadIndex, const dng_point &tileSize, const dng_rect &area) const
Protected Member Functions
void ReadTask (uint32 tileIndex, uint32 &byteCount, dng_memory_block *compressedBuffer)
void ProcessTask (uint32 tileIndex, uint32 byteCount, dng_abort_sniffer *sniffer, AutoPtr< dng_memory_block > &compressedBuffer, AutoPtr< dng_memory_block > &uncompressedBuffer, AutoPtr< dng_memory_block > &subTileBlockBuffer)
Protected Attributes
dng_read_image & fReadImage
dng_host & fHost
const dng_ifd & fIFD
dng_stream & fStream
dng_image & fImage
dng_jpeg_image * fJPEGImage
dng_fingerprint * fJPEGTileDigest
uint32 fOuterSamples
uint32 fInnerSamples
uint32 fTilesDown
uint32 fTilesAcross
uint64 * fTileOffset
uint32 * fTileByteCount
uint32 fCompressedSize
uint32 fUncompressedSize
dng_mutex fMutex
uint32 fNextTileIndex
Protected Attributes inherited from dng_area_task
uint32 fMaxThreads
uint32 fMinTaskArea
dng_point fUnitCell
dng_point fMaxTileSize
dng_string fName
Additional Inherited Members
Static Public Member Functions inherited from dng_area_task
static void Perform (dng_area_task &task, const dng_rect &area, dng_memory_allocator *allocator, dng_abort_sniffer *sniffer, dng_area_task_progress *progress)
Member Function Documentation
Process()
void dng_read_tiles_task::Process (uint32 threadIndex, const dng_rect & tile, dng_abort_sniffer * sniffer) virtual
and progress updates.
Process one tile or fully partitioned area. This method is overridden by derived classes to implement the actual image processing. Note that the sniffer can be ignored if it is certain that a processing task will complete very quickly. This method should never be called directly but rather accessed via Process. There is no allocator parameter as all allocation should be done in Start.
Parameters
threadIndex 0 to threadCount - 1 index indicating which thread this is. (Can be used to get a thread-specific buffer allocated in the Start method.)
tile Area to process.
sniffer dng_abort_sniffer to use to check for user cancellation
Implements dng_area_task.
References dng_host::Allocate(), AutoPtr< T >::Get(), and AutoPtr< T >::Reset().
The documentation for this class was generated from the following files:
dng_read_image.h
dng_read_image.cpp