DNG SDK 1.5: dng_opcode_list Class Reference
dng_opcode_list Class Reference
A list of opcodes.
#include <dng_opcode_list.h>
Public Member Functions
dng_opcode_list (uint32 stage)
Create an empty opcode list for the specific image stage (1, 2, or 3).
bool IsEmpty () const
Is the opcode list empty?
bool NotEmpty () const
Does the list contain at least 1 opcode?
bool AlwaysApply () const
Should the opcode list always be applied to the image?
void SetAlwaysApply ()
uint32 Count () const
The number of opcodes in this list.
dng_opcode & Entry (uint32 index)
const dng_opcode & Entry (uint32 index) const
void Clear ()
Remove all opcodes from the list.
void Swap (dng_opcode_list &otherList)
Swap two opcode lists.
uint32 MinVersion (bool includeOptional) const
void Apply (dng_host &host, dng_negative &negative, AutoPtr< dng_image > &image)
void Append (AutoPtr< dng_opcode > &opcode)
Append the specified opcode to this list.
dng_memory_block * Spool (dng_host &host) const
void FingerprintToStream (dng_stream &stream) const
Write a fingerprint of this opcode list to the specified stream.
void Parse (dng_host &host, dng_stream &stream, uint32 byteCount, uint64 streamOffset)
Detailed Description
A list of opcodes.
Member Function Documentation
Apply()
void dng_opcode_list::Apply (dng_host & host, dng_negative & negative, AutoPtr< dng_image > & image)
Apply this opcode list to the specified image with corresponding negative.
References dng_opcode::AboutToApply(), dng_opcode::Apply(), dng_image::Bounds(), Count(), DNG_REQUIRE, Entry(), AutoPtr< T >::Get(), and dng_image::Planes().
Referenced by dng_host::ApplyOpcodeList().
Entry() [1/2]
dng_opcode& dng_opcode_list::Entry (uint32 index) inline
Retrieve read/write opcode by index (must be in the range 0 to Count () - 1).
Referenced by Apply().
Entry() [2/2]
const dng_opcode& dng_opcode_list::Entry (uint32 index) const inline
Retrieve read-only opcode by index (must be in the range 0 to Count () - 1).
MinVersion()
uint32 dng_opcode_list::MinVersion (bool includeOptional) const
Return minimum DNG version required to support all opcodes in this list. If includeOptional is set to true, then this calculation will include optional opcodes.
Referenced by FingerprintToStream(), and Spool().
Parse()
void dng_opcode_list::Parse (dng_host & host, dng_stream & stream, uint32 byteCount, uint64 streamOffset)
Read an opcode list from the specified stream, starting at the specified offset (streamOffset, in bytes). byteCount is provided for error checking purposes. A bad format exception will be thrown if the length of the opcode stream does not exactly match byteCount.
References Append(), Clear(), dng_stream::Get_uint32(), dng_host::Make_dng_opcode(), dng_stream::Position(), dng_stream::SetReadPosition(), and ThrowBadFormat().
SetAlwaysApply()
void dng_opcode_list::SetAlwaysApply () inline
Set internal flag to indicate this opcode list should always be applied.
Spool()
dng_memory_block * dng_opcode_list::Spool (dng_host & host) const
Serialize this opcode list to a block of memory. The caller is responsible for deleting this block.
References dng_host::Allocator(), AlwaysApply(), IsEmpty(), MinVersion(), dng_stream::SetBigEndian(), and ThrowProgramError().
The documentation for this class was generated from the following files:
dng_opcode_list.h
dng_opcode_list.cpp