DNG SDK 1.5: dng_filter_opcode Class Reference
dng_filter_opcode Class Reference abstract
Class to represent a filter opcode, such as a convolution.
#include <dng_opcodes.h>
Public Member Functions
virtual uint32 BufferPixelType (uint32 imagePixelType)
The pixel data type of this opcode.
virtual dng_rect ModifiedBounds (const dng_rect &imageBounds)
virtual dng_point SrcRepeat ()
Returns the width and height (in pixels) of the repeating mosaic pattern.
virtual dng_rect SrcArea (const dng_rect &dstArea, const dng_rect &imageBounds)
virtual dng_point SrcTileSize (const dng_point &dstTileSize, const dng_rect &imageBounds)
virtual void Prepare (dng_negative &negative, uint32 threadCount, const dng_point &tileSize, const dng_rect &imageBounds, uint32 imagePlanes, uint32 bufferPixelType, dng_memory_allocator &allocator)
virtual void ProcessArea (dng_negative &negative, uint32 threadIndex, dng_pixel_buffer &srcBuffer, dng_pixel_buffer &dstBuffer, const dng_rect &dstArea, const dng_rect &imageBounds)=0
virtual void Apply (dng_host &host, dng_negative &negative, AutoPtr< dng_image > &image)
Apply this opcode to the specified image with associated negative.
Public Member Functions inherited from dng_opcode
uint32 OpcodeID () const
The ID of this opcode.
uint32 MinVersion () const
The first DNG version that supports this opcode.
uint32 Flags () const
The flags for this opcode.
bool Optional () const
Is this opcode optional?
bool SkipIfPreview () const
Should the opcode be skipped when rendering preview images?
bool WasReadFromStream () const
Was this opcode read from a data stream?
uint32 Stage () const
void SetStage (uint32 stage)
virtual bool IsNOP () const
virtual bool IsValidForNegative (const dng_negative &) const
Is this opcode valid for the specified negative?
virtual void PutData (dng_stream &stream) const
bool AboutToApply (dng_host &host, dng_negative &negative, const dng_rect &imageBounds, uint32 imagePlanes)
Protected Member Functions
dng_filter_opcode (uint32 opcodeID, uint32 minVersion, uint32 flags)
dng_filter_opcode (uint32 opcodeID, dng_stream &stream, const char *name)
Protected Member Functions inherited from dng_opcode
dng_opcode (uint32 opcodeID, uint32 minVersion, uint32 flags)
dng_opcode (uint32 opcodeID, dng_stream &stream, const char *name)
virtual void DoAboutToApply (dng_host &, dng_negative &, const dng_rect &, uint32)
Additional Inherited Members
Public Types inherited from dng_opcode
enum { kFlag_None = 0, kFlag_Optional = 1, kFlag_SkipIfPreview = 2 }
Opcode flags.
Detailed Description
Class to represent a filter opcode, such as a convolution.
Member Function Documentation
ModifiedBounds()
virtual dng_rect dng_filter_opcode::ModifiedBounds (const dng_rect & imageBounds) inline virtual
The adjusted bounds (processing area) of this opcode. It is limited to the intersection of the specified image area and the GainMap area.
Referenced by Apply().
Prepare()
virtual void dng_filter_opcode::Prepare (dng_negative & negative, uint32 threadCount, const dng_point & tileSize, const dng_rect & imageBounds, uint32 imagePlanes, uint32 bufferPixelType, dng_memory_allocator & allocator) inline virtual
Startup method called before any processing is performed on pixel areas. It can be used to allocate (per-thread) memory and setup tasks.
Parameters
negative The negative object to be processed.
threadCount Total number of threads that will be used for processing. Less than or equal to MaxThreads.
tileSize Size of source tiles which will be processed. (Not all tiles will be this size due to edge conditions.)
imageBounds Total size of image to be processed.
imagePlanes Number of planes in the image. Less than or equal to kMaxColorPlanes.
bufferPixelType Pixel type of image buffer (see dng_tag_types.h).
allocator dng_memory_allocator to use for allocating temporary buffers, etc.
Reimplemented in dng_opcode_FixBadPixelsList, and dng_opcode_FixBadPixelsConstant.
Referenced by dng_filter_opcode_task::Start().
ProcessArea()
virtual void dng_filter_opcode::ProcessArea (dng_negative & negative, uint32 threadIndex, dng_pixel_buffer & srcBuffer, dng_pixel_buffer & dstBuffer, const dng_rect & dstArea, const dng_rect & imageBounds) pure virtual
Implements filtering operation from one buffer to another. Source and destination pixels are set up in member fields of this class. Ideally, no allocation should be done in this routine.
Parameters
negative The negative associated with the pixels to be processed.
threadIndex The thread on which this routine is being called, between 0 and threadCount - 1 for the threadCount passed to Prepare method.
srcBuffer Input area and source pixels.
dstBuffer Destination pixels.
dstArea Destination pixel processing area.
imageBounds Total image area to be processed; dstArea will always lie within these bounds.
Implemented in dng_opcode_FixBadPixelsList, and dng_opcode_FixBadPixelsConstant.
Referenced by dng_filter_opcode_task::ProcessArea().
SrcArea()
virtual dng_rect dng_filter_opcode::SrcArea (const dng_rect & dstArea, const dng_rect & imageBounds) inline virtual
Returns the source pixel area needed to process a destination pixel area that lies within the specified bounds.
Parameters
dstArea The destination pixel area to be computed.
imageBounds The overall image area (dstArea will lie within these bounds).
Return values
The source pixel area needed to process the specified dstArea.
Reimplemented in dng_opcode_FixBadPixelsList, and dng_opcode_FixBadPixelsConstant.
Referenced by dng_filter_opcode_task::SrcArea(), and SrcTileSize().
SrcTileSize()
virtual dng_point dng_filter_opcode::SrcTileSize (const dng_point & dstTileSize, const dng_rect & imageBounds) inline virtual
Given a destination tile size, calculate input tile size. Simlar to SrcArea, and should seldom be overridden.
Parameters
dstTileSize The destination tile size that is targeted for output.
imageBounds The image bounds (the destination tile will always lie within these bounds).
Return values
The source tile size needed to compute a tile of the destination size.
References SrcArea().
Referenced by dng_filter_opcode_task::SrcTileSize().
The documentation for this class was generated from the following files:
dng_opcodes.h
dng_opcodes.cpp