DNG SDK 1.5: dng_area_spec Class Reference
dng_area_spec Class Reference
A class to describe an area of an image, including a pixel subrectangle, plane range, and row/column pitch (e.g., for mosaic images). Useful for specifying opcodes that only apply to specific color planes or pixel types (e.g., only one of the two green Bayer pixels).
#include <dng_misc_opcodes.h>
Public Types
enum { kDataSize = 32 }
Public Member Functions
dng_area_spec (const dng_rect &area=dng_rect(), uint32 plane=0, uint32 planes=1, uint32 rowPitch=1, uint32 colPitch=1)
Create an empty area.
const dng_rect & Area () const
The pixel area.
uint32 Plane () const
The first plane.
uint32 Planes () const
The total number of planes.
uint32 RowPitch () const
The row pitch (i.e., stride). A pitch of 1 means all rows.
uint32 ColPitch () const
The column pitch (i.e., stride). A pitch of 1 means all columns.
void GetData (dng_stream &stream)
Read area data from the specified stream.
void PutData (dng_stream &stream) const
Write area data to the specified stream.
dng_rect Overlap (const dng_rect &tile) const
Detailed Description
A class to describe an area of an image, including a pixel subrectangle, plane range, and row/column pitch (e.g., for mosaic images). Useful for specifying opcodes that only apply to specific color planes or pixel types (e.g., only one of the two green Bayer pixels).
Member Function Documentation
Overlap()
dng_rect dng_area_spec::Overlap (const dng_rect & tile) const
Compute and return pixel area overlap (i.e., intersection) between this area and the specified tile.
Referenced by dng_opcode_GainMap::ModifiedBounds(), dng_opcode_MapTable::ModifiedBounds(), dng_opcode_MapPolynomial::ModifiedBounds(), dng_opcode_DeltaPerRow::ModifiedBounds(), dng_opcode_DeltaPerColumn::ModifiedBounds(), dng_opcode_ScalePerRow::ModifiedBounds(), dng_opcode_ScalePerColumn::ModifiedBounds(), dng_opcode_GainMap::ProcessArea(), dng_opcode_MapTable::ProcessArea(), dng_opcode_MapPolynomial::ProcessArea(), dng_opcode_DeltaPerRow::ProcessArea(), dng_opcode_DeltaPerColumn::ProcessArea(), dng_opcode_ScalePerRow::ProcessArea(), and dng_opcode_ScalePerColumn::ProcessArea().
The documentation for this class was generated from the following files:
dng_misc_opcodes.h
dng_misc_opcodes.cpp