DNG SDK 1.5: dng_opcode_FixBadPixelsList Class Reference
dng_opcode_FixBadPixelsList Class Reference
An opcode to fix lists of bad pixels (indicated by position) in a Bayer image.
#include <dng_bad_pixels.h>
Public Member Functions
dng_opcode_FixBadPixelsList (AutoPtr< dng_bad_pixel_list > &list, uint32 bayerPhase)
dng_opcode_FixBadPixelsList (dng_stream &stream)
virtual void PutData (dng_stream &stream) const
virtual dng_point SrcRepeat ()
Returns the width and height (in pixels) of the repeating mosaic pattern.
virtual dng_rect SrcArea (const dng_rect &dstArea, const dng_rect &imageBounds)
virtual void Prepare (dng_negative &negative, uint32 threadCount, const dng_point &tileSize, const dng_rect &imageBounds, uint32 imagePlanes, uint32 bufferPixelType, dng_memory_allocator &allocator)
virtual void ProcessArea (dng_negative &negative, uint32 threadIndex, dng_pixel_buffer &srcBuffer, dng_pixel_buffer &dstBuffer, const dng_rect &dstArea, const dng_rect &imageBounds)
Public Member Functions inherited from dng_filter_opcode
virtual uint32 BufferPixelType (uint32 imagePixelType)
The pixel data type of this opcode.
virtual dng_rect ModifiedBounds (const dng_rect &imageBounds)
virtual dng_point SrcTileSize (const dng_point &dstTileSize, const dng_rect &imageBounds)
virtual void Apply (dng_host &host, dng_negative &negative, AutoPtr< dng_image > &image)
Apply this opcode to the specified image with associated negative.
Public Member Functions inherited from dng_opcode
uint32 OpcodeID () const
The ID of this opcode.
uint32 MinVersion () const
The first DNG version that supports this opcode.
uint32 Flags () const
The flags for this opcode.
bool Optional () const
Is this opcode optional?
bool SkipIfPreview () const
Should the opcode be skipped when rendering preview images?
bool WasReadFromStream () const
Was this opcode read from a data stream?
uint32 Stage () const
void SetStage (uint32 stage)
virtual bool IsNOP () const
virtual bool IsValidForNegative (const dng_negative &) const
Is this opcode valid for the specified negative?
bool AboutToApply (dng_host &host, dng_negative &negative, const dng_rect &imageBounds, uint32 imagePlanes)
Protected Types
enum { kBadPointPadding = 2, kBadRectPadding = 4 }
Protected Member Functions
bool IsGreen (int32 row, int32 col) const
virtual void FixIsolatedPixel (dng_pixel_buffer &buffer, dng_point &badPoint)
virtual void FixClusteredPixel (dng_pixel_buffer &buffer, uint32 pointIndex, const dng_rect &imageBounds)
virtual void FixSingleColumn (dng_pixel_buffer &buffer, const dng_rect &badRect)
virtual void FixSingleRow (dng_pixel_buffer &buffer, const dng_rect &badRect)
virtual void FixClusteredRect (dng_pixel_buffer &buffer, const dng_rect &badRect, const dng_rect &imageBounds)
Protected Member Functions inherited from dng_filter_opcode
dng_filter_opcode (uint32 opcodeID, uint32 minVersion, uint32 flags)
dng_filter_opcode (uint32 opcodeID, dng_stream &stream, const char *name)
Protected Member Functions inherited from dng_opcode
dng_opcode (uint32 opcodeID, uint32 minVersion, uint32 flags)
dng_opcode (uint32 opcodeID, dng_stream &stream, const char *name)
virtual void DoAboutToApply (dng_host &, dng_negative &, const dng_rect &, uint32)
Additional Inherited Members
Public Types inherited from dng_opcode
enum { kFlag_None = 0, kFlag_Optional = 1, kFlag_SkipIfPreview = 2 }
Opcode flags.
Detailed Description
An opcode to fix lists of bad pixels (indicated by position) in a Bayer image.
Constructor & Destructor Documentation
dng_opcode_FixBadPixelsList()
dng_opcode_FixBadPixelsList::dng_opcode_FixBadPixelsList (AutoPtr< dng_bad_pixel_list > & list, uint32 bayerPhase)
Construct an opcode to fix lists of bad pixels (indicated by position) in a Bayer image.
Parameters
list The list of bad pixels to fix.
bayerPhase The phase of the Bayer mosaic pattern (0, 1, 2, 3).
Member Function Documentation
Prepare()
void dng_opcode_FixBadPixelsList::Prepare (dng_negative & negative, uint32 threadCount, const dng_point & tileSize, const dng_rect & imageBounds, uint32 imagePlanes, uint32 bufferPixelType, dng_memory_allocator & allocator) virtual
Startup method called before any processing is performed on pixel areas. It can be used to allocate (per-thread) memory and setup tasks.
Parameters
negative The negative object to be processed.
threadCount Total number of threads that will be used for processing. Less than or equal to MaxThreads.
tileSize Size of source tiles which will be processed. (Not all tiles will be this size due to edge conditions.)
imageBounds Total size of image to be processed.
imagePlanes Number of planes in the image. Less than or equal to kMaxColorPlanes.
bufferPixelType Pixel type of image buffer (see dng_tag_types.h).
allocator dng_memory_allocator to use for allocating temporary buffers, etc.
Reimplemented from dng_filter_opcode.
References ThrowBadFormat().
ProcessArea()
void dng_opcode_FixBadPixelsList::ProcessArea (dng_negative & negative, uint32 threadIndex, dng_pixel_buffer & srcBuffer, dng_pixel_buffer & dstBuffer, const dng_rect & dstArea, const dng_rect & imageBounds) virtual
Implements filtering operation from one buffer to another. Source and destination pixels are set up in member fields of this class. Ideally, no allocation should be done in this routine.
Parameters
negative The negative associated with the pixels to be processed.
threadIndex The thread on which this routine is being called, between 0 and threadCount - 1 for the threadCount passed to Prepare method.
srcBuffer Input area and source pixels.
dstBuffer Destination pixels.
dstArea Destination pixel processing area.
imageBounds Total image area to be processed; dstArea will always lie within these bounds.
Implements dng_filter_opcode.
References dng_pixel_buffer::CopyArea(), dng_bad_pixel_list::IsPointIsolated(), dng_bad_pixel_list::IsRectIsolated(), dng_bad_pixel_list::Point(), dng_bad_pixel_list::PointCount(), dng_bad_pixel_list::Rect(), dng_bad_pixel_list::RectCount(), dng_pixel_buffer::RepeatSubArea(), and SrcRepeat().
PutData()
void dng_opcode_FixBadPixelsList::PutData (dng_stream & stream) const virtual
Write opcode to a stream.
Parameters
stream The stream to which to write the opcode data.
Reimplemented from dng_opcode.
References dng_bad_pixel_list::Point(), dng_bad_pixel_list::PointCount(), dng_stream::Put_int32(), dng_stream::Put_uint32(), dng_bad_pixel_list::Rect(), and dng_bad_pixel_list::RectCount().
SrcArea()
dng_rect dng_opcode_FixBadPixelsList::SrcArea (const dng_rect & dstArea, const dng_rect & imageBounds) virtual
Returns the source pixel area needed to process a destination pixel area that lies within the specified bounds.
Parameters
dstArea The destination pixel area to be computed.
imageBounds The overall image area (dstArea will lie within these bounds).
Return values
The source pixel area needed to process the specified dstArea.
Reimplemented from dng_filter_opcode.
References dng_bad_pixel_list::PointCount(), and dng_bad_pixel_list::RectCount().
The documentation for this class was generated from the following files:
dng_bad_pixels.h
dng_bad_pixels.cpp