DNG SDK 1.5: dng_exif Class Reference
dng_exif Class Reference
Container class for parsing and holding EXIF tags.
#include <dng_exif.h>
Public Member Functions
virtual dng_exif * Clone () const
Make clone.
void SetEmpty ()
Clear all EXIF fields.
void CopyGPSFrom (const dng_exif &exif)
void SetExposureTime (real64 et, bool snap=true)
void SetShutterSpeedValue (real64 ss)
void SetFNumber (real64 fs)
void SetApertureValue (real64 av)
void UpdateDateTime (const dng_date_time_info &dt)
bool AtLeastVersion0230 () const
Returns true iff the EXIF version is at least 2.3.
bool AtLeastVersion0231 () const
Returns true iff the EXIF version is at least 2.3.1.
void SetVersion0231 ()
Sets the EXIF version to 2.3.1.
bool HasLensDistortInfo () const
void SetLensDistortInfo (const dng_vector &params)
virtual bool ParseTag (dng_stream &stream, dng_shared &shared, uint32 parentCode, bool isMainIFD, uint32 tagCode, uint32 tagType, uint32 tagCount, uint64 tagOffset)
virtual void PostParse (dng_host &host, dng_shared &shared)
Static Public Member Functions
static real64 SnapExposureTime (real64 et)
static dng_urational EncodeFNumber (real64 fs)
static real64 ApertureValueToFNumber (real64 av)
static real64 ApertureValueToFNumber (const dng_urational &av)
static real64 FNumberToApertureValue (real64 fNumber)
static real64 FNumberToApertureValue (const dng_urational &fNumber)
Public Attributes
dng_string fImageDescription
dng_string fMake
dng_string fModel
dng_string fSoftware
dng_string fArtist
dng_string fCopyright
dng_string fCopyright2
dng_string fUserComment
dng_date_time_info fDateTime
dng_date_time_storage_info fDateTimeStorageInfo
dng_date_time_info fDateTimeOriginal
dng_date_time_storage_info fDateTimeOriginalStorageInfo
dng_date_time_info fDateTimeDigitized
dng_date_time_storage_info fDateTimeDigitizedStorageInfo
uint32 fTIFF_EP_StandardID
uint32 fExifVersion
uint32 fFlashPixVersion
dng_urational fExposureTime
dng_urational fFNumber
dng_srational fShutterSpeedValue
dng_urational fApertureValue
dng_srational fBrightnessValue
dng_srational fExposureBiasValue
dng_urational fMaxApertureValue
dng_urational fFocalLength
dng_urational fDigitalZoomRatio
dng_urational fExposureIndex
dng_urational fSubjectDistance
dng_urational fGamma
dng_urational fBatteryLevelR
dng_string fBatteryLevelA
uint32 fExposureProgram
uint32 fMeteringMode
uint32 fLightSource
uint32 fFlash
uint32 fFlashMask
uint32 fSensingMethod
uint32 fColorSpace
uint32 fFileSource
uint32 fSceneType
uint32 fCustomRendered
uint32 fExposureMode
uint32 fWhiteBalance
uint32 fSceneCaptureType
uint32 fGainControl
uint32 fContrast
uint32 fSaturation
uint32 fSharpness
uint32 fSubjectDistanceRange
uint32 fSelfTimerMode
uint32 fImageNumber
uint32 fFocalLengthIn35mmFilm
uint32 fISOSpeedRatings [3]
uint32 fSensitivityType
uint32 fStandardOutputSensitivity
uint32 fRecommendedExposureIndex
uint32 fISOSpeed
uint32 fISOSpeedLatitudeyyy
uint32 fISOSpeedLatitudezzz
uint32 fSubjectAreaCount
uint32 fSubjectArea [4]
uint32 fComponentsConfiguration
dng_urational fCompresssedBitsPerPixel
uint32 fPixelXDimension
uint32 fPixelYDimension
dng_urational fFocalPlaneXResolution
dng_urational fFocalPlaneYResolution
uint32 fFocalPlaneResolutionUnit
uint32 fCFARepeatPatternRows
uint32 fCFARepeatPatternCols
uint8 fCFAPattern [kMaxCFAPattern][kMaxCFAPattern]
dng_fingerprint fImageUniqueID
uint32 fGPSVersionID
dng_string fGPSLatitudeRef
dng_urational fGPSLatitude [3]
dng_string fGPSLongitudeRef
dng_urational fGPSLongitude [3]
uint32 fGPSAltitudeRef
dng_urational fGPSAltitude
dng_urational fGPSTimeStamp [3]
dng_string fGPSSatellites
dng_string fGPSStatus
dng_string fGPSMeasureMode
dng_urational fGPSDOP
dng_string fGPSSpeedRef
dng_urational fGPSSpeed
dng_string fGPSTrackRef
dng_urational fGPSTrack
dng_string fGPSImgDirectionRef
dng_urational fGPSImgDirection
dng_string fGPSMapDatum
dng_string fGPSDestLatitudeRef
dng_urational fGPSDestLatitude [3]
dng_string fGPSDestLongitudeRef
dng_urational fGPSDestLongitude [3]
dng_string fGPSDestBearingRef
dng_urational fGPSDestBearing
dng_string fGPSDestDistanceRef
dng_urational fGPSDestDistance
dng_string fGPSProcessingMethod
dng_string fGPSAreaInformation
dng_string fGPSDateStamp
uint32 fGPSDifferential
dng_urational fGPSHPositioningError
dng_string fInteroperabilityIndex
uint32 fInteroperabilityVersion
dng_string fRelatedImageFileFormat
uint32 fRelatedImageWidth
uint32 fRelatedImageLength
dng_string fCameraSerialNumber
dng_urational fLensInfo [4]
dng_string fLensID
dng_string fLensMake
dng_string fLensName
dng_string fLensSerialNumber
bool fLensNameWasReadFromExif
dng_urational fApproxFocusDistance
dng_srational fFlashCompensation
dng_string fOwnerName
dng_string fFirmware
dng_srational fTemperature
dng_urational fHumidity
dng_urational fPressure
dng_srational fWaterDepth
dng_urational fAcceleration
dng_srational fCameraElevationAngle
dng_string fTitle
dng_srational fLensDistortInfo [4]
Protected Member Functions
virtual bool Parse_ifd0 (dng_stream &stream, dng_shared &shared, uint32 parentCode, uint32 tagCode, uint32 tagType, uint32 tagCount, uint64 tagOffset)
virtual bool Parse_ifd0_main (dng_stream &stream, dng_shared &shared, uint32 parentCode, uint32 tagCode, uint32 tagType, uint32 tagCount, uint64 tagOffset)
virtual bool Parse_ifd0_exif (dng_stream &stream, dng_shared &shared, uint32 parentCode, uint32 tagCode, uint32 tagType, uint32 tagCount, uint64 tagOffset)
virtual bool Parse_gps (dng_stream &stream, dng_shared &shared, uint32 parentCode, uint32 tagCode, uint32 tagType, uint32 tagCount, uint64 tagOffset)
virtual bool Parse_interoperability (dng_stream &stream, dng_shared &shared, uint32 parentCode, uint32 tagCode, uint32 tagType, uint32 tagCount, uint64 tagOffset)
Detailed Description
Container class for parsing and holding EXIF tags.
Public member fields are documented in EXIF specification.
Member Function Documentation
ApertureValueToFNumber() [1/2]
real64 dng_exif::ApertureValueToFNumber (real64 av) static
Utility to convert aperture value (APEX units) to f-number.
Parameters
av The aperture value (APEX units) to convert.
Referenced by ApertureValueToFNumber(), and SetApertureValue().
ApertureValueToFNumber() [2/2]
real64 dng_exif::ApertureValueToFNumber (const dng_urational & av) static
Utility to convert aperture value (APEX units) to f-number.
Parameters
av The aperture value (APEX units) to convert.
References ApertureValueToFNumber().
CopyGPSFrom()
void dng_exif::CopyGPSFrom (const dng_exif & exif)
Copy all GPS-related fields.
Parameters
exif Source object from which to copy GPS fields.
EncodeFNumber()
dng_urational dng_exif::EncodeFNumber (real64 fs) static
Utility to encode f-number as a rational.
Parameters
fs The f-number to encode.
Referenced by SetFNumber().
FNumberToApertureValue() [1/2]
real64 dng_exif::FNumberToApertureValue (real64 fNumber) static
Utility to convert f-number to aperture value (APEX units).
Parameters
fNumber The f-number to convert.
Referenced by FNumberToApertureValue(), and SetFNumber().
FNumberToApertureValue() [2/2]
real64 dng_exif::FNumberToApertureValue (const dng_urational & fNumber) static
Utility to convert f-number to aperture value (APEX units).
Parameters
fNumber The f-number to convert.
References FNumberToApertureValue().
SetApertureValue()
void dng_exif::SetApertureValue (real64 av)
Set the FNumber and ApertureValue fields.
Parameters
av The aperture value (APEX units).
References ApertureValueToFNumber(), and SetFNumber().
SetExposureTime()
void dng_exif::SetExposureTime (real64 et, bool snap = true)
Set exposure time and shutter speed fields. Optionally fix up common errors and rounding issues with EXIF exposure times.
Parameters
et Exposure time in seconds.
snap Set to true to fix up common errors and rounding issues with EXIF exposure times.
References SnapExposureTime().
Referenced by SetShutterSpeedValue().
SetFNumber()
void dng_exif::SetFNumber (real64 fs)
Set the FNumber and ApertureValue fields.
Parameters
fs The f-number to set.
References EncodeFNumber(), and FNumberToApertureValue().
Referenced by SetApertureValue().
SetShutterSpeedValue()
void dng_exif::SetShutterSpeedValue (real64 ss)
Set shutter speed value (APEX units) and exposure time.
Parameters
ss Shutter speed in APEX units.
References SetExposureTime().
SnapExposureTime()
real64 dng_exif::SnapExposureTime (real64 et) static
Utility to fix up common errors and rounding issues with EXIF exposure times.
Referenced by SetExposureTime().
UpdateDateTime()
void dng_exif::UpdateDateTime (const dng_date_time_info & dt)
Set the DateTime field.
Parameters
dt The DateTime value.
The documentation for this class was generated from the following files:
dng_exif.h
dng_exif.cpp