DNG SDK 1.5: dng_bad_pixel_list Class Reference
dng_bad_pixel_list Class Reference
A list of bad pixels and rectangles (usually single rows or columns).
#include <dng_bad_pixels.h>
Public Types
enum { kNoIndex = 0xFFFFFFFF }
Public Member Functions
dng_bad_pixel_list ()
Create an empty bad pixel list.
uint32 PointCount () const
Returns the number of bad single pixels.
const dng_point & Point (uint32 index) const
uint32 RectCount () const
Returns the number of bad rectangles.
const dng_rect & Rect (uint32 index) const
bool IsEmpty () const
bool NotEmpty () const
void AddPoint (const dng_point &pt)
void AddRect (const dng_rect &r)
void Sort ()
bool IsPointIsolated (uint32 index, uint32 radius) const
bool IsRectIsolated (uint32 index, uint32 radius) const
bool IsPointValid (const dng_point &pt, const dng_rect &imageBounds, uint32 index=kNoIndex) const
Detailed Description
A list of bad pixels and rectangles (usually single rows or columns).
Member Function Documentation
AddPoint()
void dng_bad_pixel_list::AddPoint (const dng_point & pt)
Add the specified coordinate to the list of bad single pixels.
Parameters
pt The bad single pixel to add.
AddRect()
void dng_bad_pixel_list::AddRect (const dng_rect & r)
Add the specified rectangle to the list of bad rectangles.
Parameters
r The bad rectangle to add.
IsEmpty()
bool dng_bad_pixel_list::IsEmpty () const inline
Returns true iff there are zero bad single pixels and zero bad rectangles.
References PointCount(), and RectCount().
Referenced by NotEmpty().
IsPointIsolated()
bool dng_bad_pixel_list::IsPointIsolated (uint32 index, uint32 radius) const
Returns true iff the specified bad single pixel is isolated, i.e., there is no other bad single pixel or bad rectangle that lies within radius pixels of this bad single pixel.
Parameters
index The index of the bad single pixel to test.
radius The pixel radius to test for isolation.
References Point(), PointCount(), Rect(), and RectCount().
Referenced by dng_opcode_FixBadPixelsList::ProcessArea().
IsPointValid()
bool dng_bad_pixel_list::IsPointValid (const dng_point & pt, const dng_rect & imageBounds, uint32 index = kNoIndex) const
Returns true iff the specified point is valid, i.e., lies within the specified image bounds, is different from all other bad single pixels, and is not contained in any bad rectangle. The second and third conditions are only checked if provided with a starting search index.
Parameters
pt The point to test for validity.
imageBounds The pt must lie within imageBounds to be valid. \index The search index to use (or kNoIndex, to avoid a search) for checking for validity.
References Point(), PointCount(), Rect(), and RectCount().
IsRectIsolated()
bool dng_bad_pixel_list::IsRectIsolated (uint32 index, uint32 radius) const
Returns true iff the specified bad rectangle is isolated, i.e., there is no other bad single pixel or bad rectangle that lies within radius pixels of this bad rectangle.
Parameters
index The index of the bad rectangle to test.
radius The pixel radius to test for isolation.
References Rect(), and RectCount().
Referenced by dng_opcode_FixBadPixelsList::ProcessArea().
NotEmpty()
bool dng_bad_pixel_list::NotEmpty () const inline
Returns true iff there is at least one bad single pixel or at least one bad rectangle.
References IsEmpty().
Point()
const dng_point& dng_bad_pixel_list::Point (uint32 index) const inline
Retrieves the bad single pixel coordinate via the specified list index.
Parameters
index The list index from which to retrieve the bad single pixel coordinate.
Referenced by IsPointIsolated(), IsPointValid(), dng_opcode_FixBadPixelsList::ProcessArea(), and dng_opcode_FixBadPixelsList::PutData().
Rect()
const dng_rect& dng_bad_pixel_list::Rect (uint32 index) const inline
Retrieves the bad rectangle via the specified list index.
Parameters
index The list index from which to retrieve the bad rectangle coordinates.
Referenced by IsPointIsolated(), IsPointValid(), IsRectIsolated(), dng_opcode_FixBadPixelsList::ProcessArea(), and dng_opcode_FixBadPixelsList::PutData().
Sort()
void dng_bad_pixel_list::Sort ()
Sort the bad single pixels and bad rectangles by coordinates (top to bottom, then left to right).
References PointCount(), and RectCount().
The documentation for this class was generated from the following files:
dng_bad_pixels.h
dng_bad_pixels.cpp