DNG SDK 1.5: dng_warp_params Class Reference
dng_warp_params Class Reference abstract
Abstract base class holding common warp opcode parameters (e.g., number of planes, optical center) and common warp routines.
#include <dng_lens_correction.h>
Public Member Functions
dng_warp_params ()
Create empty (invalid) warp parameters.
dng_warp_params (uint32 planes, const dng_point_real64 &fCenter)
virtual bool IsNOPAll () const
Is the entire correction a NOP for all planes?
virtual bool IsNOP (uint32 plane) const
Is the entire correction a NOP for the specified plane?
virtual bool IsRadNOPAll () const
Is the radial correction a NOP for all planes?
virtual bool IsRadNOP (uint32 plane) const
Is the radial correction a NOP for the specified plane?
virtual bool IsTanNOPAll () const
Is the tangential correction a NOP for all planes?
virtual bool IsTanNOP (uint32 plane) const
Is the tangential correction a NOP for the specified plane?
virtual bool IsValid () const
Do these warp params appear valid?
virtual bool IsValidForNegative (const dng_negative &negative) const
Are these warp params valid for the specified negative?
virtual void PropagateToAllPlanes (uint32 totalPlanes)=0
Propagate warp parameters from first plane to all other planes.
virtual real64 Evaluate (uint32 plane, real64 r) const =0
virtual real64 EvaluateInverse (uint32 plane, real64 r) const
virtual real64 EvaluateRatio (uint32 plane, real64 r2) const =0
virtual dng_point_real64 EvaluateTangential (uint32 plane, real64 r2, const dng_point_real64 &diff, const dng_point_real64 &diff2) const =0
dng_point_real64 EvaluateTangential2 (uint32 plane, const dng_point_real64 &diff) const
dng_point_real64 EvaluateTangential3 (uint32 plane, real64 r2, const dng_point_real64 &diff) const
virtual real64 MaxSrcRadiusGap (real64 maxDstGap) const =0
virtual dng_point_real64 MaxSrcTanGap (dng_point_real64 minDst, dng_point_real64 maxDst) const =0
virtual real64 SafeMinRatio () const =0
virtual real64 SafeMaxRatio () const =0
virtual void Dump () const
Debug parameters.
Public Attributes
uint32 fPlanes
dng_point_real64 fCenter
Detailed Description
Abstract base class holding common warp opcode parameters (e.g., number of planes, optical center) and common warp routines.
Constructor & Destructor Documentation
dng_warp_params()
dng_warp_params::dng_warp_params (uint32 planes, const dng_point_real64 & fCenter)
Create warp parameters with specified number of planes and image center.
Parameters
planes The number of planes of parameters specified: It must be either 1 or equal to the number of planes of the image to be processed.
fCenter The image center in relative coordinates.
References DNG_ASSERT, and kMaxColorPlanes.
Member Function Documentation
Evaluate()
virtual real64 dng_warp_params::Evaluate (uint32 plane, real64 r) const pure virtual
Evaluate the 1D radial warp function for the specified plane. Parameter r is the destination (i.e., corrected) normalized radius, i.e., the normalized Euclidean distance between a corrected pixel position and the optical center in the image. r lies in the range [0,1]. The returned result is non-negative.
Implemented in dng_warp_params_fisheye, and dng_warp_params_rectilinear.
Referenced by EvaluateInverse().
EvaluateInverse()
real64 dng_warp_params::EvaluateInverse (uint32 plane, real64 r) const virtual
Compute and return the inverse of Evaluate () above. The base implementation uses Newton's method to perform the inversion. Parameter r is the source (i.e., uncorrected) normalized radius, i.e., normalized Euclidean distance between a corrected pixel position and the optical center in the image. Both r and the computed result are non-negative.
References Evaluate().
EvaluateRatio()
virtual real64 dng_warp_params::EvaluateRatio (uint32 plane, real64 r2) const pure virtual
Evaluate the 1D radial warp ratio function for the specified plane. Parameter r2 is the square of the destination (i.e., corrected) normalized radius, i.e., the square of the normalized Euclidean distance between a corrected pixel position and the optical center in the image. r2 must lie in the range [0,1]. Note that this is different than the Evaluate () function, above, in that the argument to EvaluateRatio () is the square of the radius, not the radius itself. The returned result is non-negative. Mathematically, EvaluateRatio (r * r) is the same as Evaluate (r) / r.
Implemented in dng_warp_params_fisheye, and dng_warp_params_rectilinear.
EvaluateTangential()
virtual dng_point_real64 dng_warp_params::EvaluateTangential (uint32 plane, real64 r2, const dng_point_real64 & diff, const dng_point_real64 & diff2) const pure virtual
Evaluate the 2D tangential warp for the specified plane. Parameter r2 is the square of the destination (i.e., corrected) normalized radius, i.e., the square of the normalized Euclidean distance between a corrected pixel position P and the optical center in the image. r2 must lie in the range [0,1]. diff contains the vertical and horizontal Euclidean distances (in pixels) between P and the optical center. diff2 contains the squares of the vertical and horizontal Euclidean distances (in pixels) between P and the optical center. The returned result is the tangential warp offset, measured in pixels.
Implemented in dng_warp_params_fisheye, and dng_warp_params_rectilinear.
Referenced by EvaluateTangential2(), and EvaluateTangential3().
EvaluateTangential2()
dng_point_real64 dng_warp_params::EvaluateTangential2 (uint32 plane, const dng_point_real64 & diff) const
Evaluate the 2D tangential warp for the specified plane. diff contains the vertical and horizontal Euclidean distances (in pixels) between the destination (i.e., corrected) pixel position and the optical center in the image. The returned result is the tangential warp offset, measured in pixels.
References EvaluateTangential().
Referenced by dng_warp_params_rectilinear::MaxSrcTanGap().
EvaluateTangential3()
dng_point_real64 dng_warp_params::EvaluateTangential3 (uint32 plane, real64 r2, const dng_point_real64 & diff) const
Evaluate the 2D tangential warp for the specified plane. Parameter r2 is the square of the destination (i.e., corrected) normalized radius, i.e., the square of the normalized Euclidean distance between a corrected pixel position P and the optical center in the image. r2 must lie in the range [0,1]. diff contains the vertical and horizontal Euclidean distances (in pixels) between P and the optical center. The returned result is the tangential warp offset, measured in pixels.
References EvaluateTangential().
MaxSrcRadiusGap()
virtual real64 dng_warp_params::MaxSrcRadiusGap (real64 maxDstGap) const pure virtual
Compute and return the maximum warped radius gap. Let D be a rectangle in a destination (corrected) image. Let rDstFar and rDstNear be the farthest and nearest points to the image center, respectively. Then the specified parameter maxDstGap is the Euclidean distance between rDstFar and rDstNear. Warp D through this warp function to a closed and bounded (generally not rectangular) region S. Let rSrcfar and rSrcNear be the farthest and nearest points to the image center, respectively. This routine returns a value that is at least (rSrcFar - rSrcNear).
Implemented in dng_warp_params_fisheye, and dng_warp_params_rectilinear.
Referenced by dng_filter_warp::SrcTileSize().
MaxSrcTanGap()
virtual dng_point_real64 dng_warp_params::MaxSrcTanGap (dng_point_real64 minDst, dng_point_real64 maxDst) const pure virtual
Compute and return the maximum warped tangential gap. minDst is the top-left pixel of the image in normalized pixel coordinates. maxDst is the bottom-right pixel of the image in normalized pixel coordinates. MaxSrcTanGap () computes the maximum absolute shift in normalized pixels in the horizontal and vertical directions that can occur as a result of the tangential warp.
Implemented in dng_warp_params_fisheye, and dng_warp_params_rectilinear.
Referenced by dng_filter_warp::SrcTileSize().
SafeMaxRatio()
virtual real64 dng_warp_params::SafeMaxRatio () const pure virtual
Compute and return the maximum src/dst ratio that should be used for this warp.
Implemented in dng_warp_params_fisheye, and dng_warp_params_rectilinear.
SafeMinRatio()
virtual real64 dng_warp_params::SafeMinRatio () const pure virtual
Compute and return the minimum src/dst ratio that should be used for this warp.
Implemented in dng_warp_params_fisheye, and dng_warp_params_rectilinear.
The documentation for this class was generated from the following files:
dng_lens_correction.h
dng_lens_correction.cpp