DNG SDK 1.5: dng_camera_profile_id Class Reference
dng_camera_profile_id Class Reference
An ID for a camera profile consisting of a name and optional fingerprint.
#include <dng_camera_profile.h>
Public Member Functions
dng_camera_profile_id ()
Construct an invalid camera profile ID (empty name and fingerprint).
dng_camera_profile_id (const char *name)
dng_camera_profile_id (const dng_string &name)
dng_camera_profile_id (const char *name, const dng_fingerprint &fingerprint)
dng_camera_profile_id (const dng_string &name, const dng_fingerprint &fingerprint)
const dng_string & Name () const
const dng_fingerprint & Fingerprint () const
bool operator== (const dng_camera_profile_id &id) const
bool operator!= (const dng_camera_profile_id &id) const
bool IsValid () const
Returns true iff the camera profile ID is valid.
void Clear ()
Detailed Description
An ID for a camera profile consisting of a name and optional fingerprint.
Constructor & Destructor Documentation
dng_camera_profile_id() [1/4]
dng_camera_profile_id::dng_camera_profile_id (const char * name) inline
Construct a camera profile ID with the specified name and no fingerprint.
Parameters
name The name of the camera profile ID.
dng_camera_profile_id() [2/4]
dng_camera_profile_id::dng_camera_profile_id (const dng_string & name) inline
Construct a camera profile ID with the specified name and no fingerprint.
Parameters
name The name of the camera profile ID.
dng_camera_profile_id() [3/4]
dng_camera_profile_id::dng_camera_profile_id (const char * name, const dng_fingerprint & fingerprint) inline
Construct a camera profile ID with the specified name and fingerprint.
Parameters
name The name of the camera profile ID.
fingerprint The fingerprint of the camera profile ID.
References DNG_ASSERT, and dng_fingerprint::IsValid().
dng_camera_profile_id() [4/4]
dng_camera_profile_id::dng_camera_profile_id (const dng_string & name, const dng_fingerprint & fingerprint) inline
Construct a camera profile ID with the specified name and fingerprint.
Parameters
name The name of the camera profile ID.
fingerprint The fingerprint of the camera profile ID.
References DNG_ASSERT, and dng_fingerprint::IsValid().
Member Function Documentation
Clear()
void dng_camera_profile_id::Clear () inline
Resets the name and fingerprint, thereby making this camera profile ID invalid.
References dng_camera_profile_id().
Fingerprint()
const dng_fingerprint& dng_camera_profile_id::Fingerprint () const inline
Getter for the fingerprint of the camera profile ID.
Return values
The fingerprint of the camera profile ID.
Name()
const dng_string& dng_camera_profile_id::Name () const inline
Getter for the name of the camera profile ID.
Return values
The name of the camera profile ID.
operator!=()
bool dng_camera_profile_id::operator!= (const dng_camera_profile_id & id) const inline
Test for inequality of two camera profile IDs.
Parameters
id The id of the camera profile ID to compare.
operator==()
bool dng_camera_profile_id::operator== (const dng_camera_profile_id & id) const inline
Test for equality of two camera profile IDs.
Parameters
id The id of the camera profile ID to compare.
The documentation for this class was generated from the following file:
dng_camera_profile.h