DNG SDK 1.5: AutoPtr< T > Class Template Reference
AutoPtr< T > Class Template Reference
A class intended to be used in stack scope to hold a pointer from new. The held pointer will be deleted automatically if the scope is left without calling Release on the AutoPtr first.
#include <dng_auto_ptr.h>
Public Member Functions
AutoPtr ()
Construct an AutoPtr with no referent.
AutoPtr (T *p)
~AutoPtr ()
Reset is called on destruction.
void Alloc ()
Call Reset with a pointer from new. Uses T's default constructor.
T * Get () const
T * Release ()
void Reset (T *p)
void Reset ()
T * operator-> () const
T & operator * () const
Friends
void Swap (AutoPtr< T > &x, AutoPtr< T > &y)
Swap with another auto ptr.
Detailed Description
template<class T>
class AutoPtr< T >
A class intended to be used in stack scope to hold a pointer from new. The held pointer will be deleted automatically if the scope is left without calling Release on the AutoPtr first.
Constructor & Destructor Documentation
AutoPtr()
template<class T> AutoPtr< T >::AutoPtr (T * p) inline explicit
Construct an AutoPtr which owns the argument pointer.
Parameters
p pointer which constructed AutoPtr takes ownership of. p will be deleted on destruction or Reset unless Release is called first.
Member Function Documentation
Get()
template<class T> T* AutoPtr< T >::Get () const inline
Return the owned pointer of this AutoPtr, NULL if none. No change in ownership or other effects occur.
Referenced by dng_opcode_list::Apply(), dng_linearization_info::ColumnBlack(), dng_linearization_info::ColumnBlackCount(), dng_render::dng_render(), dng_info::IsValidDNG(), dng_linearization_info::MaxBlackLevel(), dng_info::Parse(), dng_info::PostParse(), dng_opcode_FixVignetteRadial::Prepare(), dng_read_tiles_task::Process(), dng_opcode_MapTable::ProcessArea(), dng_opcode_Unknown::PutData(), dng_render::Render(), dng_linearization_info::RowBlack(), and dng_linearization_info::RowBlackCount().
operator *()
template<class T> T& AutoPtr< T >::operator * () const inline
Returns a reference to the object that the owned pointer points to. It is an error to call this if the AutoPtr has NULL as its value.
operator->()
template<class T> T* AutoPtr< T >::operator-> () const inline
Allows members of the owned pointer to be accessed directly. It is an error to call this if the AutoPtr has NULL as its value.
Release()
template<class T > T * AutoPtr< T >::Release ()
Return the owned pointer of this AutoPtr, NULL if none. The AutoPtr gives up ownership and takes NULL as its value.
Referenced by dng_filter_opcode::Apply(), dng_opcode_WarpRectilinear::Apply(), dng_opcode_WarpFisheye::Apply(), dng_gain_map::GetStream(), dng_hue_sat_map::Interpolate(), and dng_render::Render().
Reset() [1/2]
template<class T> void AutoPtr< T >::Reset (T * p)
If a pointer is owned, it is deleted. Ownership is taken of passed in pointer.
Parameters
p pointer which constructed AutoPtr takes ownership of. p will be deleted on destruction or Reset unless Release is called first.
Referenced by dng_filter_opcode::Apply(), dng_opcode_WarpRectilinear::Apply(), dng_opcode_WarpFisheye::Apply(), dng_render::dng_render(), dng_1d_table::Initialize(), dng_info::Parse(), dng_opcode_MapTable::Prepare(), dng_opcode_FixVignetteRadial::Prepare(), dng_jpeg_image_encode_task::Process(), dng_read_tiles_task::Process(), dng_write_tiles_task::Process(), dng_render::Render(), and dng_find_new_raw_image_digest_task::Start().
Reset() [2/2]
template<class T> void AutoPtr< T >::Reset ()
If a pointer is owned, it is deleted and the AutoPtr takes NULL as its value.
The documentation for this class was generated from the following file:
dng_auto_ptr.h