DNG SDK 1.5: dng_render_task Class Reference
dng_render_task Class Reference
Public Member Functions
dng_render_task (const dng_image &srcImage, const dng_image *srcMask, dng_image &dstImage, const dng_negative &negative, const dng_render &params, const dng_point &srcOffset)
virtual dng_rect SrcArea (const dng_rect &dstArea)
virtual void Start (uint32 threadCount, const dng_rect &dstArea, const dng_point &tileSize, dng_memory_allocator *allocator, dng_abort_sniffer *sniffer)
virtual void ProcessArea (uint32 threadIndex, dng_pixel_buffer &srcBuffer, dng_pixel_buffer &dstBuffer)
Public Member Functions inherited from dng_filter_task
dng_filter_task (const char *name, const dng_image &srcImage, dng_image &dstImage)
virtual dng_point SrcTileSize (const dng_point &dstTileSize)
virtual void Process (uint32 threadIndex, const dng_rect &area, dng_abort_sniffer *sniffer)
Public Member Functions inherited from dng_area_task
dng_area_task (const char *name="unnamed dng_area_task")
const char * Name () const
virtual uint32 MaxThreads () const
virtual uint32 MinTaskArea () const
operation. (Partitions can be smaller due to small inputs and edge cases.)
virtual dng_point UnitCell () const
virtual dng_point MaxTileSize () const
virtual dng_rect RepeatingTile1 () const
virtual dng_rect RepeatingTile2 () const
virtual dng_rect RepeatingTile3 () const
virtual void Finish (uint32 threadCount)
dng_point FindTileSize (const dng_rect &area) const
void ProcessOnThread (uint32 threadIndex, const dng_rect &area, const dng_point &tileSize, dng_abort_sniffer *sniffer, dng_area_task_progress *progress)
virtual dng_base_tile_iterator * MakeTileIterator (uint32 threadIndex, const dng_rect &tile, const dng_rect &area) const
virtual dng_base_tile_iterator * MakeTileIterator (uint32 threadIndex, const dng_point &tileSize, const dng_rect &area) const
Protected Attributes
const dng_image * fSrcMask
const dng_negative & fNegative
const dng_render & fParams
dng_point fSrcOffset
dng_1d_table fZeroOffsetRamp
dng_vector fCameraWhite
dng_matrix fCameraToRGB
AutoPtr< dng_hue_sat_map > fHueSatMap
dng_1d_table fExposureRamp
AutoPtr< dng_hue_sat_map > fLookTable
dng_1d_table fToneCurve
dng_matrix fRGBtoFinal
dng_1d_table fEncodeGamma
AutoPtr< dng_1d_table > fHueSatMapEncode
AutoPtr< dng_1d_table > fHueSatMapDecode
AutoPtr< dng_1d_table > fLookTableEncode
AutoPtr< dng_1d_table > fLookTableDecode
AutoPtr< dng_memory_block > fTempBuffer [kMaxMPThreads]
AutoPtr< dng_memory_block > fMaskBuffer [kMaxMPThreads]
Protected Attributes inherited from dng_filter_task
const dng_image & fSrcImage
dng_image & fDstImage
uint32 fSrcPlane
uint32 fSrcPlanes
uint32 fSrcPixelType
uint32 fDstPlane
uint32 fDstPlanes
uint32 fDstPixelType
dng_point fSrcRepeat
dng_point fSrcTileSize
AutoPtr< dng_memory_block > fSrcBuffer [kMaxMPThreads]
AutoPtr< dng_memory_block > fDstBuffer [kMaxMPThreads]
Protected Attributes inherited from dng_area_task
uint32 fMaxThreads
uint32 fMinTaskArea
dng_point fUnitCell
dng_point fMaxTileSize
dng_string fName
Additional Inherited Members
Static Public Member Functions inherited from dng_area_task
static void Perform (dng_area_task &task, const dng_rect &area, dng_memory_allocator *allocator, dng_abort_sniffer *sniffer, dng_area_task_progress *progress)
Member Function Documentation
ProcessArea()
void dng_render_task::ProcessArea (uint32 threadIndex, dng_pixel_buffer & srcBuffer, dng_pixel_buffer & dstBuffer) virtual
Implements filtering operation from one buffer to another. Source and destination pixels are set up in member fields of this class. Ideally, no allocation should be done in this routine.
Parameters
threadIndex The thread on which this routine is being called, between 0 and threadCount - 1 for the threadCount passed to Start method.
srcBuffer Input area and source pixels.
dstBuffer Output area and destination pixels.
Implements dng_filter_task.
References dng_memory_block::Buffer_real32(), dng_pixel_buffer::DirtyPixel(), and dng_image::Get().
SrcArea()
dng_rect dng_render_task::SrcArea (const dng_rect & dstArea) virtual
Compute the source area needed for a given destination area. Default implementation assumes destination area is equal to source area for all cases.
Parameters
dstArea Area to for which pixels will be computed.
Return values
The source area needed as input to calculate the requested destination area.
Reimplemented from dng_filter_task.
Start()
void dng_render_task::Start (uint32 threadCount, const dng_rect & dstArea, const dng_point & tileSize, dng_memory_allocator * allocator, dng_abort_sniffer * sniffer) virtual
Called prior to processing on specific threads. Can be used to allocate per-thread memory buffers, etc.
Parameters
threadCount Total number of threads that will be used for processing. Less than or equal to MaxThreads of dng_area_task.
tileSize Size of source tiles which will be processed. (Not all tiles will be this size due to edge conditions.)
allocator dng_memory_allocator to use for allocating temporary buffers, etc.
sniffer Sniffer to test for user cancellation and to set up progress.
Reimplemented from dng_filter_task.
References dng_negative::CameraNeutral(), dng_negative::HasCameraNeutral(), dng_1d_table::Initialize(), dng_negative::IsMonochrome(), dng_filter_task::Start(), and dng_render::WhiteXY().
The documentation for this class was generated from the following file:
dng_render.cpp