DNG SDK 1.5: dng_encode_proxy_task Class Reference
dng_encode_proxy_task Class Reference
Public Member Functions
dng_encode_proxy_task (dng_host &host, const dng_image &srcImage, dng_image &dstImage, const real64 *lower, const real64 *upper, bool isSceneReferred, real64 stage3BlackLevel, real64 *blackLevel)
virtual dng_rect RepeatingTile1 () const
virtual dng_rect RepeatingTile2 () const
virtual void Process (uint32 threadIndex, const dng_rect &tile, dng_abort_sniffer *sniffer)
and progress updates.
Public Member Functions inherited from dng_area_task
dng_area_task (const char *name="unnamed dng_area_task")
const char * Name () const
virtual uint32 MaxThreads () const
virtual uint32 MinTaskArea () const
operation. (Partitions can be smaller due to small inputs and edge cases.)
virtual dng_point UnitCell () const
virtual dng_point MaxTileSize () const
virtual dng_rect RepeatingTile3 () const
virtual void Start (uint32 threadCount, const dng_rect &dstArea, const dng_point &tileSize, dng_memory_allocator *allocator, dng_abort_sniffer *sniffer)
virtual void Finish (uint32 threadCount)
dng_point FindTileSize (const dng_rect &area) const
void ProcessOnThread (uint32 threadIndex, const dng_rect &area, const dng_point &tileSize, dng_abort_sniffer *sniffer, dng_area_task_progress *progress)
virtual dng_base_tile_iterator * MakeTileIterator (uint32 threadIndex, const dng_rect &tile, const dng_rect &area) const
virtual dng_base_tile_iterator * MakeTileIterator (uint32 threadIndex, const dng_point &tileSize, const dng_rect &area) const
Additional Inherited Members
Static Public Member Functions inherited from dng_area_task
static void Perform (dng_area_task &task, const dng_rect &area, dng_memory_allocator *allocator, dng_abort_sniffer *sniffer, dng_area_task_progress *progress)
Protected Attributes inherited from dng_area_task
uint32 fMaxThreads
uint32 fMinTaskArea
dng_point fUnitCell
dng_point fMaxTileSize
dng_string fName
Member Function Documentation
Process()
void dng_encode_proxy_task::Process (uint32 threadIndex, const dng_rect & tile, dng_abort_sniffer * sniffer) virtual
and progress updates.
Process one tile or fully partitioned area. This method is overridden by derived classes to implement the actual image processing. Note that the sniffer can be ignored if it is certain that a processing task will complete very quickly. This method should never be called directly but rather accessed via Process. There is no allocator parameter as all allocation should be done in Start.
Parameters
threadIndex 0 to threadCount - 1 index indicating which thread this is. (Can be used to get a thread-specific buffer allocated in the Start method.)
tile Area to process.
sniffer dng_abort_sniffer to use to check for user cancellation
Implements dng_area_task.
References dng_memory_block::Buffer_uint16(), dng_pixel_buffer::ConstPixel_uint16(), dng_pixel_buffer::DirtyPixel_uint8(), and dng_image::Planes().
RepeatingTile1()
virtual dng_rect dng_encode_proxy_task::RepeatingTile1 () const inline virtual
Getter for RepeatingTile1. RepeatingTile1, RepeatingTile2, and RepeatingTile3 are used to establish a set of 0 to 3 tile patterns for which the resulting partitions that the final Process method is called on will not cross tile boundaries in any of the tile patterns. This can be used for a processing routine that needs to read from two tiles and write to a third such that all the tiles are aligned and sized in a certain way. A RepeatingTile value is valid if it is non-empty. Higher numbered RepeatingTile patterns are only used if all lower ones are non-empty. A RepeatingTile pattern must be a multiple of UnitCell in size for all constraints of the partitionerr to be met.
Reimplemented from dng_area_task.
References dng_image::RepeatingTile().
RepeatingTile2()
virtual dng_rect dng_encode_proxy_task::RepeatingTile2 () const inline virtual
Getter for RepeatingTile2. RepeatingTile1, RepeatingTile2, and RepeatingTile3 are used to establish a set of 0 to 3 tile patterns for which the resulting partitions that the final Process method is called on will not cross tile boundaries in any of the tile patterns. This can be used for a processing routine that needs to read from two tiles and write to a third such that all the tiles are aligned and sized in a certain way. A RepeatingTile value is valid if it is non-empty. Higher numbered RepeatingTile patterns are only used if all lower ones are non-empty. A RepeatingTile pattern must be a multiple of UnitCell in size for all constraints of the partitionerr to be met.
Reimplemented from dng_area_task.
References dng_image::RepeatingTile().
The documentation for this class was generated from the following file:
dng_negative.cpp