DNG SDK 1.5: dng_memory_data Class Reference
dng_memory_data Class Reference
Class to provide resource acquisition is instantiation discipline for small memory allocations.
#include <dng_memory.h>
Public Member Functions
dng_memory_data ()
dng_memory_data (uint32 size)
dng_memory_data (const dng_safe_uint32 &size)
dng_memory_data (uint32 count, std::size_t elementSize)
~dng_memory_data ()
Release memory buffer using free.
void Allocate (uint32 size)
void Allocate (const dng_safe_uint32 &size)
void Allocate (uint32 count, std::size_t elementSize)
void Allocate (const dng_safe_uint32 &count, std::size_t elementSize)
void Clear ()
void * Buffer ()
const void * Buffer () const
char * Buffer_char ()
const char * Buffer_char () const
uint8 * Buffer_uint8 ()
const uint8 * Buffer_uint8 () const
uint16 * Buffer_uint16 ()
const uint16 * Buffer_uint16 () const
int16 * Buffer_int16 ()
const int16 * Buffer_int16 () const
uint32 * Buffer_uint32 ()
const uint32 * Buffer_uint32 () const
int32 * Buffer_int32 ()
const int32 * Buffer_int32 () const
uint64 * Buffer_uint64 ()
const uint64 * Buffer_uint64 () const
int64 * Buffer_int64 ()
const int64 * Buffer_int64 () const
real32 * Buffer_real32 ()
const real32 * Buffer_real32 () const
real64 * Buffer_real64 ()
const real64 * Buffer_real64 () const
Detailed Description
Class to provide resource acquisition is instantiation discipline for small memory allocations.
This class does not use dng_memory_allocator for memory allocation.
Constructor & Destructor Documentation
dng_memory_data() [1/3]
dng_memory_data::dng_memory_data ()
Construct an empty memory buffer using malloc.
Exceptions
dng_memory_full with fErrorCode equal to dng_error_memory.
dng_memory_data() [2/3]
dng_memory_data::dng_memory_data (uint32 size)
Construct memory buffer of size bytes using malloc.
Parameters
size Number of bytes of memory needed.
Exceptions
dng_memory_full with fErrorCode equal to dng_error_memory.
References Allocate().
dng_memory_data() [3/3]
dng_memory_data::dng_memory_data (uint32 count, std::size_t elementSize)
Note: This constructor is for internal use only and should not be considered part of the DNG SDK API.
Construct memory buffer of count elements of elementSize bytes each.
Parameters
count Number of elements.
elementSize Size of each element.
Exceptions
dng_memory_full with fErrorCode equal to dng_error_memory.
References Allocate().
Member Function Documentation
Allocate() [1/2]
void dng_memory_data::Allocate (uint32 size)
Clear existing memory buffer and allocate new memory of size bytes.
Parameters
size Number of bytes of memory needed.
Exceptions
dng_memory_full with fErrorCode equal to dng_error_memory.
References Clear(), and ThrowMemoryFull().
Referenced by Allocate(), and dng_memory_data().
Allocate() [2/2]
void dng_memory_data::Allocate (uint32 count, std::size_t elementSize)
Note: This method is for internal use only and should not be considered part of the DNG SDK API.
Clear existing memory buffer and allocate new memory of count elements of elementSize bytes each.
Parameters
count Number of elements.
elementSize Size of each element.
Exceptions
dng_memory_full with fErrorCode equal to dng_error_memory.
References Allocate(), and ThrowOverflow().
Buffer() [1/2]
void* dng_memory_data::Buffer () inline
Return pointer to allocated memory as a void *..
Return values
void * valid for as many bytes as were allocated.
Referenced by Buffer_char(), Buffer_int16(), Buffer_int32(), Buffer_int64(), Buffer_real32(), Buffer_real64(), Buffer_uint16(), Buffer_uint32(), Buffer_uint64(), Buffer_uint8(), and dng_stream::CopyToStream().
Buffer() [2/2]
const void* dng_memory_data::Buffer () const inline
Return pointer to allocated memory as a const void *.
Return values
const void * valid for as many bytes as were allocated.
Buffer_char() [1/2]
char* dng_memory_data::Buffer_char () inline
Return pointer to allocated memory as a char *.
Return values
char * valid for as many bytes as were allocated.
References Buffer().
Referenced by dng_iptc::Parse().
Buffer_char() [2/2]
const char* dng_memory_data::Buffer_char () const inline
Return pointer to allocated memory as a const char *.
Return values
const char * valid for as many bytes as were allocated.
References Buffer().
Buffer_int16() [1/2]
int16* dng_memory_data::Buffer_int16 () inline
Return pointer to allocated memory as a int16 *.
Return values
int16 * valid for as many bytes as were allocated.
References Buffer().
Buffer_int16() [2/2]
const int16* dng_memory_data::Buffer_int16 () const inline
Return pointer to allocated memory as a const int16 *.
Return values
const int16 * valid for as many bytes as were allocated.
References Buffer().
Buffer_int32() [1/2]
int32* dng_memory_data::Buffer_int32 () inline
Return pointer to allocated memory as a const int32 *.
Return values
const int32 * valid for as many bytes as were allocated.
References Buffer().
Buffer_int32() [2/2]
const int32* dng_memory_data::Buffer_int32 () const inline
Return pointer to allocated memory as a const int32 *.
Return values
const int32 * valid for as many bytes as were allocated.
References Buffer().
Buffer_int64() [1/2]
int64* dng_memory_data::Buffer_int64 () inline
Return pointer to allocated memory as a const int64 *.
Return values
const int64 * valid for as many bytes as were allocated.
References Buffer().
Buffer_int64() [2/2]
const int64* dng_memory_data::Buffer_int64 () const inline
Return pointer to allocated memory as a const int64 *.
Return values
const int64 * valid for as many bytes as were allocated.
References Buffer().
Buffer_real32() [1/2]
real32* dng_memory_data::Buffer_real32 () inline
Return pointer to allocated memory as a real32 *.
Return values
real32 * valid for as many bytes as were allocated.
References Buffer().
Buffer_real32() [2/2]
const real32* dng_memory_data::Buffer_real32 () const inline
Return pointer to allocated memory as a const real32 *.
Return values
const real32 * valid for as many bytes as were allocated.
References Buffer().
Buffer_real64() [1/2]
real64* dng_memory_data::Buffer_real64 () inline
Return pointer to allocated memory as a real64 *.
Return values
real64 * valid for as many bytes as were allocated.
References Buffer().
Buffer_real64() [2/2]
const real64* dng_memory_data::Buffer_real64 () const inline
Return pointer to allocated memory as a const real64 *.
Return values
const real64 * valid for as many bytes as were allocated.
References Buffer().
Buffer_uint16() [1/2]
uint16* dng_memory_data::Buffer_uint16 () inline
Return pointer to allocated memory as a uint16 *.
Return values
uint16 * valid for as many bytes as were allocated.
References Buffer().
Buffer_uint16() [2/2]
const uint16* dng_memory_data::Buffer_uint16 () const inline
Return pointer to allocated memory as a const uint16 *.
Return values
const uint16 * valid for as many bytes as were allocated.
References Buffer().
Buffer_uint32() [1/2]
uint32* dng_memory_data::Buffer_uint32 () inline
Return pointer to allocated memory as a uint32 *.
Return values
uint32 * valid for as many bytes as were allocated.
References Buffer().
Buffer_uint32() [2/2]
const uint32* dng_memory_data::Buffer_uint32 () const inline
Return pointer to allocated memory as a uint32 *.
Return values
uint32 * valid for as many bytes as were allocated.
References Buffer().
Buffer_uint64() [1/2]
uint64* dng_memory_data::Buffer_uint64 () inline
Return pointer to allocated memory as a uint64 *.
Return values
uint64 * valid for as many bytes as were allocated.
References Buffer().
Buffer_uint64() [2/2]
const uint64* dng_memory_data::Buffer_uint64 () const inline
Return pointer to allocated memory as a uint64 *.
Return values
uint64 * valid for as many bytes as were allocated.
References Buffer().
Buffer_uint8() [1/2]
uint8* dng_memory_data::Buffer_uint8 () inline
Return pointer to allocated memory as a uint8 *.
Return values
uint8 * valid for as many bytes as were allocated.
References Buffer().
Buffer_uint8() [2/2]
const uint8* dng_memory_data::Buffer_uint8 () const inline
Return pointer to allocated memory as a const uint8 *.
Return values
const uint8 * valid for as many bytes as were allocated.
References Buffer().
Clear()
void dng_memory_data::Clear ()
Release any allocated memory using free. Object is still valid and Allocate can be called again.
Referenced by Allocate(), and ~dng_memory_data().
The documentation for this class was generated from the following files:
dng_memory.h
dng_memory.cpp