DNG SDK 1.5: dng_find_new_raw_image_digest_task Class Reference
dng_find_new_raw_image_digest_task Class Reference
Public Member Functions
dng_find_new_raw_image_digest_task (const dng_image &image, uint32 pixelType)
virtual void Start (uint32 threadCount, const dng_rect &, const dng_point &tileSize, dng_memory_allocator *allocator, dng_abort_sniffer *)
virtual void Process (uint32 threadIndex, const dng_rect &tile, dng_abort_sniffer *)
and progress updates.
dng_fingerprint Result ()
Public Member Functions inherited from dng_area_task
dng_area_task (const char *name="unnamed dng_area_task")
const char * Name () const
virtual uint32 MaxThreads () const
virtual uint32 MinTaskArea () const
operation. (Partitions can be smaller due to small inputs and edge cases.)
virtual dng_point UnitCell () const
virtual dng_point MaxTileSize () const
virtual dng_rect RepeatingTile1 () const
virtual dng_rect RepeatingTile2 () const
virtual dng_rect RepeatingTile3 () const
virtual void Finish (uint32 threadCount)
dng_point FindTileSize (const dng_rect &area) const
void ProcessOnThread (uint32 threadIndex, const dng_rect &area, const dng_point &tileSize, dng_abort_sniffer *sniffer, dng_area_task_progress *progress)
virtual dng_base_tile_iterator * MakeTileIterator (uint32 threadIndex, const dng_rect &tile, const dng_rect &area) const
virtual dng_base_tile_iterator * MakeTileIterator (uint32 threadIndex, const dng_point &tileSize, const dng_rect &area) const
Additional Inherited Members
Static Public Member Functions inherited from dng_area_task
static void Perform (dng_area_task &task, const dng_rect &area, dng_memory_allocator *allocator, dng_abort_sniffer *sniffer, dng_area_task_progress *progress)
Protected Attributes inherited from dng_area_task
uint32 fMaxThreads
uint32 fMinTaskArea
dng_point fUnitCell
dng_point fMaxTileSize
dng_string fName
Member Function Documentation
Process()
virtual void dng_find_new_raw_image_digest_task::Process (uint32 threadIndex, const dng_rect & tile, dng_abort_sniffer * sniffer) inline virtual
and progress updates.
Process one tile or fully partitioned area. This method is overridden by derived classes to implement the actual image processing. Note that the sniffer can be ignored if it is certain that a processing task will complete very quickly. This method should never be called directly but rather accessed via Process. There is no allocator parameter as all allocation should be done in Start.
Parameters
threadIndex 0 to threadCount - 1 index indicating which thread this is. (Can be used to get a thread-specific buffer allocated in the Start method.)
tile Area to process.
sniffer dng_abort_sniffer to use to check for user cancellation
Implements dng_area_task.
References dng_image::Bounds(), dng_memory_block::Buffer(), DNG_ASSERT, dng_image::Get(), and dng_image::Planes().
Start()
virtual void dng_find_new_raw_image_digest_task::Start (uint32 threadCount, const dng_rect & dstArea, const dng_point & tileSize, dng_memory_allocator * allocator, dng_abort_sniffer * sniffer) inline virtual
Task startup method called before any processing is done on partitions. The Start method is called before any processing is done and can be overridden to allocate temporary buffers, etc.
Parameters
threadCount Total number of threads that will be used for processing. Less than or equal to MaxThreads.
dstArea Area to be processed in the current run of the task.
tileSize Size of source tiles which will be processed. (Not all tiles will be this size due to edge conditions.)
allocator dng_memory_allocator to use for allocating temporary buffers, etc.
sniffer Sniffer to test for user cancellation and to set up progress.
Reimplemented from dng_area_task.
References dng_memory_allocator::Allocate(), dng_image::Bounds(), dng_image::Planes(), AutoPtr< T >::Reset(), AutoArray< T >::Reset(), and ThrowProgramError().
The documentation for this class was generated from the following file:
dng_negative.cpp