DNG SDK 1.5: dng_info Class Reference
dng_info Class Reference
Top-level structure of DNG file with access to metadata.
#include <dng_info.h>
Public Member Functions
uint32 IFDCount () const
Returns the number of parsed SubIFDs (including the main IFD).
uint32 ChainedIFDCount () const
Returns the number of chained IFDs.
uint32 ChainedSubIFDCount (uint32 chainIndex) const
Returns number SubIFDs for a chained IFD.
virtual void Parse (dng_host &host, dng_stream &stream)
virtual void PostParse (dng_host &host)
Must be called immediately after a successful Parse operation.
virtual bool IsValidDNG ()
Public Attributes
uint64 fTIFFBlockOffset
uint64 fTIFFBlockOriginalOffset
bool fBigEndian
uint32 fMagic
AutoPtr< dng_exif > fExif
AutoPtr< dng_shared > fShared
int32 fMainIndex
int32 fMaskIndex
int32 fDepthIndex
int32 fEnhancedIndex
std::vector< dng_ifd * > fIFD
std::vector< dng_ifd * > fChainedIFD
std::vector< std::vector< dng_ifd * > > fChainedSubIFD
Protected Member Functions
virtual void ValidateMagic ()
virtual void ParseTag (dng_host &host, dng_stream &stream, dng_exif *exif, dng_shared *shared, dng_ifd *ifd, uint32 parentCode, uint32 tagCode, uint32 tagType, uint32 tagCount, uint64 tagOffset, int64 offsetDelta)
virtual bool ValidateIFD (dng_stream &stream, uint64 ifdOffset, int64 offsetDelta)
virtual void ParseIFD (dng_host &host, dng_stream &stream, dng_exif *exif, dng_shared *shared, dng_ifd *ifd, uint64 ifdOffset, int64 offsetDelta, uint32 parentCode)
virtual bool ParseMakerNoteIFD (dng_host &host, dng_stream &stream, uint64 ifdSize, uint64 ifdOffset, int64 offsetDelta, uint64 minOffset, uint64 maxOffset, uint32 parentCode)
virtual void ParseMakerNote (dng_host &host, dng_stream &stream, uint32 makerNoteCount, uint64 makerNoteOffset, int64 offsetDelta, uint64 minOffset, uint64 maxOffset)
virtual void ParseSonyPrivateData (dng_host &host, dng_stream &stream, uint64 count, uint64 oldOffset, uint64 newOffset)
virtual void ParseDNGPrivateData (dng_host &host, dng_stream &stream)
Protected Attributes
uint32 fMakerNoteNextIFD
Detailed Description
Top-level structure of DNG file with access to metadata.
See DNG 1.1.0 specification for information on member fields of this class.
Member Function Documentation
IsValidDNG()
bool dng_info::IsValidDNG () virtual
Test validity of DNG data.
Return values
true if stream provided a valid DNG.
References AutoPtr< T >::Get(), IFDCount(), and ReportError().
Parse()
void dng_info::Parse (dng_host & host, dng_stream & stream) virtual
Read dng_info from a dng_stream
Parameters
host DNG host used for progress updating, abort testing, buffer allocation, etc.
stream Stream to read DNG data from.
References ChainedIFDCount(), AutoPtr< T >::Get(), dng_stream::Get_uint16(), dng_stream::Get_uint32(), IFDCount(), dng_camera_profile::IsValid(), kMaxChainedIFDs, kMaxSubIFDs, dng_stream::Length(), dng_host::Make_dng_exif(), dng_host::Make_dng_ifd(), dng_host::Make_dng_shared(), dng_camera_profile::Parse(), dng_stream::Position(), dng_stream::PositionInOriginalFile(), ReportError(), ReportWarning(), AutoPtr< T >::Reset(), dng_stream::SetBigEndian(), dng_stream::SetLittleEndian(), dng_stream::SetReadPosition(), and ThrowBadFormat().
The documentation for this class was generated from the following files:
dng_info.h
dng_info.cpp