DNG SDK 1.5: dng_md5_printer Class Reference
dng_md5_printer Class Reference
Class to hash binary data to a fingerprint using the MD5 Message-Digest Algorithm.
#include <dng_fingerprint.h>
Public Member Functions
void Reset ()
Reset the fingerprint.
void Process (const void *data, uint32 inputLen)
void Process (const char *text)
const dng_fingerprint & Result ()
Get the fingerprint (i.e., result of the hash).
Detailed Description
Class to hash binary data to a fingerprint using the MD5 Message-Digest Algorithm.
Member Function Documentation
Process() [1/2]
void dng_md5_printer::Process (const void * data, uint32 inputLen)
Append the data to the stream to be hashed.
Parameters
data The data to be hashed.
inputLen The length of data, in bytes.
References DNG_ASSERT.
Referenced by dng_hue_sat_map::Interpolate(), Process(), dng_jpeg_image_find_digest_task::Process(), and Result().
Process() [2/2]
void dng_md5_printer::Process (const char * text) inline
Append the string to the stream to be hashed.
Parameters
text The string to be hashed.
References Process().
The documentation for this class was generated from the following files:
dng_fingerprint.h
dng_fingerprint.cpp