DNG SDK 1.5: dng_memory_block Class Reference
dng_memory_block Class Reference
Class to provide resource acquisition is instantiation discipline for image buffers and other larger memory allocations.
#include <dng_memory.h>
Public Member Functions
dng_memory_block * Clone (dng_memory_allocator &allocator) const
uint32 LogicalSize () const
void * Buffer ()
const void * Buffer () const
char * Buffer_char ()
const char * Buffer_char () const
uint8 * Buffer_uint8 ()
const uint8 * Buffer_uint8 () const
uint16 * Buffer_uint16 ()
const uint16 * Buffer_uint16 () const
int16 * Buffer_int16 ()
const int16 * Buffer_int16 () const
uint32 * Buffer_uint32 ()
const uint32 * Buffer_uint32 () const
int32 * Buffer_int32 ()
const int32 * Buffer_int32 () const
real32 * Buffer_real32 ()
const real32 * Buffer_real32 () const
real64 * Buffer_real64 ()
const real64 * Buffer_real64 () const
Protected Member Functions
dng_memory_block (uint32 logicalSize)
uint32 PhysicalSize ()
void SetBuffer (void *p)
Detailed Description
Class to provide resource acquisition is instantiation discipline for image buffers and other larger memory allocations.
This class requires a dng_memory_allocator for allocation.
Member Function Documentation
Buffer() [1/2]
void* dng_memory_block::Buffer () inline
Return pointer to allocated memory as a void *..
Return values
void * valid for as many bytes as were allocated.
Referenced by Buffer_char(), Buffer_int16(), Buffer_int32(), Buffer_real32(), Buffer_real64(), Buffer_uint16(), Buffer_uint32(), Buffer_uint8(), dng_inplace_opcode_task::Process(), dng_find_new_raw_image_digest_task::Process(), and dng_opcode_Unknown::PutData().
Buffer() [2/2]
const void* dng_memory_block::Buffer () const inline
Return pointer to allocated memory as a const void *.
Return values
const void * valid for as many bytes as were allocated.
Buffer_char() [1/2]
char* dng_memory_block::Buffer_char () inline
Return pointer to allocated memory as a char *.
Return values
char * valid for as many bytes as were allocated.
References Buffer().
Buffer_char() [2/2]
const char* dng_memory_block::Buffer_char () const inline
Return pointer to allocated memory as a const char *.
Return values
const char * valid for as many bytes as were allocated.
References Buffer().
Buffer_int16() [1/2]
int16* dng_memory_block::Buffer_int16 () inline
Return pointer to allocated memory as a int16 *.
Return values
int16 * valid for as many bytes as were allocated.
References Buffer().
Buffer_int16() [2/2]
const int16* dng_memory_block::Buffer_int16 () const inline
Return pointer to allocated memory as a const int16 *.
Return values
const int16 * valid for as many bytes as were allocated.
References Buffer().
Buffer_int32() [1/2]
int32* dng_memory_block::Buffer_int32 () inline
Return pointer to allocated memory as a int32 *.
Return values
int32 * valid for as many bytes as were allocated.
References Buffer().
Buffer_int32() [2/2]
const int32* dng_memory_block::Buffer_int32 () const inline
Return pointer to allocated memory as a const int32 *.
Return values
const int32 * valid for as many bytes as were allocated.
References Buffer().
Buffer_real32() [1/2]
real32* dng_memory_block::Buffer_real32 () inline
Return pointer to allocated memory as a real32 *.
Return values
real32 * valid for as many bytes as were allocated.
References Buffer().
Referenced by dng_gain_map::Entry(), dng_1d_table::Initialize(), dng_opcode_DeltaPerRow::ProcessArea(), dng_opcode_DeltaPerColumn::ProcessArea(), dng_opcode_ScalePerRow::ProcessArea(), dng_opcode_ScalePerColumn::ProcessArea(), dng_resample_task::ProcessArea(), dng_render_task::ProcessArea(), dng_opcode_DeltaPerRow::PutData(), dng_opcode_DeltaPerColumn::PutData(), dng_opcode_ScalePerRow::PutData(), and dng_opcode_ScalePerColumn::PutData().
Buffer_real32() [2/2]
const real32* dng_memory_block::Buffer_real32 () const inline
Return pointer to allocated memory as a const real32 *.
Return values
const real32 * valid for as many bytes as were allocated.
References Buffer().
Buffer_real64() [1/2]
real64* dng_memory_block::Buffer_real64 () inline
Return pointer to allocated memory as a real64 *.
Return values
real64 * valid for as many bytes as were allocated.
References Buffer().
Referenced by dng_linearization_info::ColumnBlack(), dng_linearization_info::MaxBlackLevel(), and dng_linearization_info::RowBlack().
Buffer_real64() [2/2]
const real64* dng_memory_block::Buffer_real64 () const inline
Return pointer to allocated memory as a const real64 *.
Return values
const real64 * valid for as many bytes as were allocated.
References Buffer().
Buffer_uint16() [1/2]
uint16* dng_memory_block::Buffer_uint16 () inline
Return pointer to allocated memory as a uint16 *.
Return values
uint16 * valid for as many bytes as were allocated.
References Buffer().
Referenced by dng_opcode_MapTable::Prepare(), dng_opcode_FixVignetteRadial::Prepare(), dng_encode_proxy_task::Process(), dng_opcode_MapTable::ProcessArea(), and dng_opcode_MapTable::PutData().
Buffer_uint16() [2/2]
const uint16* dng_memory_block::Buffer_uint16 () const inline
Return pointer to allocated memory as a const uint16 *.
Return values
const uint16 * valid for as many bytes as were allocated.
References Buffer().
Buffer_uint32() [1/2]
uint32* dng_memory_block::Buffer_uint32 () inline
Return pointer to allocated memory as a uint32 *.
Return values
uint32 * valid for as many bytes as were allocated.
References Buffer().
Buffer_uint32() [2/2]
const uint32* dng_memory_block::Buffer_uint32 () const inline
Return pointer to allocated memory as a const uint32 *.
Return values
const uint32 * valid for as many bytes as were allocated.
References Buffer().
Buffer_uint8() [1/2]
uint8* dng_memory_block::Buffer_uint8 () inline
Return pointer to allocated memory as a uint8 *.
Return values
uint8 * valid for as many bytes as were allocated.
References Buffer().
Referenced by dng_memory_stream::CopyToStream().
Buffer_uint8() [2/2]
const uint8* dng_memory_block::Buffer_uint8 () const inline
Return pointer to allocated memory as a const uint8 *.
Return values
const uint8 * valid for as many bytes as were allocated.
References Buffer().
LogicalSize()
uint32 dng_memory_block::LogicalSize () const inline
Getter for available size, in bytes, of memory block.
Return values
size in bytes of available memory in memory block.
Referenced by dng_linearization_info::ColumnBlackCount(), dng_linearization_info::MaxBlackLevel(), dng_opcode_Unknown::PutData(), and dng_linearization_info::RowBlackCount().
The documentation for this class was generated from the following files:
dng_memory.h
dng_memory.cpp