DNG SDK 1.5: dng_memory_allocator Class Reference
dng_memory_allocator Class Reference
Interface for dng_memory_block allocator.
#include <dng_memory.h>
Public Member Functions
virtual dng_memory_block * Allocate (uint32 size)
virtual void * Malloc (size_t size)
virtual void Free (void *ptr)
Detailed Description
Interface for dng_memory_block allocator.
Member Function Documentation
Allocate()
dng_memory_block * dng_memory_allocator::Allocate (uint32 size) virtual
Allocate a dng_memory block.
Parameters
size Number of bytes in memory block.
Return values
A dng_memory_block with at least size bytes of valid storage.
Exceptions
dng_exception with fErrorCode equal to dng_error_memory.
References ThrowMemoryFull().
Referenced by dng_host::Allocate(), dng_stream::AsMemoryBlock(), dng_1d_table::Initialize(), dng_opcode_MapTable::Prepare(), dng_opcode_FixVignetteRadial::Prepare(), dng_filter_task::Start(), dng_inplace_opcode_task::Start(), dng_resample_task::Start(), and dng_find_new_raw_image_digest_task::Start().
Free()
void dng_memory_allocator::Free (void * ptr) virtual
Free the specified block of memory previously allocated with Malloc. Default implementation uses standard library 'free' routine.
Malloc()
void * dng_memory_allocator::Malloc (size_t size) virtual
Directly allocate a block of at least 'size' bytes.
Parameters
size Number of bytes in memory block.
Return values
A pointer to a contiguous block of memory with at least size bytes of valid storage. Caller is responsible for freeing the memory with Free. Default implementation uses standard library 'malloc' routine.
The documentation for this class was generated from the following files:
dng_memory.h
dng_memory.cpp