DNG SDK 1.5: dng_opcode_FixVignetteRadial Class Reference
dng_opcode_FixVignetteRadial Class Reference
Radially-symmetric lens vignette correction opcode.
#include <dng_lens_correction.h>
Public Member Functions
dng_opcode_FixVignetteRadial (const dng_vignette_radial_params &params, uint32 flags)
dng_opcode_FixVignetteRadial (dng_stream &stream)
const dng_vignette_radial_params & Params () const
virtual bool IsNOP () const
virtual bool IsValidForNegative (const dng_negative &) const
Is this opcode valid for the specified negative?
virtual void PutData (dng_stream &stream) const
virtual uint32 BufferPixelType (uint32)
The pixel data type of this opcode.
virtual void Prepare (dng_negative &negative, uint32 threadCount, const dng_point &tileSize, const dng_rect &imageBounds, uint32 imagePlanes, uint32 bufferPixelType, dng_memory_allocator &allocator)
virtual void ProcessArea (dng_negative &negative, uint32 threadIndex, dng_pixel_buffer &buffer, const dng_rect &dstArea, const dng_rect &imageBounds)
Public Member Functions inherited from dng_inplace_opcode
virtual dng_rect ModifiedBounds (const dng_rect &imageBounds)
virtual void Apply (dng_host &host, dng_negative &negative, AutoPtr< dng_image > &image)
Apply this opcode to the specified image with associated negative.
Public Member Functions inherited from dng_opcode
uint32 OpcodeID () const
The ID of this opcode.
uint32 MinVersion () const
The first DNG version that supports this opcode.
uint32 Flags () const
The flags for this opcode.
bool Optional () const
Is this opcode optional?
bool SkipIfPreview () const
Should the opcode be skipped when rendering preview images?
bool WasReadFromStream () const
Was this opcode read from a data stream?
uint32 Stage () const
void SetStage (uint32 stage)
bool AboutToApply (dng_host &host, dng_negative &negative, const dng_rect &imageBounds, uint32 imagePlanes)
Protected Member Functions
virtual dng_vignette_radial_params MakeParamsForRender (const dng_negative &negative)
Protected Member Functions inherited from dng_inplace_opcode
dng_inplace_opcode (uint32 opcodeID, uint32 minVersion, uint32 flags)
dng_inplace_opcode (uint32 opcodeID, dng_stream &stream, const char *name)
Protected Member Functions inherited from dng_opcode
dng_opcode (uint32 opcodeID, uint32 minVersion, uint32 flags)
dng_opcode (uint32 opcodeID, dng_stream &stream, const char *name)
virtual void DoAboutToApply (dng_host &, dng_negative &, const dng_rect &, uint32)
Static Protected Member Functions
static uint32 ParamBytes ()
Protected Attributes
dng_vignette_radial_params fParams
uint32 fImagePlanes
int64 fSrcOriginH
int64 fSrcOriginV
int64 fSrcStepH
int64 fSrcStepV
uint32 fTableInputBits
uint32 fTableOutputBits
AutoPtr< dng_memory_block > fGainTable
AutoPtr< dng_memory_block > fMaskBuffers [kMaxMPThreads]
Additional Inherited Members
Public Types inherited from dng_opcode
enum { kFlag_None = 0, kFlag_Optional = 1, kFlag_SkipIfPreview = 2 }
Opcode flags.
Detailed Description
Radially-symmetric lens vignette correction opcode.
Member Function Documentation
IsNOP()
bool dng_opcode_FixVignetteRadial::IsNOP () const virtual
Is the opcode a NOP (i.e., does nothing)? An opcode could be a NOP for some specific parameters.
Reimplemented from dng_opcode.
Prepare()
void dng_opcode_FixVignetteRadial::Prepare (dng_negative & negative, uint32 threadCount, const dng_point & tileSize, const dng_rect & imageBounds, uint32 imagePlanes, uint32 bufferPixelType, dng_memory_allocator & allocator) virtual
Startup method called before any processing is performed on pixel areas. It can be used to allocate (per-thread) memory and setup tasks.
Parameters
negative The negative object to be processed.
threadCount Total number of threads that will be used for processing. Less than or equal to MaxThreads.
tileSize Size of source tiles which will be processed. (Not all tiles will be this size due to edge conditions.)
imageBounds Total size of image to be processed.
imagePlanes Number of planes in the image. Less than or equal to kMaxColorPlanes.
bufferPixelType Pixel type of image buffer (see dng_tag_types.h).
allocator dng_memory_allocator to use for allocating temporary buffers, etc.
Reimplemented from dng_inplace_opcode.
References dng_memory_allocator::Allocate(), dng_memory_block::Buffer_uint16(), DNG_ASSERT, AutoPtr< T >::Get(), dng_1d_table::Initialize(), dng_1d_table::Interpolate(), kMaxColorPlanes, kMaxMPThreads, dng_negative::PixelAspectRatio(), AutoPtr< T >::Reset(), ThrowBadFormat(), and ThrowProgramError().
ProcessArea()
void dng_opcode_FixVignetteRadial::ProcessArea (dng_negative & negative, uint32 threadIndex, dng_pixel_buffer & buffer, const dng_rect & dstArea, const dng_rect & imageBounds) virtual
Implements image processing operation in a single buffer. The source pixels are provided as input to the buffer, and this routine calculates and writes the destination pixels to the same buffer. Ideally, no allocation should be done in this routine.
Parameters
negative The negative associated with the pixels to be processed.
threadIndex The thread on which this routine is being called, between 0 and threadCount - 1 for the threadCount passed to Prepare method.
buffer Source and Destination pixels.
dstArea Destination pixel processing area.
imageBounds Total image area to be processed; dstArea will always lie within these bounds.
Implements dng_inplace_opcode.
PutData()
void dng_opcode_FixVignetteRadial::PutData (dng_stream & stream) const virtual
Write opcode to a stream.
Parameters
stream The stream to which to write the opcode data.
Reimplemented from dng_opcode.
References DNG_REQUIRE, dng_stream::Put_real64(), and dng_stream::Put_uint32().
The documentation for this class was generated from the following files:
dng_lens_correction.h
dng_lens_correction.cpp