DNG SDK 1.5: dng_pixel_buffer Class Reference
dng_pixel_buffer Class Reference
Holds a buffer of pixel data with "pixel geometry" metadata.
#include <dng_pixel_buffer.h>
Public Member Functions
dng_pixel_buffer (const dng_rect &area, uint32 plane, uint32 planes, uint32 pixelType, uint32 planarConfiguration, void *data)
dng_pixel_buffer (const dng_pixel_buffer &buffer)
dng_pixel_buffer & operator= (const dng_pixel_buffer &buffer)
uint32 PixelRange () const
const dng_rect & Area () const
uint32 Planes () const
int32 RowStep () const
int32 PlaneStep () const
const void * ConstPixel (int32 row, int32 col, uint32 plane=0) const
void * DirtyPixel (int32 row, int32 col, uint32 plane=0)
const uint8 * ConstPixel_uint8 (int32 row, int32 col, uint32 plane=0) const
const uint8 * ConstPixel_uint8_overrideType (int32 row, int32 col, uint32 plane=0) const
uint8 * DirtyPixel_uint8 (int32 row, int32 col, uint32 plane=0)
uint8 * DirtyPixel_uint8_overrideType (int32 row, int32 col, uint32 plane=0)
const int8 * ConstPixel_int8 (int32 row, int32 col, uint32 plane=0) const
int8 * DirtyPixel_int8 (int32 row, int32 col, uint32 plane=0)
const uint16 * ConstPixel_uint16 (int32 row, int32 col, uint32 plane=0) const
uint16 * DirtyPixel_uint16 (int32 row, int32 col, uint32 plane=0)
const int16 * ConstPixel_int16 (int32 row, int32 col, uint32 plane=0) const
int16 * DirtyPixel_int16 (int32 row, int32 col, uint32 plane=0)
const uint32 * ConstPixel_uint32 (int32 row, int32 col, uint32 plane=0) const
uint32 * DirtyPixel_uint32 (int32 row, int32 col, uint32 plane=0)
const int32 * ConstPixel_int32 (int32 row, int32 col, uint32 plane=0) const
int32 * DirtyPixel_int32 (int32 row, int32 col, uint32 plane=0)
const real32 * ConstPixel_real32 (int32 row, int32 col, uint32 plane=0) const
real32 * DirtyPixel_real32 (int32 row, int32 col, uint32 plane=0)
void SetConstant (const dng_rect &area, uint32 plane, uint32 planes, uint32 value)
void SetConstant_uint8 (const dng_rect &area, uint32 plane, uint32 planes, uint8 value)
void SetConstant_uint16 (const dng_rect &area, uint32 plane, uint32 planes, uint16 value)
void SetConstant_int16 (const dng_rect &area, uint32 plane, uint32 planes, int16 value)
void SetConstant_uint32 (const dng_rect &area, uint32 plane, uint32 planes, uint32 value)
void SetConstant_real32 (const dng_rect &area, uint32 plane, uint32 planes, real32 value)
void SetZero (const dng_rect &area, uint32 plane, uint32 planes)
void CopyArea (const dng_pixel_buffer &src, const dng_rect &area, uint32 srcPlane, uint32 dstPlane, uint32 planes)
void CopyArea (const dng_pixel_buffer &src, const dng_rect &area, uint32 plane, uint32 planes)
void RepeatArea (const dng_rect &srcArea, const dng_rect &dstArea)
void RepeatSubArea (const dng_rect subArea, uint32 repeatV=1, uint32 repeatH=1)
Replicates a sub-area of a buffer to fill the entire buffer.
void ShiftRight (uint32 shift)
void FlipH ()
void FlipV ()
void FlipZ ()
bool EqualArea (const dng_pixel_buffer &rhs, const dng_rect &area, uint32 plane, uint32 planes) const
real64 MaximumDifference (const dng_pixel_buffer &rhs, const dng_rect &area, uint32 plane, uint32 planes) const
Static Public Member Functions
static dng_point RepeatPhase (const dng_rect &srcArea, const dng_rect &dstArea)
Public Attributes
dng_rect fArea
uint32 fPlane
uint32 fPlanes
int32 fRowStep
int32 fColStep
int32 fPlaneStep
uint32 fPixelType
uint32 fPixelSize
void * fData
bool fDirty
Detailed Description
Holds a buffer of pixel data with "pixel geometry" metadata.
The pixel geometry describes the layout in terms of how many planes, rows and columns plus the steps (in bytes) between each column, row and plane.
Constructor & Destructor Documentation
dng_pixel_buffer()
dng_pixel_buffer::dng_pixel_buffer (const dng_rect & area, uint32 plane, uint32 planes, uint32 pixelType, uint32 planarConfiguration, void * data)
Note: This constructor is for internal use only and should not be considered part of the DNG SDK API.
Initialize the pixel buffer according to the given parameters (see below). May throw an error if arithmetic overflow occurs when computing the row, column or plane step, or if an invalid value was passed for planarConfiguration.
Parameters
area Area covered by the pixel buffer
plane Index of the first plane
planes Number of planes
pixelType Pixel data type (one of the values defined in dng_tag_types.h)
planarConfiguration Layout of the pixel planes in memory: One of pcInterleaved, pcPlanar, or pcRowInterleaved (defined in dng_tag_values.h)
data Pointer to the pixel data
References ThrowOverflow(), and ThrowProgramError().
Member Function Documentation
Area()
const dng_rect& dng_pixel_buffer::Area () const inline
Get extent of pixels in buffer
Return values
Rectangle giving valid extent of buffer.
Referenced by dng_filter_opcode_task::ProcessArea().
ConstPixel()
const void* dng_pixel_buffer::ConstPixel (int32 row, int32 col, uint32 plane = 0) const inline
Get read-only untyped (void *) pointer to pixel data starting at a specific pixel in the buffer.
Parameters
row Start row for buffer pointer.
col Start column for buffer pointer.
plane Start plane for buffer pointer.
Return values
Pointer to pixel data as void *.
Referenced by CopyArea(), EqualArea(), MaximumDifference(), dng_limit_float_depth_task< simd >::Process(), dng_image::Put(), and RepeatArea().
ConstPixel_int16()
const int16* dng_pixel_buffer::ConstPixel_int16 (int32 row, int32 col, uint32 plane = 0) const inline
Get read-only int16 * to pixel data starting at a specific pixel in the buffer.
Parameters
row Start row for buffer pointer.
col Start column for buffer pointer.
plane Start plane for buffer pointer.
Return values
Pointer to pixel data as int16 *.
ConstPixel_int32()
const int32* dng_pixel_buffer::ConstPixel_int32 (int32 row, int32 col, uint32 plane = 0) const inline
Get read-only int32 * to pixel data starting at a specific pixel in the buffer.
Parameters
row Start row for buffer pointer.
col Start column for buffer pointer.
plane Start plane for buffer pointer.
Return values
Pointer to pixel data as int32 *.
ConstPixel_int8()
const int8* dng_pixel_buffer::ConstPixel_int8 (int32 row, int32 col, uint32 plane = 0) const inline
Get read-only int8 * to pixel data starting at a specific pixel in the buffer.
Parameters
row Start row for buffer pointer.
col Start column for buffer pointer.
plane Start plane for buffer pointer.
Return values
Pointer to pixel data as int8 *.
ConstPixel_real32()
const real32* dng_pixel_buffer::ConstPixel_real32 (int32 row, int32 col, uint32 plane = 0) const inline
Get read-only real32 * to pixel data starting at a specific pixel in the buffer.
Parameters
row Start row for buffer pointer.
col Start column for buffer pointer.
plane Start plane for buffer pointer.
Return values
Pointer to pixel data as real32 *.
Referenced by dng_resample_task::ProcessArea(), and dng_filter_warp::ProcessArea().
ConstPixel_uint16()
const uint16* dng_pixel_buffer::ConstPixel_uint16 (int32 row, int32 col, uint32 plane = 0) const inline
Get read-only uint16 * to pixel data starting at a specific pixel in the buffer.
Parameters
row Start row for buffer pointer.
col Start column for buffer pointer.
plane Start plane for buffer pointer.
Return values
Pointer to pixel data as uint16 *.
Referenced by dng_encode_proxy_task::Process(), dng_opcode_FixBadPixelsConstant::ProcessArea(), and dng_fast_interpolator::ProcessArea().
ConstPixel_uint32()
const uint32* dng_pixel_buffer::ConstPixel_uint32 (int32 row, int32 col, uint32 plane = 0) const inline
Get read-only uint32 * to pixel data starting at a specific pixel in the buffer.
Parameters
row Start row for buffer pointer.
col Start column for buffer pointer.
plane Start plane for buffer pointer.
Return values
Pointer to pixel data as uint32 *.
ConstPixel_uint8()
const uint8* dng_pixel_buffer::ConstPixel_uint8 (int32 row, int32 col, uint32 plane = 0) const inline
Get read-only uint8 * to pixel data starting at a specific pixel in the buffer.
Parameters
row Start row for buffer pointer.
col Start column for buffer pointer.
plane Start plane for buffer pointer.
Return values
Pointer to pixel data as uint8 *.
CopyArea() [1/2]
void dng_pixel_buffer::CopyArea (const dng_pixel_buffer & src, const dng_rect & area, uint32 srcPlane, uint32 dstPlane, uint32 planes)
Copy image data from an area of one pixel buffer to same area of another.
Parameters
src Buffer to copy from.
area Rectangle of pixel buffer to copy.
srcPlane Plane to start copy in src.
dstPlane Plane to start copy in dst.
planes Number of planes to copy.
References ConstPixel(), DirtyPixel(), and OptimizeOrder().
Referenced by CopyArea(), dng_opcode_FixBadPixelsConstant::ProcessArea(), and dng_opcode_FixBadPixelsList::ProcessArea().
CopyArea() [2/2]
void dng_pixel_buffer::CopyArea (const dng_pixel_buffer & src, const dng_rect & area, uint32 plane, uint32 planes) inline
Copy image data from an area of one pixel buffer to same area of another.
Parameters
src Buffer to copy from.
area Rectangle of pixel buffer to copy.
plane Plane to start copy in src and this.
planes Number of planes to copy.
References CopyArea().
DirtyPixel()
void* dng_pixel_buffer::DirtyPixel (int32 row, int32 col, uint32 plane = 0) inline
Get a writable untyped (void *) pointer to pixel data starting at a specific pixel in the buffer.
Parameters
row Start row for buffer pointer.
col Start column for buffer pointer.
plane Start plane for buffer pointer.
Return values
Pointer to pixel data as void *.
References DNG_ASSERT.
Referenced by CopyArea(), dng_image::Get(), dng_limit_float_depth_task< simd >::Process(), dng_render_task::ProcessArea(), RepeatArea(), dng_simple_image::Rotate(), SetConstant(), ShiftRight(), and dng_simple_image::Trim().
DirtyPixel_int16()
int16* dng_pixel_buffer::DirtyPixel_int16 (int32 row, int32 col, uint32 plane = 0) inline
Get a writable int16 * to pixel data starting at a specific pixel in the buffer.
Parameters
row Start row for buffer pointer.
col Start column for buffer pointer.
plane Start plane for buffer pointer.
Return values
Pointer to pixel data as int16 *.
DirtyPixel_int32()
int32* dng_pixel_buffer::DirtyPixel_int32 (int32 row, int32 col, uint32 plane = 0) inline
Get a writable int32 * to pixel data starting at a specific pixel in the buffer.
Parameters
row Start row for buffer pointer.
col Start column for buffer pointer.
plane Start plane for buffer pointer.
Return values
Pointer to pixel data as int32 *.
DirtyPixel_int8()
int8* dng_pixel_buffer::DirtyPixel_int8 (int32 row, int32 col, uint32 plane = 0) inline
Get a writable int8 * to pixel data starting at a specific pixel in the buffer.
Parameters
row Start row for buffer pointer.
col Start column for buffer pointer.
plane Start plane for buffer pointer.
Return values
Pointer to pixel data as int8 *.
DirtyPixel_real32()
real32* dng_pixel_buffer::DirtyPixel_real32 (int32 row, int32 col, uint32 plane = 0) inline
Get a writable real32 * to pixel data starting at a specific pixel in the buffer.
Parameters
row Start row for buffer pointer.
col Start column for buffer pointer.
plane Start plane for buffer pointer.
Return values
Pointer to pixel data as real32 *.
Referenced by dng_opcode_GainMap::ProcessArea(), dng_opcode_DeltaPerRow::ProcessArea(), dng_opcode_DeltaPerColumn::ProcessArea(), dng_opcode_ScalePerRow::ProcessArea(), dng_opcode_ScalePerColumn::ProcessArea(), and dng_filter_warp::ProcessArea().
DirtyPixel_uint16()
uint16* dng_pixel_buffer::DirtyPixel_uint16 (int32 row, int32 col, uint32 plane = 0) inline
Get a writable uint16 * to pixel data starting at a specific pixel in the buffer.
Parameters
row Start row for buffer pointer.
col Start column for buffer pointer.
plane Start plane for buffer pointer.
Return values
Pointer to pixel data as uint16 *.
Referenced by dng_opcode_FixBadPixelsConstant::ProcessArea(), and dng_fast_interpolator::ProcessArea().
DirtyPixel_uint32()
uint32* dng_pixel_buffer::DirtyPixel_uint32 (int32 row, int32 col, uint32 plane = 0) inline
Get a writable uint32 * to pixel data starting at a specific pixel in the buffer.
Parameters
row Start row for buffer pointer.
col Start column for buffer pointer.
plane Start plane for buffer pointer.
Return values
Pointer to pixel data as uint32 *.
DirtyPixel_uint8()
uint8* dng_pixel_buffer::DirtyPixel_uint8 (int32 row, int32 col, uint32 plane = 0) inline
Get a writable uint8 * to pixel data starting at a specific pixel in the buffer.
Parameters
row Start row for buffer pointer.
col Start column for buffer pointer.
plane Start plane for buffer pointer.
Return values
Pointer to pixel data as uint8 *.
Referenced by dng_encode_proxy_task::Process().
EqualArea()
bool dng_pixel_buffer::EqualArea (const dng_pixel_buffer & rhs, const dng_rect & area, uint32 plane, uint32 planes) const
Return true if the contents of an area of the pixel buffer area are the same as those of another.
Parameters
rhs Buffer to compare against.
area Rectangle of pixel buffer to test.
plane Plane to start comparing.
planes Number of planes to compare.
Return values
bool true if areas are equal, false otherwise.
References ConstPixel().
Referenced by dng_image::EqualArea().
FlipH()
void dng_pixel_buffer::FlipH ()
Change metadata so pixels are iterated in opposite horizontal order. This operation does not require movement of actual pixel data.
FlipV()
void dng_pixel_buffer::FlipV ()
Change metadata so pixels are iterated in opposite vertical order. This operation does not require movement of actual pixel data.
FlipZ()
void dng_pixel_buffer::FlipZ ()
Change metadata so pixels are iterated in opposite plane order. This operation does not require movement of actual pixel data.
MaximumDifference()
real64 dng_pixel_buffer::MaximumDifference (const dng_pixel_buffer & rhs, const dng_rect & area, uint32 plane, uint32 planes) const
Return the absolute value of the maximum difference between two pixel buffers. Used for comparison testing with tolerance
Parameters
rhs Buffer to compare against.
area Rectangle of pixel buffer to test.
plane Plane to start comparing.
planes Number of planes to compare.
Return values
larges absolute value difference between the corresponding pixels each buffer across area.
References ConstPixel(), ThrowNotYetImplemented(), and ThrowProgramError().
PixelRange()
uint32 dng_pixel_buffer::PixelRange () const
Get the range of pixel values.
Return values
Range of value a pixel can take. (Meaning [0, max] for unsigned case. Signed case is biased so [-32768, max - 32768].)
Planes()
uint32 dng_pixel_buffer::Planes () const inline
Number of planes of image data.
Return values
Number of planes held in buffer.
Referenced by dng_opcode_GainMap::ProcessArea(), dng_opcode_MapTable::ProcessArea(), dng_opcode_MapPolynomial::ProcessArea(), dng_opcode_DeltaPerRow::ProcessArea(), dng_opcode_DeltaPerColumn::ProcessArea(), dng_opcode_ScalePerRow::ProcessArea(), and dng_opcode_ScalePerColumn::ProcessArea().
PlaneStep()
int32 dng_pixel_buffer::PlaneStep () const inline
Step, in pixels not bytes, between planes of data in buffer.
Return values
plane step in pixels. May be negative.
RepeatArea()
void dng_pixel_buffer::RepeatArea (const dng_rect & srcArea, const dng_rect & dstArea)
Repeat the image data in srcArea across dstArea. (Generally used for padding operations.)
Parameters
srcArea Area to repeat from.
dstArea Area to fill with data from srcArea.
References ConstPixel(), DirtyPixel(), and RepeatPhase().
Referenced by RepeatSubArea().
RepeatPhase()
dng_point dng_pixel_buffer::RepeatPhase (const dng_rect & srcArea, const dng_rect & dstArea) static
Calculate the offset phase of destination rectangle relative to source rectangle. Phase is based on a 0,0 origin and the notion of repeating srcArea across dstArea. It is the number of pixels into srcArea to start repeating from when tiling dstArea.
Return values
dng_point containing horizontal and vertical phase.
References DNG_REPORT.
Referenced by RepeatArea().
RowStep()
int32 dng_pixel_buffer::RowStep () const inline
Step, in pixels not bytes, between rows of data in buffer.
Return values
row step in pixels. May be negative.
Referenced by dng_opcode_DeltaPerColumn::ProcessArea(), dng_opcode_ScalePerColumn::ProcessArea(), and dng_filter_warp::ProcessArea().
SetConstant()
void dng_pixel_buffer::SetConstant (const dng_rect & area, uint32 plane, uint32 planes, uint32 value)
Initialize a rectangular area of pixel buffer to a constant.
Parameters
area Rectangle of pixel buffer to set.
plane Plane to start filling on.
planes Number of planes to fill.
value Constant value to set pixels to.
References DirtyPixel(), and OptimizeOrder().
Referenced by SetConstant_int16(), SetConstant_real32(), SetConstant_uint16(), SetConstant_uint32(), SetConstant_uint8(), and SetZero().
SetConstant_int16()
void dng_pixel_buffer::SetConstant_int16 (const dng_rect & area, uint32 plane, uint32 planes, int16 value) inline
Initialize a rectangular area of pixel buffer to a constant signed 16-bit value.
Parameters
area Rectangle of pixel buffer to set.
plane Plane to start filling on.
planes Number of planes to fill.
value Constant int16 value to set pixels to.
References DNG_ASSERT, and SetConstant().
SetConstant_real32()
void dng_pixel_buffer::SetConstant_real32 (const dng_rect & area, uint32 plane, uint32 planes, real32 value) inline
Initialize a rectangular area of pixel buffer to a constant real 32-bit value.
Parameters
area Rectangle of pixel buffer to set.
plane Plane to start filling on.
planes Number of planes to fill.
value Constant real32 value to set pixels to.
References DNG_ASSERT, and SetConstant().
SetConstant_uint16()
void dng_pixel_buffer::SetConstant_uint16 (const dng_rect & area, uint32 plane, uint32 planes, uint16 value) inline
Initialize a rectangular area of pixel buffer to a constant unsigned 16-bit value.
Parameters
area Rectangle of pixel buffer to set.
plane Plane to start filling on.
planes Number of planes to fill.
value Constant uint16 value to set pixels to.
References DNG_ASSERT, and SetConstant().
SetConstant_uint32()
void dng_pixel_buffer::SetConstant_uint32 (const dng_rect & area, uint32 plane, uint32 planes, uint32 value) inline
Initialize a rectangular area of pixel buffer to a constant unsigned 32-bit value.
Parameters
area Rectangle of pixel buffer to set.
plane Plane to start filling on.
planes Number of planes to fill.
value Constant uint32 value to set pixels to.
References DNG_ASSERT, and SetConstant().
SetConstant_uint8()
void dng_pixel_buffer::SetConstant_uint8 (const dng_rect & area, uint32 plane, uint32 planes, uint8 value) inline
Initialize a rectangular area of pixel buffer to a constant unsigned 8-bit value.
Parameters
area Rectangle of pixel buffer to set.
plane Plane to start filling on.
planes Number of planes to fill.
value Constant uint8 value to set pixels to.
References DNG_ASSERT, and SetConstant().
SetZero()
void dng_pixel_buffer::SetZero (const dng_rect & area, uint32 plane, uint32 planes)
Initialize a rectangular area of pixel buffer to zeros.
Parameters
area Rectangle of pixel buffer to zero.
plane Plane to start filling on.
planes Number of planes to fill.
References SetConstant(), and ThrowNotYetImplemented().
ShiftRight()
void dng_pixel_buffer::ShiftRight (uint32 shift)
Apply a right shift (C++ oerpator >>) to all pixel values. Only implemented for 16-bit (signed or unsigned) pixel buffers.
Parameters
shift Number of bits by which to right shift each pixel value.
References DirtyPixel(), OptimizeOrder(), and ThrowNotYetImplemented().
The documentation for this class was generated from the following files:
dng_pixel_buffer.h
dng_pixel_buffer.cpp