DNG SDK 1.5: dng_opcode Class Reference
dng_opcode Class Reference abstract
Virtual base class for opcode.
#include <dng_opcodes.h>
Public Types
enum { kFlag_None = 0, kFlag_Optional = 1, kFlag_SkipIfPreview = 2 }
Opcode flags.
Public Member Functions
uint32 OpcodeID () const
The ID of this opcode.
uint32 MinVersion () const
The first DNG version that supports this opcode.
uint32 Flags () const
The flags for this opcode.
bool Optional () const
Is this opcode optional?
bool SkipIfPreview () const
Should the opcode be skipped when rendering preview images?
bool WasReadFromStream () const
Was this opcode read from a data stream?
uint32 Stage () const
void SetStage (uint32 stage)
virtual bool IsNOP () const
virtual bool IsValidForNegative (const dng_negative &) const
Is this opcode valid for the specified negative?
virtual void PutData (dng_stream &stream) const
bool AboutToApply (dng_host &host, dng_negative &negative, const dng_rect &imageBounds, uint32 imagePlanes)
virtual void Apply (dng_host &host, dng_negative &negative, AutoPtr< dng_image > &image)=0
Apply this opcode to the specified image with associated negative.
Protected Member Functions
dng_opcode (uint32 opcodeID, uint32 minVersion, uint32 flags)
dng_opcode (uint32 opcodeID, dng_stream &stream, const char *name)
virtual void DoAboutToApply (dng_host &, dng_negative &, const dng_rect &, uint32)
Detailed Description
Virtual base class for opcode.
Member Enumeration Documentation
anonymous enum
anonymous enum
Opcode flags.
Enumerator
kFlag_None
No flag.
kFlag_Optional
This opcode is optional.
kFlag_SkipIfPreview
May skip opcode for preview images.
Member Function Documentation
AboutToApply()
bool dng_opcode::AboutToApply (dng_host & host, dng_negative & negative, const dng_rect & imageBounds, uint32 imagePlanes)
Perform error checking prior to applying this opcode to the specified negative. Returns true if this opcode should be applied to the negative, false otherwise.
References dng_host::ForPreview(), IsNOP(), IsValidForNegative(), MinVersion(), Optional(), SkipIfPreview(), ThrowBadFormat(), and WasReadFromStream().
Referenced by dng_opcode_list::Apply().
IsNOP()
virtual bool dng_opcode::IsNOP () const inline virtual
Is the opcode a NOP (i.e., does nothing)? An opcode could be a NOP for some specific parameters.
Reimplemented in dng_opcode_FixVignetteRadial, dng_opcode_WarpFisheye, and dng_opcode_WarpRectilinear.
Referenced by AboutToApply().
PutData()
void dng_opcode::PutData (dng_stream & stream) const virtual
Write opcode to a stream.
Parameters
stream The stream to which to write the opcode data.
Reimplemented in dng_opcode_FixVignetteRadial, dng_opcode_WarpFisheye, dng_opcode_WarpRectilinear, dng_opcode_ScalePerColumn, dng_opcode_ScalePerRow, dng_opcode_DeltaPerColumn, dng_opcode_DeltaPerRow, dng_opcode_Unknown, dng_opcode_FixBadPixelsList, dng_opcode_MapPolynomial, dng_opcode_MapTable, dng_opcode_GainMap, dng_opcode_FixBadPixelsConstant, and dng_opcode_TrimBounds.
References dng_stream::Put_uint32().
SetStage()
void dng_opcode::SetStage (uint32 stage) inline
Set the image processing stage (1, 2, 3) for this opcode. Stage 1 is the original image data, including masked areas. Stage 2 is linearized image data and trimmed to the active area. Stage 3 is demosaiced and trimmed to the active area.
Stage()
uint32 dng_opcode::Stage () const inline
Which image processing stage (1, 2, 3) is associated with this opcode?
Referenced by dng_opcode_MapPolynomial::BufferPixelType(), dng_opcode_MapTable::Prepare(), dng_opcode_GainMap::ProcessArea(), dng_opcode_MapPolynomial::ProcessArea(), dng_opcode_DeltaPerRow::ProcessArea(), dng_opcode_DeltaPerColumn::ProcessArea(), dng_opcode_ScalePerRow::ProcessArea(), and dng_opcode_ScalePerColumn::ProcessArea().
The documentation for this class was generated from the following files:
dng_opcodes.h
dng_opcodes.cpp