DNG SDK 1.5: dng_1d_table Class Reference
dng_1d_table Class Reference
A 1D floating-point lookup table using linear interpolation.
#include <dng_1d_table.h>
Public Member Functions
dng_1d_table (uint32 count=kDefaultTableSize)
uint32 Count () const
Number of table entries.
void Initialize (dng_memory_allocator &allocator, const dng_1d_function &function, bool subSample=false)
real32 Interpolate (real32 x) const
const real32 * Table () const
Direct access function for table data.
void Expand16 (uint16 *table16) const
Expand the table to a 16-bit to 16-bit table.
Static Public Attributes
static const uint32 kMinTableSize = 512
Constant denoting minimum size of table.
Protected Attributes
AutoPtr< dng_memory_block > fBuffer
real32 * fTable
const uint32 fTableCount
Detailed Description
A 1D floating-point lookup table using linear interpolation.
Constructor & Destructor Documentation
dng_1d_table()
dng_1d_table::dng_1d_table (uint32 count = kDefaultTableSize) explicit
Table constructor. count must be a power of two and at least kMinTableSize.
References DNG_REQUIRE, and kMinTableSize.
Member Function Documentation
Initialize()
void dng_1d_table::Initialize (dng_memory_allocator & allocator, const dng_1d_function & function, bool subSample = false)
Set up table, initialize entries using functiion. This method can throw an exception, e.g. if there is not enough memory.
Parameters
allocator Memory allocator from which table memory is allocated.
function Table is initialized with values of finction.Evalluate(0.0) to function.Evaluate(1.0).
subSample If true, only sample the function a limited number of times and interpolate.
References dng_memory_allocator::Allocate(), dng_memory_block::Buffer_real32(), and AutoPtr< T >::Reset().
Referenced by dng_opcode_FixVignetteRadial::Prepare(), and dng_render_task::Start().
Interpolate()
real32 dng_1d_table::Interpolate (real32 x) const inline
Lookup and interpolate mapping for an input.
Parameters
x value from 0.0 to 1.0 used as input for mapping
Return values
Approximation of function.Evaluate(x)
References DNG_ASSERT.
Referenced by dng_opcode_FixVignetteRadial::Prepare().
The documentation for this class was generated from the following files:
dng_1d_table.h
dng_1d_table.cpp