DNG SDK 1.5: dng_filter_task Class Reference
dng_filter_task Class Reference abstract
Represents a task which filters an area of a source dng_image to an area of a destination dng_image.
#include <dng_filter_task.h>
Public Member Functions
dng_filter_task (const char *name, const dng_image &srcImage, dng_image &dstImage)
virtual dng_rect SrcArea (const dng_rect &dstArea)
virtual dng_point SrcTileSize (const dng_point &dstTileSize)
virtual void ProcessArea (uint32 threadIndex, dng_pixel_buffer &srcBuffer, dng_pixel_buffer &dstBuffer)=0
virtual void Start (uint32 threadCount, const dng_rect &dstArea, const dng_point &tileSize, dng_memory_allocator *allocator, dng_abort_sniffer *sniffer)
virtual void Process (uint32 threadIndex, const dng_rect &area, dng_abort_sniffer *sniffer)
Public Member Functions inherited from dng_area_task
dng_area_task (const char *name="unnamed dng_area_task")
const char * Name () const
virtual uint32 MaxThreads () const
virtual uint32 MinTaskArea () const
operation. (Partitions can be smaller due to small inputs and edge cases.)
virtual dng_point UnitCell () const
virtual dng_point MaxTileSize () const
virtual dng_rect RepeatingTile1 () const
virtual dng_rect RepeatingTile2 () const
virtual dng_rect RepeatingTile3 () const
virtual void Finish (uint32 threadCount)
dng_point FindTileSize (const dng_rect &area) const
void ProcessOnThread (uint32 threadIndex, const dng_rect &area, const dng_point &tileSize, dng_abort_sniffer *sniffer, dng_area_task_progress *progress)
virtual dng_base_tile_iterator * MakeTileIterator (uint32 threadIndex, const dng_rect &tile, const dng_rect &area) const
virtual dng_base_tile_iterator * MakeTileIterator (uint32 threadIndex, const dng_point &tileSize, const dng_rect &area) const
Protected Attributes
const dng_image & fSrcImage
dng_image & fDstImage
uint32 fSrcPlane
uint32 fSrcPlanes
uint32 fSrcPixelType
uint32 fDstPlane
uint32 fDstPlanes
uint32 fDstPixelType
dng_point fSrcRepeat
dng_point fSrcTileSize
AutoPtr< dng_memory_block > fSrcBuffer [kMaxMPThreads]
AutoPtr< dng_memory_block > fDstBuffer [kMaxMPThreads]
Protected Attributes inherited from dng_area_task
uint32 fMaxThreads
uint32 fMinTaskArea
dng_point fUnitCell
dng_point fMaxTileSize
dng_string fName
Additional Inherited Members
Static Public Member Functions inherited from dng_area_task
static void Perform (dng_area_task &task, const dng_rect &area, dng_memory_allocator *allocator, dng_abort_sniffer *sniffer, dng_area_task_progress *progress)
Detailed Description
Represents a task which filters an area of a source dng_image to an area of a destination dng_image.
Constructor & Destructor Documentation
dng_filter_task()
dng_filter_task::dng_filter_task (const char * name, const dng_image & srcImage, dng_image & dstImage)
Construct a filter task given a source and destination images.
Parameters
srcImage Image from which source pixels are read.
dstImage Image to which result pixels are written.
Member Function Documentation
Process()
void dng_filter_task::Process (uint32 threadIndex, const dng_rect & area, dng_abort_sniffer * sniffer) virtual
Process one tile or partitioned area. Should not be overridden. Instead, override ProcessArea, which is where to implement filter processing for a specific type of dng_filter_task. There is no allocator parameter as all allocation should be done in Start.
Parameters
threadIndex 0 to threadCount - 1 index indicating which thread this is. (Can be used to get a thread-specific buffer allocated in the Start method.)
area Size of tiles to be used for sizing buffers, etc. (Edges of processing can be smaller.)
sniffer dng_abort_sniffer to use to check for user cancellation and progress updates.
Implements dng_area_task.
References dng_image::edge_repeat, dng_image::Get(), ProcessArea(), dng_image::Put(), SrcArea(), and ThrowMemoryFull().
ProcessArea()
virtual void dng_filter_task::ProcessArea (uint32 threadIndex, dng_pixel_buffer & srcBuffer, dng_pixel_buffer & dstBuffer) pure virtual
Implements filtering operation from one buffer to another. Source and destination pixels are set up in member fields of this class. Ideally, no allocation should be done in this routine.
Parameters
threadIndex The thread on which this routine is being called, between 0 and threadCount - 1 for the threadCount passed to Start method.
srcBuffer Input area and source pixels.
dstBuffer Output area and destination pixels.
Implemented in dng_fast_interpolator, dng_filter_warp, dng_render_task, dng_resample_task, and dng_filter_opcode_task.
Referenced by Process().
SrcArea()
virtual dng_rect dng_filter_task::SrcArea (const dng_rect & dstArea) inline virtual
Compute the source area needed for a given destination area. Default implementation assumes destination area is equal to source area for all cases.
Parameters
dstArea Area to for which pixels will be computed.
Return values
The source area needed as input to calculate the requested destination area.
Reimplemented in dng_fast_interpolator, dng_filter_warp, dng_render_task, dng_resample_task, and dng_filter_opcode_task.
Referenced by Process(), and SrcTileSize().
SrcTileSize()
virtual dng_point dng_filter_task::SrcTileSize (const dng_point & dstTileSize) inline virtual
Given a destination tile size, calculate input tile size. Simlar to SrcArea, and should seldom be overridden.
Parameters
dstTileSize The destination tile size that is targeted for output.
Return values
The source tile size needed to compute a tile of the destination size.
Reimplemented in dng_filter_warp, dng_resample_task, and dng_filter_opcode_task.
References SrcArea().
Referenced by Start().
Start()
void dng_filter_task::Start (uint32 threadCount, const dng_rect & dstArea, const dng_point & tileSize, dng_memory_allocator * allocator, dng_abort_sniffer * sniffer) virtual
Called prior to processing on specific threads. Can be used to allocate per-thread memory buffers, etc.
Parameters
threadCount Total number of threads that will be used for processing. Less than or equal to MaxThreads of dng_area_task.
tileSize Size of source tiles which will be processed. (Not all tiles will be this size due to edge conditions.)
allocator dng_memory_allocator to use for allocating temporary buffers, etc.
sniffer Sniffer to test for user cancellation and to set up progress.
Reimplemented from dng_area_task.
Reimplemented in dng_render_task, dng_resample_task, and dng_filter_opcode_task.
References dng_memory_allocator::Allocate(), and SrcTileSize().
Referenced by dng_filter_opcode_task::Start(), dng_resample_task::Start(), and dng_render_task::Start().
The documentation for this class was generated from the following files:
dng_filter_task.h
dng_filter_task.cpp