DNG SDK 1.5: dng_negative Class Reference
dng_negative Class Reference
Main class for holding DNG image data and associated metadata.
#include <dng_negative.h>
Public Types
enum RawImageStageEnum {
rawImageStagePreOpcode1, rawImageStagePostOpcode1, rawImageStagePostOpcode2, rawImageStagePreOpcode3,
rawImageStagePostOpcode3, rawImageStageNone
}
Public Member Functions
dng_memory_allocator & Allocator () const
Provide access to the memory allocator used for this object.
void SetModelName (const char *name)
Getter for ModelName.
const dng_string & ModelName () const
Setter for ModelName.
void SetLocalName (const char *name)
Setter for LocalName.
const dng_string & LocalName () const
Getter for LocalName.
dng_metadata & Metadata ()
Getter for metadata.
dng_metadata * CloneInternalMetadata () const
void SetBaseOrientation (const dng_orientation &orientation)
Setter for BaseOrientation.
bool HasBaseOrientation () METACONST
Has BaseOrientation been set?
const dng_orientation & BaseOrientation () METACONST
Getter for BaseOrientation.
virtual dng_orientation ComputeOrientation (const dng_metadata &metadata) const
Hook to allow SDK host code to add additional rotations.
dng_orientation Orientation ()
For non-const negatives, we simply default to using the metadata attached to the negative.
void ApplyOrientation (const dng_orientation &orientation)
void SetDefaultCropSize (const dng_urational &sizeH, const dng_urational &sizeV)
Setter for DefaultCropSize.
void SetDefaultCropSize (uint32 sizeH, uint32 sizeV)
Setter for DefaultCropSize.
const dng_urational & DefaultCropSizeH () const
Getter for DefaultCropSize horizontal.
const dng_urational & DefaultCropSizeV () const
Getter for DefaultCropSize vertical.
void SetDefaultCropOrigin (const dng_urational &originH, const dng_urational &originV)
Setter for DefaultCropOrigin.
void SetDefaultCropOrigin (uint32 originH, uint32 originV)
Setter for DefaultCropOrigin.
void SetDefaultCropCentered (const dng_point &rawSize)
Set default crop around center of image.
const dng_urational & DefaultCropOriginH () const
Get default crop origin horizontal value.
const dng_urational & DefaultCropOriginV () const
Get default crop origin vertical value.
bool HasDefaultUserCrop () const
Is there a default user crop?
const dng_urational & DefaultUserCropT () const
Getter for top coordinate of default user crop.
const dng_urational & DefaultUserCropL () const
Getter for left coordinate of default user crop.
const dng_urational & DefaultUserCropB () const
Getter for bottom coordinate of default user crop.
const dng_urational & DefaultUserCropR () const
Getter for right coordinate of default user crop.
void ResetDefaultUserCrop ()
Reset default user crop to default crop area.
void SetDefaultUserCrop (const dng_urational &t, const dng_urational &l, const dng_urational &b, const dng_urational &r)
Setter for all 4 coordinates of default user crop.
void SetDefaultUserCropT (const dng_urational &value)
Setter for top coordinate of default user crop.
void SetDefaultUserCropL (const dng_urational &value)
Setter for left coordinate of default user crop.
void SetDefaultUserCropB (const dng_urational &value)
Setter for bottom coordinate of default user crop.
void SetDefaultUserCropR (const dng_urational &value)
Setter for right coordinate of default user crop.
void SetDefaultScale (const dng_urational &scaleH, const dng_urational &scaleV)
Setter for DefaultScale.
const dng_urational & DefaultScaleH () const
Get default scale horizontal value.
const dng_urational & DefaultScaleV () const
Get default scale vertical value.
void SetBestQualityScale (const dng_urational &scale)
Setter for BestQualityScale.
const dng_urational & BestQualityScale () const
Getter for BestQualityScale.
bool HasBestQualityScale () const
Is the best quality scale different than the default scale?
real64 RawToFullScaleH () const
API for raw to full image scaling factors horizontal.
real64 RawToFullScaleV () const
API for raw to full image scaling factors vertical.
void SetRawToFullScale (real64 scaleH, real64 scaleV)
Setter for raw to full scales.
real64 DefaultScale () const
real64 SquareWidth () const
Default cropped image size (at scale == 1.0) width.
real64 SquareHeight () const
Default cropped image size (at scale == 1.0) height.
real64 AspectRatio () const
Default cropped image aspect ratio.
real64 PixelAspectRatio () const
Pixel aspect ratio of stage 3 image.
uint32 FinalWidth (real64 scale) const
Default cropped image size at given scale factor width.
uint32 FinalHeight (real64 scale) const
Default cropped image size at given scale factor height.
uint32 DefaultFinalWidth () const
Default cropped image size at default scale factor width.
uint32 DefaultFinalHeight () const
Default cropped image size at default scale factor height.
uint32 BestQualityFinalWidth () const
uint32 BestQualityFinalHeight () const
const dng_point & OriginalDefaultFinalSize () const
void SetOriginalDefaultFinalSize (const dng_point &size)
Setter for OriginalDefaultFinalSize.
const dng_point & OriginalBestQualityFinalSize () const
void SetOriginalBestQualityFinalSize (const dng_point &size)
Setter for OriginalBestQualityFinalSize.
const dng_urational & OriginalDefaultCropSizeH () const
const dng_urational & OriginalDefaultCropSizeV () const
void SetOriginalDefaultCropSize (const dng_urational &sizeH, const dng_urational &sizeV)
Setter for OriginalDefaultCropSize.
void SetDefaultOriginalSizes ()
void SetOriginalSizes (const dng_point &size)
Set all the original size fields to a specific size.
dng_rect DefaultCropArea () const
The default crop area in the stage 3 image coordinates.
void SetBaselineNoise (real64 noise)
Setter for BaselineNoise.
const dng_urational & BaselineNoiseR () const
Getter for BaselineNoise as dng_urational.
real64 BaselineNoise () const
Getter for BaselineNoise as real64.
void SetNoiseReductionApplied (const dng_urational &value)
Setter for NoiseReductionApplied.
const dng_urational & NoiseReductionApplied () const
Getter for NoiseReductionApplied.
void SetRawNoiseReductionApplied ()
const dng_urational & RawNoiseReductionApplied () const
void SetNoiseProfile (const dng_noise_profile &noiseProfile)
Setter for noise profile.
bool HasNoiseProfile () const
Does this negative have a valid noise profile?
const dng_noise_profile & NoiseProfile () const
Getter for noise profile.
bool HasRawNoiseProfile () const
void SetRawNoiseProfile ()
const dng_noise_profile & RawNoiseProfile () const
void SetBaselineExposure (real64 exposure)
Setter for BaselineExposure.
const dng_srational & BaselineExposureR () const
Getter for BaselineExposure as dng_urational.
real64 BaselineExposure () const
Getter for BaselineExposure as real64.
real64 TotalBaselineExposure (const dng_camera_profile_id &profileID) const
void SetBaselineSharpness (real64 sharpness)
Setter for BaselineSharpness.
const dng_urational & BaselineSharpnessR () const
Getter for BaselineSharpness as dng_urational.
real64 BaselineSharpness () const
Getter for BaselineSharpness as real64.
void SetRawBaselineSharpness ()
const dng_urational & RawBaselineSharpness () const
void SetChromaBlurRadius (const dng_urational &radius)
Setter for ChromaBlurRadius.
const dng_urational & ChromaBlurRadius () const
Getter for ChromaBlurRadius as dng_urational.
void SetAntiAliasStrength (const dng_urational &strength)
Setter for AntiAliasStrength.
const dng_urational & AntiAliasStrength () const
Getter for AntiAliasStrength as dng_urational.
void SetLinearResponseLimit (real64 limit)
Setter for LinearResponseLimit.
const dng_urational & LinearResponseLimitR () const
Getter for LinearResponseLimit as dng_urational.
real64 LinearResponseLimit () const
Getter for LinearResponseLimit as real64.
void SetShadowScale (const dng_urational &scale)
Setter for ShadowScale.
const dng_urational & ShadowScaleR () const
Getter for ShadowScale as dng_urational.
real64 ShadowScale () const
Getter for ShadowScale as real64.
void SetColorimetricReference (uint32 ref)
uint32 ColorimetricReference () const
void SetFloatingPoint (bool isFloatingPoint)
bool IsFloatingPoint () const
bool IsHighDynamicRange () const
bool IsNormalDynamicRange () const
void SetColorChannels (uint32 channels)
Setter for ColorChannels.
uint32 ColorChannels () const
Getter for ColorChannels.
void SetMonochrome ()
Setter for Monochrome.
bool IsMonochrome () const
Getter for Monochrome.
void SetAnalogBalance (const dng_vector &b)
Setter for AnalogBalance.
dng_urational AnalogBalanceR (uint32 channel) const
Getter for AnalogBalance as dng_urational.
real64 AnalogBalance (uint32 channel) const
Getter for AnalogBalance as real64.
void SetCameraNeutral (const dng_vector &n)
Setter for CameraNeutral.
void ClearCameraNeutral ()
Clear CameraNeutral.
bool HasCameraNeutral () const
Determine if CameraNeutral has been set but not cleared.
const dng_vector & CameraNeutral () const
Getter for CameraNeutral.
dng_urational CameraNeutralR (uint32 channel) const
void SetCameraWhiteXY (const dng_xy_coord &coord)
Setter for CameraWhiteXY.
bool HasCameraWhiteXY () const
const dng_xy_coord & CameraWhiteXY () const
void GetCameraWhiteXY (dng_urational &x, dng_urational &y) const
void SetCameraCalibration1 (const dng_matrix &m)
void SetCameraCalibration2 (const dng_matrix &m)
const dng_matrix & CameraCalibration1 () const
Getter for first of up to two color matrices used for individual camera calibrations.
const dng_matrix & CameraCalibration2 () const
Getter for second of up to two color matrices used for individual camera calibrations.
void SetCameraCalibrationSignature (const char *signature)
const dng_string & CameraCalibrationSignature () const
void AddProfile (AutoPtr< dng_camera_profile > &profile)
void ClearProfiles ()
void ClearProfiles (bool clearBuiltinMatrixProfiles, bool clearReadFromDisk)
uint32 ProfileCount () const
const dng_camera_profile & ProfileByIndex (uint32 index) const
virtual const dng_camera_profile * ProfileByID (const dng_camera_profile_id &id, bool useDefaultIfNoMatch=true) const
bool HasProfileID (const dng_camera_profile_id &id) const
virtual const dng_camera_profile * ComputeCameraProfileToEmbed (const dng_metadata &metadata) const
const dng_camera_profile * CameraProfileToEmbed ()
void SetAsShotProfileName (const char *name)
const dng_string & AsShotProfileName () const
virtual dng_color_spec * MakeColorSpec (const dng_camera_profile_id &id) const
void SetRawImageDigest (const dng_fingerprint &digest)
void SetNewRawImageDigest (const dng_fingerprint &digest)
void ClearRawImageDigest () const
const dng_fingerprint & RawImageDigest () const
const dng_fingerprint & NewRawImageDigest () const
void FindRawImageDigest (dng_host &host) const
void FindNewRawImageDigest (dng_host &host) const
void ValidateRawImageDigest (dng_host &host)
void SetRawDataUniqueID (const dng_fingerprint &id)
dng_fingerprint RawDataUniqueID () const
void FindRawDataUniqueID (dng_host &host) const
virtual void RecomputeRawDataUniqueID (dng_host &host)
void SetOriginalRawFileName (const char *name)
bool HasOriginalRawFileName () const
const dng_string & OriginalRawFileName () const
void SetHasOriginalRawFileData (bool hasData)
bool CanEmbedOriginalRaw () const
void SetOriginalRawFileData (AutoPtr< dng_memory_block > &data)
const void * OriginalRawFileData () const
uint32 OriginalRawFileDataLength () const
void SetOriginalRawFileDigest (const dng_fingerprint &digest)
const dng_fingerprint & OriginalRawFileDigest () const
void FindOriginalRawFileDigest () const
void ValidateOriginalRawFileDigest ()
void SetPrivateData (AutoPtr< dng_memory_block > &block)
void ClearPrivateData ()
const uint8 * PrivateData () const
uint32 PrivateLength () const
void SetMakerNoteSafety (bool safe)
bool IsMakerNoteSafe () METACONST
void SetMakerNote (AutoPtr< dng_memory_block > &block)
void ClearMakerNote ()
const void * MakerNoteData () METACONST
uint32 MakerNoteLength () METACONST
dng_exif * GetExif ()
void ResetExif (dng_exif *newExif)
dng_exif * GetOriginalExif ()
void SetIPTC (AutoPtr< dng_memory_block > &block, uint64 offset)
void SetIPTC (AutoPtr< dng_memory_block > &block)
void ClearIPTC ()
const void * IPTCData () METACONST
uint32 IPTCLength () METACONST
uint64 IPTCOffset () METACONST
dng_fingerprint IPTCDigest (bool includePadding=true) METACONST
void RebuildIPTC (bool padForTIFF)
bool SetXMP (dng_host &host, const void *buffer, uint32 count, bool xmpInSidecar=false, bool xmpIsNewer=false)
dng_xmp * GetXMP ()
bool XMPinSidecar () METACONST
void ResetXMP (dng_xmp *newXMP)
void ResetXMPSidecarNewer (dng_xmp *newXMP, bool inSidecar, bool isNewer)
bool HaveValidEmbeddedXMP () METACONST
void SetSourceMIME (const char *s)
const dng_linearization_info * GetLinearizationInfo () const
void ClearLinearizationInfo ()
void SetLinearization (AutoPtr< dng_memory_block > &curve)
void SetActiveArea (const dng_rect &area)
void SetMaskedAreas (uint32 count, const dng_rect *area)
void SetMaskedArea (const dng_rect &area)
void SetBlackLevel (real64 black, int32 plane=-1)
void SetQuadBlacks (real64 black0, real64 black1, real64 black2, real64 black3, int32 plane=-1)
void Set6x6Blacks (real64 blacks6x6 [36], int32 plane=-1)
void SetRowBlacks (const real64 *blacks, uint32 count)
void SetColumnBlacks (const real64 *blacks, uint32 count)
uint32 WhiteLevel (uint32 plane=0) const
void SetWhiteLevel (uint32 white, int32 plane=-1)
const dng_mosaic_info * GetMosaicInfo () const
void ClearMosaicInfo ()
void SetColorKeys (ColorKeyCode color0, ColorKeyCode color1, ColorKeyCode color2, ColorKeyCode color3=colorKeyMaxEnum)
void SetRGB ()
void SetCMY ()
void SetGMCY ()
void SetBayerMosaic (uint32 phase)
void SetFujiMosaic (uint32 phase)
void SetFujiMosaic6x6 (uint32 phase)
void SetQuadMosaic (uint32 pattern)
void SetGreenSplit (uint32 split)
const dng_opcode_list & OpcodeList1 () const
dng_opcode_list & OpcodeList1 ()
const dng_opcode_list & OpcodeList2 () const
dng_opcode_list & OpcodeList2 ()
const dng_opcode_list & OpcodeList3 () const
dng_opcode_list & OpcodeList3 ()
virtual void Parse (dng_host &host, dng_stream &stream, dng_info &info)
virtual void PostParse (dng_host &host, dng_stream &stream, dng_info &info)
void SynchronizeMetadata ()
void UpdateDateTime (const dng_date_time_info &dt)
void UpdateDateTimeToNow ()
virtual bool SetFourColorBayer ()
const dng_image * Stage1Image () const
const dng_image * Stage2Image () const
const dng_image * Stage3Image () const
RawImageStageEnum RawImageStage () const
const dng_image & RawImage () const
uint16 RawImageBlackLevel () const
uint32 RawFloatBitDepth () const
void SetRawFloatBitDepth (uint32 bitDepth)
const dng_jpeg_image * RawJPEGImage () const
void SetRawJPEGImage (AutoPtr< dng_jpeg_image > &jpegImage)
void ClearRawJPEGImage ()
void SetRawJPEGImageDigest (const dng_fingerprint &digest)
void ClearRawJPEGImageDigest () const
const dng_fingerprint & RawJPEGImageDigest () const
void FindRawJPEGImageDigest (dng_host &host) const
virtual void ReadOpcodeLists (dng_host &host, dng_stream &stream, dng_info &info)
virtual void ReadStage1Image (dng_host &host, dng_stream &stream, dng_info &info)
virtual void ReadEnhancedImage (dng_host &host, dng_stream &stream, dng_info &info)
void SetStage1Image (AutoPtr< dng_image > &image)
void SetStage2Image (AutoPtr< dng_image > &image)
void SetStage3Image (AutoPtr< dng_image > &image)
void BuildStage2Image (dng_host &host)
void BuildStage3Image (dng_host &host, int32 srcPlane=-1)
void SetStage3Gain (real64 gain)
real64 Stage3Gain () const
void SetStage3BlackLevel (uint16 level)
uint16 Stage3BlackLevel () const
real64 Stage3BlackLevelNormalized () const
virtual bool SupportsPreservedBlackLevels (dng_host &host)
dng_image * EncodeRawProxy (dng_host &host, const dng_image &srcImage, dng_opcode_list &opcodeList, real64 *blackLevel) const
void ConvertToProxy (dng_host &host, dng_image_writer &writer, uint32 proxySize=0, uint64 proxyCount=0)
bool IsProxy () const
void SetIsPreview (bool preview)
bool IsPreview () const
void SetIsDamaged (bool damaged)
bool IsDamaged () const
void SetTransparencyMask (AutoPtr< dng_image > &image, uint32 bitDepth=0)
const dng_image * TransparencyMask () const
const dng_image * RawTransparencyMask () const
uint32 RawTransparencyMaskBitDepth () const
void ReadTransparencyMask (dng_host &host, dng_stream &stream, dng_info &info)
virtual void ResizeTransparencyToMatchStage3 (dng_host &host, bool convertTo8Bit=false)
virtual bool NeedFlattenTransparency (dng_host &host)
virtual void FlattenTransparency (dng_host &host)
const dng_image * UnflattenedStage3Image () const
bool HasDepthMap () const
void SetHasDepthMap (bool hasDepthMap)
const dng_image * DepthMap () const
void SetDepthMap (AutoPtr< dng_image > &depthMap)
bool HasDepthMapImage () const
const dng_image * RawDepthMap () const
void ReadDepthMap (dng_host &host, dng_stream &stream, dng_info &info)
virtual void ResizeDepthToMatchStage3 (dng_host &host)
uint32 DepthFormat () const
void SetDepthFormat (uint32 format)
const dng_urational & DepthNear () const
void SetDepthNear (const dng_urational &dist)
const dng_urational & DepthFar () const
void SetDepthFar (const dng_urational &dist)
uint32 DepthUnits () const
void SetDepthUnits (uint32 units)
uint32 DepthMeasureType () const
void SetDepthMeasureType (uint32 measure)
const dng_string & EnhanceParams () const
void SetEnhanceParams (const dng_string &s)
void SetEnhanceParams (const char *s)
Static Public Member Functions
static dng_negative * Make (dng_host &host)
static dng_fingerprint FindImageDigest (dng_host &host, const dng_image &image)
Protected Member Functions
const dng_metadata & InternalMetadata () const
dng_negative (dng_host &host)
virtual void Initialize ()
virtual dng_linearization_info * MakeLinearizationInfo ()
void NeedLinearizationInfo ()
virtual dng_mosaic_info * MakeMosaicInfo ()
void NeedMosaicInfo ()
virtual void DoBuildStage2 (dng_host &host)
virtual void DoPostOpcodeList2 (dng_host &host)
virtual bool NeedDefloatStage2 (dng_host &host)
virtual void DefloatStage2 (dng_host &host)
virtual void DoInterpolateStage3 (dng_host &host, int32 srcPlane, dng_matrix *scaleTransforms)
virtual void DoMergeStage3 (dng_host &host, dng_matrix *scaleTransforms)
virtual void DoBuildStage3 (dng_host &host, int32 srcPlane, dng_matrix *scaleTransforms)
virtual void AdjustProfileForStage3 ()
Protected Attributes
dng_memory_allocator & fAllocator
dng_string fModelName
dng_string fLocalName
dng_urational fDefaultCropSizeH
dng_urational fDefaultCropSizeV
dng_urational fDefaultCropOriginH
dng_urational fDefaultCropOriginV
dng_urational fDefaultUserCropT
dng_urational fDefaultUserCropL
dng_urational fDefaultUserCropB
dng_urational fDefaultUserCropR
dng_urational fDefaultScaleH
dng_urational fDefaultScaleV
dng_urational fBestQualityScale
dng_point fOriginalDefaultFinalSize
dng_point fOriginalBestQualityFinalSize
dng_urational fOriginalDefaultCropSizeH
dng_urational fOriginalDefaultCropSizeV
real64 fRawToFullScaleH
real64 fRawToFullScaleV
dng_urational fBaselineNoise
dng_urational fNoiseReductionApplied
dng_urational fRawNoiseReductionApplied
dng_noise_profile fNoiseProfile
dng_noise_profile fRawNoiseProfile
dng_srational fBaselineExposure
dng_urational fBaselineSharpness
dng_urational fRawBaselineSharpness
dng_urational fChromaBlurRadius
dng_urational fAntiAliasStrength
dng_urational fLinearResponseLimit
dng_urational fShadowScale
uint32 fColorimetricReference
bool fFloatingPoint
uint32 fColorChannels
dng_vector fAnalogBalance
dng_vector fCameraNeutral
dng_xy_coord fCameraWhiteXY
dng_matrix fCameraCalibration1
dng_matrix fCameraCalibration2
dng_string fCameraCalibrationSignature
dng_std_vector< dng_camera_profile * > fCameraProfile
dng_string fAsShotProfileName
dng_fingerprint fRawImageDigest
dng_fingerprint fNewRawImageDigest
dng_fingerprint fRawDataUniqueID
dng_std_mutex fRawDataUniqueIDMutex
dng_string fOriginalRawFileName
bool fHasOriginalRawFileData
AutoPtr< dng_memory_block > fOriginalRawFileData
dng_fingerprint fOriginalRawFileDigest
AutoPtr< dng_memory_block > fDNGPrivateData
dng_metadata fMetadata
AutoPtr< dng_linearization_info > fLinearizationInfo
AutoPtr< dng_mosaic_info > fMosaicInfo
dng_opcode_list fOpcodeList1
dng_opcode_list fOpcodeList2
dng_opcode_list fOpcodeList3
AutoPtr< dng_image > fStage1Image
AutoPtr< dng_image > fStage2Image
AutoPtr< dng_image > fStage3Image
real64 fStage3Gain
uint16 fStage3BlackLevel
bool fIsPreview
bool fIsDamaged
RawImageStageEnum fRawImageStage
AutoPtr< dng_image > fRawImage
uint16 fRawImageBlackLevel
uint32 fRawFloatBitDepth
AutoPtr< dng_jpeg_image > fRawJPEGImage
dng_fingerprint fRawJPEGImageDigest
AutoPtr< dng_image > fTransparencyMask
AutoPtr< dng_image > fRawTransparencyMask
uint32 fRawTransparencyMaskBitDepth
AutoPtr< dng_image > fUnflattenedStage3Image
bool fHasDepthMap
AutoPtr< dng_image > fDepthMap
AutoPtr< dng_image > fRawDepthMap
uint32 fDepthFormat
dng_urational fDepthNear
dng_urational fDepthFar
uint32 fDepthUnits
uint32 fDepthMeasureType
dng_string fEnhanceParams
Detailed Description
Main class for holding DNG image data and associated metadata.
Member Function Documentation
ApplyOrientation()
void dng_negative::ApplyOrientation (const dng_orientation & orientation) inline
Logically rotates the image by changing the orientation values. This will also update the XMP data.
References dng_metadata::ApplyOrientation(), and Metadata().
BestQualityFinalHeight()
uint32 dng_negative::BestQualityFinalHeight () const inline
Get best quality height. For a naive conversion, one could use either the default size, or the best quality size.
References BestQualityScale(), DefaultScale(), and FinalHeight().
Referenced by SetDefaultOriginalSizes().
BestQualityFinalWidth()
uint32 dng_negative::BestQualityFinalWidth () const inline
Get best quality width. For a naive conversion, one could use either the default size, or the best quality size.
References BestQualityScale(), DefaultScale(), and FinalWidth().
Referenced by SetDefaultOriginalSizes().
CloneInternalMetadata()
dng_metadata * dng_negative::CloneInternalMetadata () const
Make a copy of the internal metadata generally as a basis for further changes.
References Allocator(), dng_metadata::Clone(), and InternalMetadata().
DefaultScale()
real64 dng_negative::DefaultScale () const inline
Get default scale factor. When specifing a single scale factor, we use the horizontal scale factor, and let the vertical scale factor be calculated based on the pixel aspect ratio.
References DefaultScaleH().
Referenced by BestQualityFinalHeight(), BestQualityFinalWidth(), DefaultFinalHeight(), and DefaultFinalWidth().
InternalMetadata()
const dng_metadata& dng_negative::InternalMetadata () const inline protected
An accessor for the internal metadata that works even when we have general access turned off. This is needed to provide access to EXIF ISO information.
Referenced by CloneInternalMetadata().
OriginalBestQualityFinalSize()
const dng_point& dng_negative::OriginalBestQualityFinalSize () const inline
Best quality size of original (non-proxy) image. For non-proxy images, this is equal to BestQualityFinalWidth/BestQualityFinalHeight. For proxy images, this is equal to the BestQualityFinalWidth/BestQualityFinalHeight of the image this proxy was derived from.
Referenced by SetDefaultOriginalSizes().
OriginalDefaultCropSizeH()
const dng_urational& dng_negative::OriginalDefaultCropSizeH () const inline
DefaultCropSize for original (non-proxy) image. For non-proxy images, this is equal to the DefaultCropSize. for proxy images, this is equal size of the DefaultCropSize of the image this proxy was derived from.
Referenced by SetDefaultOriginalSizes().
OriginalDefaultFinalSize()
const dng_point& dng_negative::OriginalDefaultFinalSize () const inline
Default size of original (non-proxy) image. For non-proxy images, this is equal to DefaultFinalWidth/DefaultFinalHight. For proxy images, this is equal to the DefaultFinalWidth/DefaultFinalHeight of the image this proxy was derived from.
Referenced by SetDefaultOriginalSizes().
SetCameraCalibration1()
void dng_negative::SetCameraCalibration1 (const dng_matrix & m)
Setter for first of up to two color matrices used for individual camera calibrations.
The sequence of matrix transforms is: Camera data --> camera calibration --> "inverse" of color matrix
This will be a 4x4 matrix for a four-color camera. The defaults are almost always the identity matrix, and for the cases where they aren't, they are diagonal matrices.
SetCameraCalibration2()
void dng_negative::SetCameraCalibration2 (const dng_matrix & m)
Setter for second of up to two color matrices used for individual camera calibrations.
The sequence of matrix transforms is: Camera data --> camera calibration --> "inverse" of color matrix
This will be a 4x4 matrix for a four-color camera. The defaults are almost always the identity matrix, and for the cases where they aren't, they are diagonal matrices.
SetDefaultOriginalSizes()
void dng_negative::SetDefaultOriginalSizes ()
If the original size fields are undefined, set them to the current sizes.
References BestQualityFinalHeight(), BestQualityFinalWidth(), DefaultCropSizeH(), DefaultCropSizeV(), DefaultFinalHeight(), DefaultFinalWidth(), OriginalBestQualityFinalSize(), OriginalDefaultCropSizeH(), OriginalDefaultFinalSize(), SetOriginalBestQualityFinalSize(), SetOriginalDefaultCropSize(), and SetOriginalDefaultFinalSize().
TotalBaselineExposure()
real64 dng_negative::TotalBaselineExposure (const dng_camera_profile_id & profileID) const
Compute total baseline exposure (sum of negative's BaselineExposure and profile's BaselineExposureOffset).
References BaselineExposure(), and dng_camera_profile::BaselineExposureOffset().
The documentation for this class was generated from the following files:
dng_negative.h
dng_negative.cpp