DNG SDK 1.5: dng_opcode_Unknown Class Reference
dng_opcode_Unknown Class Reference
Class to represent unknown opcodes (e.g, opcodes defined in future DNG versions).
#include <dng_opcodes.h>
Public Member Functions
dng_opcode_Unknown (dng_host &host, uint32 opcodeID, dng_stream &stream)
virtual void PutData (dng_stream &stream) const
virtual void Apply (dng_host &host, dng_negative &negative, AutoPtr< dng_image > &image)
Apply this opcode to the specified image with associated negative.
Public Member Functions inherited from dng_opcode
uint32 OpcodeID () const
The ID of this opcode.
uint32 MinVersion () const
The first DNG version that supports this opcode.
uint32 Flags () const
The flags for this opcode.
bool Optional () const
Is this opcode optional?
bool SkipIfPreview () const
Should the opcode be skipped when rendering preview images?
bool WasReadFromStream () const
Was this opcode read from a data stream?
uint32 Stage () const
void SetStage (uint32 stage)
virtual bool IsNOP () const
virtual bool IsValidForNegative (const dng_negative &) const
Is this opcode valid for the specified negative?
bool AboutToApply (dng_host &host, dng_negative &negative, const dng_rect &imageBounds, uint32 imagePlanes)
Additional Inherited Members
Public Types inherited from dng_opcode
enum { kFlag_None = 0, kFlag_Optional = 1, kFlag_SkipIfPreview = 2 }
Opcode flags.
Protected Member Functions inherited from dng_opcode
dng_opcode (uint32 opcodeID, uint32 minVersion, uint32 flags)
dng_opcode (uint32 opcodeID, dng_stream &stream, const char *name)
virtual void DoAboutToApply (dng_host &, dng_negative &, const dng_rect &, uint32)
Detailed Description
Class to represent unknown opcodes (e.g, opcodes defined in future DNG versions).
Member Function Documentation
PutData()
void dng_opcode_Unknown::PutData (dng_stream & stream) const virtual
Write opcode to a stream.
Parameters
stream The stream to which to write the opcode data.
Reimplemented from dng_opcode.
References dng_memory_block::Buffer(), AutoPtr< T >::Get(), dng_memory_block::LogicalSize(), dng_stream::Put(), and dng_stream::Put_uint32().
The documentation for this class was generated from the following files:
dng_opcodes.h
dng_opcodes.cpp