DNG SDK 1.5: dng_opcode_WarpRectilinear Class Reference
dng_opcode_WarpRectilinear Class Reference
Warp opcode for pinhole perspective (rectilinear) camera model.
#include <dng_lens_correction.h>
Public Member Functions
dng_opcode_WarpRectilinear (const dng_warp_params_rectilinear &params, uint32 flags)
dng_opcode_WarpRectilinear (dng_stream &stream)
virtual bool IsNOP () const
virtual bool IsValidForNegative (const dng_negative &negative) const
Is this opcode valid for the specified negative?
virtual void PutData (dng_stream &stream) const
virtual void Apply (dng_host &host, dng_negative &negative, AutoPtr< dng_image > &image)
Apply this opcode to the specified image with associated negative.
bool HasDistort () const
bool HasLateralCA () const
const dng_warp_params_rectilinear & Params () const
Public Member Functions inherited from dng_opcode
uint32 OpcodeID () const
The ID of this opcode.
uint32 MinVersion () const
The first DNG version that supports this opcode.
uint32 Flags () const
The flags for this opcode.
bool Optional () const
Is this opcode optional?
bool SkipIfPreview () const
Should the opcode be skipped when rendering preview images?
bool WasReadFromStream () const
Was this opcode read from a data stream?
uint32 Stage () const
void SetStage (uint32 stage)
bool AboutToApply (dng_host &host, dng_negative &negative, const dng_rect &imageBounds, uint32 imagePlanes)
Static Protected Member Functions
static uint32 ParamBytes (uint32 planes)
Protected Attributes
dng_warp_params_rectilinear fWarpParams
Additional Inherited Members
Public Types inherited from dng_opcode
enum { kFlag_None = 0, kFlag_Optional = 1, kFlag_SkipIfPreview = 2 }
Opcode flags.
Protected Member Functions inherited from dng_opcode
dng_opcode (uint32 opcodeID, uint32 minVersion, uint32 flags)
dng_opcode (uint32 opcodeID, dng_stream &stream, const char *name)
virtual void DoAboutToApply (dng_host &, dng_negative &, const dng_rect &, uint32)
Detailed Description
Warp opcode for pinhole perspective (rectilinear) camera model.
Member Function Documentation
IsNOP()
bool dng_opcode_WarpRectilinear::IsNOP () const virtual
Is the opcode a NOP (i.e., does nothing)? An opcode could be a NOP for some specific parameters.
Reimplemented from dng_opcode.
References dng_warp_params::IsNOPAll().
PutData()
void dng_opcode_WarpRectilinear::PutData (dng_stream & stream) const virtual
Write opcode to a stream.
Parameters
stream The stream to which to write the opcode data.
Reimplemented from dng_opcode.
References dng_stream::Put_real64(), and dng_stream::Put_uint32().
The documentation for this class was generated from the following files:
dng_lens_correction.h
dng_lens_correction.cpp