DNG SDK 1.5: dng_image_writer Class Reference
dng_image_writer Class Reference
Support for writing dng_image or dng_negative instances to a dng_stream in TIFF or DNG format.
#include <dng_image_writer.h>
Public Member Functions
virtual void EncodeJPEGPreview (dng_host &host, const dng_image &image, dng_jpeg_preview &preview, int32 quality=-1)
virtual void WriteImage (dng_host &host, const dng_ifd &ifd, dng_basic_tag_set &basic, dng_stream &stream, const dng_image &image, uint32 fakeChannels=1)
void WriteTIFF (dng_host &host, dng_stream &stream, const dng_image &image, uint32 photometricInterpretation, uint32 compression, dng_negative *negative, const dng_color_space *space=NULL, const dng_resolution *resolution=NULL, const dng_jpeg_preview *thumbnail=NULL, const dng_memory_block *imageResources=NULL, dng_metadata_subset metadataSubset=kMetadataSubset_All, bool hasTransparency=false)
void WriteTIFF (dng_host &host, dng_stream &stream, const dng_image &image, uint32 photometricInterpretation=piBlackIsZero, uint32 compression=ccUncompressed, const dng_metadata *metadata=NULL, const dng_color_space *space=NULL, const dng_resolution *resolution=NULL, const dng_jpeg_preview *thumbnail=NULL, const dng_memory_block *imageResources=NULL, dng_metadata_subset metadataSubset=kMetadataSubset_All, bool hasTransparency=false)
void WriteTIFFWithProfile (dng_host &host, dng_stream &stream, const dng_image &image, uint32 photometricInterpretation, uint32 compression, dng_negative *negative, const void *profileData=NULL, uint32 profileSize=0, const dng_resolution *resolution=NULL, const dng_jpeg_preview *thumbnail=NULL, const dng_memory_block *imageResources=NULL, dng_metadata_subset metadataSubset=kMetadataSubset_All, bool hasTransparency=false)
virtual void WriteTIFFWithProfile (dng_host &host, dng_stream &stream, const dng_image &image, uint32 photometricInterpretation=piBlackIsZero, uint32 compression=ccUncompressed, const dng_metadata *metadata=NULL, const void *profileData=NULL, uint32 profileSize=0, const dng_resolution *resolution=NULL, const dng_jpeg_preview *thumbnail=NULL, const dng_memory_block *imageResources=NULL, dng_metadata_subset metadataSubset=kMetadataSubset_All, bool hasTransparency=false)
void WriteDNG (dng_host &host, dng_stream &stream, dng_negative &negative, const dng_preview_list *previewList=NULL, uint32 maxBackwardVersion=dngVersion_SaveDefault, bool uncompressed=false)
virtual void WriteDNGWithMetadata (dng_host &host, dng_stream &stream, const dng_negative &negative, const dng_metadata &metadata, const dng_preview_list *previewList=NULL, uint32 maxBackwardVersion=dngVersion_SaveDefault, bool uncompressed=false)
virtual void CleanUpMetadata (dng_host &host, dng_metadata &metadata, dng_metadata_subset metadataSubset, const char *dstMIME, const char *software=NULL)
Protected Types
enum { kImageBufferSize = 128 * 1024 }
Protected Member Functions
virtual void UpdateExifColorSpaceTag (dng_metadata &metadata, const void *profileData, const uint32 profileSize)
virtual uint32 CompressedBufferSize (const dng_ifd &ifd, uint32 uncompressedSize)
virtual void EncodePredictor (dng_host &host, const dng_ifd &ifd, dng_pixel_buffer &buffer, AutoPtr< dng_memory_block > &tempBuffer)
virtual void ByteSwapBuffer (dng_host &host, dng_pixel_buffer &buffer)
void ReorderSubTileBlocks (const dng_ifd &ifd, dng_pixel_buffer &buffer, AutoPtr< dng_memory_block > &uncompressedBuffer, AutoPtr< dng_memory_block > &subTileBlockBuffer)
virtual void WriteData (dng_host &host, const dng_ifd &ifd, dng_stream &stream, dng_pixel_buffer &buffer, AutoPtr< dng_memory_block > &compressedBuffer, bool usingMultipleThreads)
virtual void WriteTile (dng_host &host, const dng_ifd &ifd, dng_stream &stream, const dng_image &image, const dng_rect &tileArea, uint32 fakeChannels, AutoPtr< dng_memory_block > &compressedBuffer, AutoPtr< dng_memory_block > &uncompressedBuffer, AutoPtr< dng_memory_block > &subTileBlockBuffer, AutoPtr< dng_memory_block > &tempBuffer, bool usingMultipleThreads)
virtual void DoWriteTiles (dng_host &host, const dng_ifd &ifd, dng_basic_tag_set &basic, dng_stream &stream, const dng_image &image, uint32 fakeChannels, uint32 tilesDown, uint32 tilesAcross, uint32 compressedSize, const dng_safe_uint32 &uncompressedSize)
Friends
class dng_jpeg_image
class dng_jpeg_image_encode_task
class dng_write_tiles_task
Detailed Description
Support for writing dng_image or dng_negative instances to a dng_stream in TIFF or DNG format.
Member Function Documentation
CleanUpMetadata()
void dng_image_writer::CleanUpMetadata (dng_host & host, dng_metadata & metadata, dng_metadata_subset metadataSubset, const char * dstMIME, const char * software = NULL) virtual
Resolve metadata conflicts and apply metadata policies in keeping with Metadata Working Group (MWG) guidelines.
Referenced by WriteDNGWithMetadata().
WriteDNG()
void dng_image_writer::WriteDNG (dng_host & host, dng_stream & stream, dng_negative & negative, const dng_preview_list * previewList = NULL, uint32 maxBackwardVersion = dngVersion_SaveDefault, bool uncompressed = false)
Write a dng_image to a dng_stream in DNG format.
Parameters
host Host interface used for progress updates, abort testing, buffer allocation, etc.
stream The dng_stream on which to write the TIFF.
negative The image data and metadata (EXIF, IPTC, XMP) to be written.
previewList List of previews (not counting thumbnail) to write to the file. Defaults to empty.
maxBackwardVersion The DNG file should be readable by readers at least back to this version.
uncompressed True to force uncompressed images. Otherwise use normal compression.
References dng_negative::Metadata(), and WriteDNGWithMetadata().
WriteDNGWithMetadata()
void dng_image_writer::WriteDNGWithMetadata (dng_host & host, dng_stream & stream, const dng_negative & negative, const dng_metadata & metadata, const dng_preview_list * previewList = NULL, uint32 maxBackwardVersion = dngVersion_SaveDefault, bool uncompressed = false) virtual
Write a dng_image to a dng_stream in DNG format.
Parameters
host Host interface used for progress updates, abort testing, buffer allocation, etc.
stream The dng_stream on which to write the TIFF.
negative The image data to be written.
metadata The metadata (EXIF, IPTC, XMP) to be written.
previewList List of previews (not counting thumbnail) to write to the file. Defaults to empty.
maxBackwardVersion The DNG file should be readable by readers at least back to this version.
uncompressed True to force uncompressed images. Otherwise use normal compression.
References dng_host::Allocator(), CleanUpMetadata(), and dng_metadata::Clone().
Referenced by WriteDNG().
WriteTIFF()
void dng_image_writer::WriteTIFF (dng_host & host, dng_stream & stream, const dng_image & image, uint32 photometricInterpretation, uint32 compression, dng_negative * negative, const dng_color_space * space = NULL, const dng_resolution * resolution = NULL, const dng_jpeg_preview * thumbnail = NULL, const dng_memory_block * imageResources = NULL, dng_metadata_subset metadataSubset = kMetadataSubset_All, bool hasTransparency = false)
Write a dng_image to a dng_stream in TIFF format.
Parameters
host Host interface used for progress updates, abort testing, buffer allocation, etc.
stream The dng_stream on which to write the TIFF.
image The actual image data to be written.
photometricInterpretation Either piBlackIsZero for monochrome or piRGB for RGB images.
compression Must be ccUncompressed.
negative or metadata If non-NULL, EXIF, IPTC, and XMP metadata from this negative is written to TIFF.
space If non-null and color space has an ICC profile, TIFF will be tagged with this profile. No color space conversion of image data occurs.
resolution If non-NULL, TIFF will be tagged with this resolution.
thumbnail If non-NULL, will be stored in TIFF as preview image.
imageResources If non-NULL, will image resources be stored in TIFF as well.
metadataSubset The subset of metadata (e.g., copyright only) to include in the TIFF.
References dng_negative::Metadata().
WriteTIFFWithProfile()
void dng_image_writer::WriteTIFFWithProfile (dng_host & host, dng_stream & stream, const dng_image & image, uint32 photometricInterpretation, uint32 compression, dng_negative * negative, const void * profileData = NULL, uint32 profileSize = 0, const dng_resolution * resolution = NULL, const dng_jpeg_preview * thumbnail = NULL, const dng_memory_block * imageResources = NULL, dng_metadata_subset metadataSubset = kMetadataSubset_All, bool hasTransparency = false)
Write a dng_image to a dng_stream in TIFF format.
Parameters
host Host interface used for progress updates, abort testing, buffer allocation, etc.
stream The dng_stream on which to write the TIFF.
image The actual image data to be written.
photometricInterpretation Either piBlackIsZero for monochrome or piRGB for RGB images.
compression Must be ccUncompressed.
negative or metadata If non-NULL, EXIF, IPTC, and XMP metadata from this negative is written to TIFF.
profileData If non-null, TIFF will be tagged with this profile. No color space conversion of image data occurs.
profileSize The size for the profile data.
resolution If non-NULL, TIFF will be tagged with this resolution.
thumbnail If non-NULL, will be stored in TIFF as preview image.
imageResources If non-NULL, will image resources be stored in TIFF as well.
metadataSubset The subset of metadata (e.g., copyright only) to include in the TIFF.
References dng_negative::Metadata().
The documentation for this class was generated from the following files:
dng_image_writer.h
dng_image_writer.cpp