DNG SDK 1.5: dng_opcode_MapPolynomial Class Reference
dng_opcode_MapPolynomial Class Reference
An opcode to apply a 1D function (represented as a polynomial) to an image area.
#include <dng_misc_opcodes.h>
Public Types
enum { kMaxDegree = 8 }
Public Types inherited from dng_opcode
enum { kFlag_None = 0, kFlag_Optional = 1, kFlag_SkipIfPreview = 2 }
Opcode flags.
Public Member Functions
dng_opcode_MapPolynomial (const dng_area_spec &areaSpec, uint32 degree, const real64 *coefficient)
dng_opcode_MapPolynomial (dng_stream &stream)
virtual void PutData (dng_stream &stream) const
virtual uint32 BufferPixelType (uint32 imagePixelType)
The pixel data type of this opcode.
virtual dng_rect ModifiedBounds (const dng_rect &imageBounds)
virtual void ProcessArea (dng_negative &negative, uint32 threadIndex, dng_pixel_buffer &buffer, const dng_rect &dstArea, const dng_rect &imageBounds)
uint32 Degree () const
const real64 * Coefficients () const
Public Member Functions inherited from dng_inplace_opcode
virtual void Prepare (dng_negative &negative, uint32 threadCount, const dng_point &tileSize, const dng_rect &imageBounds, uint32 imagePlanes, uint32 bufferPixelType, dng_memory_allocator &allocator)
virtual void Apply (dng_host &host, dng_negative &negative, AutoPtr< dng_image > &image)
Apply this opcode to the specified image with associated negative.
Public Member Functions inherited from dng_opcode
uint32 OpcodeID () const
The ID of this opcode.
uint32 MinVersion () const
The first DNG version that supports this opcode.
uint32 Flags () const
The flags for this opcode.
bool Optional () const
Is this opcode optional?
bool SkipIfPreview () const
Should the opcode be skipped when rendering preview images?
bool WasReadFromStream () const
Was this opcode read from a data stream?
uint32 Stage () const
void SetStage (uint32 stage)
virtual bool IsNOP () const
virtual bool IsValidForNegative (const dng_negative &) const
Is this opcode valid for the specified negative?
bool AboutToApply (dng_host &host, dng_negative &negative, const dng_rect &imageBounds, uint32 imagePlanes)
Protected Member Functions
virtual void DoProcess (dng_pixel_buffer &buffer, const dng_rect &area, const uint32 plane, const uint32 rowPitch, const uint32 colPitch, const real32 *coefficients, const uint32 degree, uint16 blackLevel) const
Protected Member Functions inherited from dng_inplace_opcode
dng_inplace_opcode (uint32 opcodeID, uint32 minVersion, uint32 flags)
dng_inplace_opcode (uint32 opcodeID, dng_stream &stream, const char *name)
Protected Member Functions inherited from dng_opcode
dng_opcode (uint32 opcodeID, uint32 minVersion, uint32 flags)
dng_opcode (uint32 opcodeID, dng_stream &stream, const char *name)
virtual void DoAboutToApply (dng_host &, dng_negative &, const dng_rect &, uint32)
Protected Attributes
dng_area_spec fAreaSpec
uint32 fDegree
real64 fCoefficient [kMaxDegree+1]
real32 fCoefficient32 [kMaxDegree+1]
Detailed Description
An opcode to apply a 1D function (represented as a polynomial) to an image area.
Constructor & Destructor Documentation
dng_opcode_MapPolynomial()
dng_opcode_MapPolynomial::dng_opcode_MapPolynomial (const dng_area_spec & areaSpec, uint32 degree, const real64 * coefficient)
Create a MapPolynomial opcode with the specified area, polynomial degree, and polynomial coefficients. The function that will be applied to each pixel x is:
f (x) = coefficient [0] + ((x * coefficient [1]) + (x^2 * coefficient [2]) + (x^3 * coefficient [3]) + (x^4 * coefficient [4]) ...
Member Function Documentation
ModifiedBounds()
dng_rect dng_opcode_MapPolynomial::ModifiedBounds (const dng_rect & imageBounds) virtual
The adjusted bounds (processing area) of this opcode. It is limited to the intersection of the specified image area and the GainMap area.
Reimplemented from dng_inplace_opcode.
References dng_area_spec::Overlap().
ProcessArea()
void dng_opcode_MapPolynomial::ProcessArea (dng_negative & negative, uint32 threadIndex, dng_pixel_buffer & buffer, const dng_rect & dstArea, const dng_rect & imageBounds) virtual
Implements image processing operation in a single buffer. The source pixels are provided as input to the buffer, and this routine calculates and writes the destination pixels to the same buffer. Ideally, no allocation should be done in this routine.
Parameters
negative The negative associated with the pixels to be processed.
threadIndex The thread on which this routine is being called, between 0 and threadCount - 1 for the threadCount passed to Prepare method.
buffer Source and Destination pixels.
dstArea Destination pixel processing area.
imageBounds Total image area to be processed; dstArea will always lie within these bounds.
Implements dng_inplace_opcode.
References dng_area_spec::ColPitch(), dng_area_spec::Overlap(), dng_area_spec::Plane(), dng_area_spec::Planes(), dng_pixel_buffer::Planes(), dng_area_spec::RowPitch(), and dng_opcode::Stage().
PutData()
void dng_opcode_MapPolynomial::PutData (dng_stream & stream) const virtual
Write opcode to a stream.
Parameters
stream The stream to which to write the opcode data.
Reimplemented from dng_opcode.
References dng_stream::Put_real64(), dng_stream::Put_uint32(), and dng_area_spec::PutData().
The documentation for this class was generated from the following files:
dng_misc_opcodes.h
dng_misc_opcodes.cpp