DNG SDK 1.5: dng_camera_profile Class Reference
dng_camera_profile Class Reference
Container for DNG camera color profile and calibration data.
#include <dng_camera_profile.h>
Public Member Functions
void SetName (const char *name)
const dng_string & Name () const
bool NameIsEmbedded () const
void SetCalibrationIlluminant1 (uint32 light)
void SetCalibrationIlluminant2 (uint32 light)
uint32 CalibrationIlluminant1 () const
uint32 CalibrationIlluminant2 () const
real64 CalibrationTemperature1 () const
real64 CalibrationTemperature2 () const
void SetColorMatrix1 (const dng_matrix &m)
void SetColorMatrix2 (const dng_matrix &m)
bool HasColorMatrix1 () const
Predicate to test if first camera matrix is set.
bool HasColorMatrix2 () const
Predicate to test if second camera matrix is set.
const dng_matrix & ColorMatrix1 () const
Getter for first of up to two color matrices used for calibrations.
const dng_matrix & ColorMatrix2 () const
Getter for second of up to two color matrices used for calibrations.
void SetForwardMatrix1 (const dng_matrix &m)
Setter for first of up to two forward matrices used for calibrations.
void SetForwardMatrix2 (const dng_matrix &m)
Setter for second of up to two forward matrices used for calibrations.
const dng_matrix & ForwardMatrix1 () const
Getter for first of up to two forward matrices used for calibrations.
const dng_matrix & ForwardMatrix2 () const
Getter for second of up to two forward matrices used for calibrations.
void SetReductionMatrix1 (const dng_matrix &m)
void SetReductionMatrix2 (const dng_matrix &m)
const dng_matrix & ReductionMatrix1 () const
Getter for first of up to two dimensionality reduction hints for four color cameras.
const dng_matrix & ReductionMatrix2 () const
Getter for second of up to two dimensionality reduction hints for four color cameras.
const dng_fingerprint & Fingerprint () const
Getter function from profile fingerprint.
dng_fingerprint UniqueID () const
dng_camera_profile_id ProfileID () const
void SetCopyright (const char *copyright)
const dng_string & Copyright () const
void SetEmbedPolicy (uint32 policy)
uint32 EmbedPolicy () const
bool IsLegalToEmbed () const
bool HasHueSatDeltas () const
Returns true iff the profile has a valid HueSatMap color table.
const dng_hue_sat_map & HueSatDeltas1 () const
Getter for first HueSatMap color table (for calibration illuminant 1).
void SetHueSatDeltas1 (const dng_hue_sat_map &deltas1)
Setter for first HueSatMap color table (for calibration illuminant 1).
const dng_hue_sat_map & HueSatDeltas2 () const
Getter for second HueSatMap color table (for calibration illuminant 2).
void SetHueSatDeltas2 (const dng_hue_sat_map &deltas2)
Setter for second HueSatMap color table (for calibration illuminant 2).
uint32 HueSatMapEncoding () const
Returns the hue sat map encoding (see ProfileHueSatMapEncoding tag).
void SetHueSatMapEncoding (uint32 encoding)
bool HasLookTable () const
Returns true if the profile has a LookTable.
const dng_hue_sat_map & LookTable () const
Getter for LookTable.
void SetLookTable (const dng_hue_sat_map &table)
Setter for LookTable.
uint32 LookTableEncoding () const
Returns the LookTable encoding (see ProfileLookTableEncoding tag).
void SetLookTableEncoding (uint32 encoding)
void SetBaselineExposureOffset (real64 exposureOffset)
const dng_srational & BaselineExposureOffset () const
void SetDefaultBlackRender (uint32 defaultBlackRender)
uint32 DefaultBlackRender () const
const dng_tone_curve & ToneCurve () const
Returns the tone curve of the profile.
void SetToneCurve (const dng_tone_curve &curve)
Sets the tone curve of the profile to the specified curve.
void SetProfileCalibrationSignature (const char *signature)
const dng_string & ProfileCalibrationSignature () const
void SetUniqueCameraModelRestriction (const char *camera)
const dng_string & UniqueCameraModelRestriction () const
void SetWasReadFromDNG (bool state=true)
bool WasReadFromDNG () const
Was this profile read from a DNG?
void SetWasReadFromDisk (bool state=true)
bool WasReadFromDisk () const
Was this profile read from disk?
void SetWasBuiltinMatrix (bool state=true)
bool WasBuiltinMatrix () const
Was this profile a built-in matrix profile?
bool IsValid (uint32 channels) const
bool EqualData (const dng_camera_profile &profile) const
void Parse (dng_stream &stream, dng_camera_profile_info &profileInfo)
Parse profile from dng_camera_profile_info data.
bool ParseExtended (dng_stream &stream)
virtual void SetFourColorBayer ()
Convert from a three-color to a four-color Bayer profile.
dng_hue_sat_map * HueSatMapForWhite (const dng_xy_coord &white) const
void Stub ()
Stub out the profile (free memory used by large tables).
bool WasStubbed () const
Was this profile stubbed?
Static Public Member Functions
static void NormalizeColorMatrix (dng_matrix &m)
Utility function to normalize the scale of the color matrix.
static void NormalizeForwardMatrix (dng_matrix &m)
Utility function to normalize the scale of the forward matrix.
Protected Member Functions
void ClearFingerprint ()
void CalculateFingerprint () const
Static Protected Member Functions
static real64 IlluminantToTemperature (uint32 light)
static bool ValidForwardMatrix (const dng_matrix &m)
static void ReadHueSatMap (dng_stream &stream, dng_hue_sat_map &hueSatMap, uint32 hues, uint32 sats, uint32 vals, bool skipSat0)
Protected Attributes
dng_string fName
uint32 fCalibrationIlluminant1
uint32 fCalibrationIlluminant2
dng_matrix fColorMatrix1
dng_matrix fColorMatrix2
dng_matrix fForwardMatrix1
dng_matrix fForwardMatrix2
dng_matrix fReductionMatrix1
dng_matrix fReductionMatrix2
dng_fingerprint fFingerprint
dng_string fCopyright
uint32 fEmbedPolicy
dng_hue_sat_map fHueSatDeltas1
dng_hue_sat_map fHueSatDeltas2
uint32 fHueSatMapEncoding
dng_hue_sat_map fLookTable
uint32 fLookTableEncoding
dng_srational fBaselineExposureOffset
uint32 fDefaultBlackRender
dng_tone_curve fToneCurve
dng_string fProfileCalibrationSignature
dng_string fUniqueCameraModelRestriction
bool fWasReadFromDNG
bool fWasReadFromDisk
bool fWasBuiltinMatrix
bool fWasStubbed
Detailed Description
Container for DNG camera color profile and calibration data.
Member Function Documentation
BaselineExposureOffset()
const dng_srational& dng_camera_profile::BaselineExposureOffset () const inline
Returns the baseline exposure offset of the profile (see BaselineExposureOffset tag).
Referenced by dng_negative::TotalBaselineExposure().
CalibrationIlluminant1()
uint32 dng_camera_profile::CalibrationIlluminant1 () const inline
Getter for first of up to two light sources used for calibration. Uses the EXIF encodings for illuminant and is used to distinguish which matrix to use. Corresponds to the DNG CalibrationIlluminant1 tag.
Referenced by CalibrationTemperature1().
CalibrationIlluminant2()
uint32 dng_camera_profile::CalibrationIlluminant2 () const inline
Getter for second of up to two light sources used for calibration. Uses the EXIF encodings for illuminant and is used to distinguish which matrix to use. Corresponds to the DNG CalibrationIlluminant2 tag.
Referenced by CalibrationTemperature2().
CalibrationTemperature1()
real64 dng_camera_profile::CalibrationTemperature1 () const inline
Getter for first of up to two light sources used for calibration, returning result as color temperature.
References CalibrationIlluminant1().
Referenced by dng_color_spec::dng_color_spec(), and HueSatMapForWhite().
CalibrationTemperature2()
real64 dng_camera_profile::CalibrationTemperature2 () const inline
Getter for second of up to two light sources used for calibration, returning result as color temperature.
References CalibrationIlluminant2().
Referenced by dng_color_spec::dng_color_spec(), and HueSatMapForWhite().
Copyright()
const dng_string& dng_camera_profile::Copyright () const inline
Getter for camera profile copyright.
Return values
Copyright string for profile.
DefaultBlackRender()
uint32 dng_camera_profile::DefaultBlackRender () const inline
Returns the default black render of the profile (see DefaultBlackRender tag).
Referenced by dng_render::dng_render().
EmbedPolicy()
uint32 dng_camera_profile::EmbedPolicy () const inline
Getter for camera profile embed policy.
Return values
Policy for profile.
Referenced by IsLegalToEmbed().
EqualData()
bool dng_camera_profile::EqualData (const dng_camera_profile & profile) const
Predicate to check if two camera profiles are colorwise equal, thus ignores the profile name.
Parameters
profile Camera profile to compare to.
HueSatMapForWhite()
dng_hue_sat_map * dng_camera_profile::HueSatMapForWhite (const dng_xy_coord & white) const
Find the hue/sat table to use for a given white point, if any. The calling routine owns the resulting table.
References CalibrationTemperature1(), CalibrationTemperature2(), HueSatDeltas1(), HueSatDeltas2(), dng_hue_sat_map::Interpolate(), and dng_hue_sat_map::IsValid().
IsLegalToEmbed()
bool dng_camera_profile::IsLegalToEmbed () const inline
Returns true iff the profile is legal to embed in a DNG, per the profile's embed policy.
References EmbedPolicy(), and WasReadFromDNG().
IsValid()
bool dng_camera_profile::IsValid (uint32 channels) const
Determines if this a valid profile for this number of color channels?
Return values
true if the profile is valid.
References ReportError().
Referenced by dng_color_spec::dng_color_spec(), dng_info::Parse(), and SetFourColorBayer().
Name()
const dng_string& dng_camera_profile::Name () const inline
Getter for camera profile name.
Return values
Name of profile.
Referenced by ProfileID().
NameIsEmbedded()
bool dng_camera_profile::NameIsEmbedded () const inline
Test if this name is embedded.
Return values
true if the name matches the name of the embedded camera profile.
ParseExtended()
bool dng_camera_profile::ParseExtended (dng_stream & stream)
Parse from an extended profile stream, which is similar to stand alone TIFF file.
References Parse().
ProfileCalibrationSignature()
const dng_string& dng_camera_profile::ProfileCalibrationSignature () const inline
Returns the profile calibration signature (see ProfileCalibrationSignature tag) of the profile.
Referenced by dng_color_spec::dng_color_spec().
ProfileID()
dng_camera_profile_id dng_camera_profile::ProfileID () const inline
Getter for camera profile id.
Return values
ID of profile.
References Fingerprint(), and Name().
SetBaselineExposureOffset()
void dng_camera_profile::SetBaselineExposureOffset (real64 exposureOffset) inline
Sets the baseline exposure offset of the profile (see BaselineExposureOffset tag) to the specified value.
SetCalibrationIlluminant1()
void dng_camera_profile::SetCalibrationIlluminant1 (uint32 light) inline
Setter for first of up to two light sources used for calibration. Uses the EXIF encodings for illuminant and is used to distinguish which matrix to use. Corresponds to the DNG CalibrationIlluminant1 tag.
SetCalibrationIlluminant2()
void dng_camera_profile::SetCalibrationIlluminant2 (uint32 light) inline
Setter for second of up to two light sources used for calibration. Uses the EXIF encodings for illuminant and is used to distinguish which matrix to use. Corresponds to the DNG CalibrationIlluminant2 tag.
SetColorMatrix1()
void dng_camera_profile::SetColorMatrix1 (const dng_matrix & m)
Setter for first of up to two color matrices used for reference camera calibrations. These matrices map XYZ values to camera values. The DNG SDK needs to map colors that direction in order to determine the clipping points for highlight recovery logic based on the white point. If cameras were all three-color, the matrix could be stored as a forward matrix. The inverse matrix is requried to support four-color cameras.
References NormalizeColorMatrix().
SetColorMatrix2()
void dng_camera_profile::SetColorMatrix2 (const dng_matrix & m)
Setter for second of up to two color matrices used for reference camera calibrations. These matrices map XYZ values to camera values. The DNG SDK needs to map colors that direction in order to determine the clipping points for highlight recovery logic based on the white point. If cameras were all three-color, the matrix could be stored as a forward matrix. The inverse matrix is requried to support four-color cameras.
References NormalizeColorMatrix().
SetCopyright()
void dng_camera_profile::SetCopyright (const char * copyright) inline
Setter for camera profile copyright.
Parameters
copyright Copyright string to use for this camera profile.
SetDefaultBlackRender()
void dng_camera_profile::SetDefaultBlackRender (uint32 defaultBlackRender) inline
Sets the default black render of the profile (see DefaultBlackRender tag) to the specified option.
SetEmbedPolicy()
void dng_camera_profile::SetEmbedPolicy (uint32 policy) inline
Setter for camera profile embed policy.
Parameters
policy Policy to use for this camera profile.
SetHueSatMapEncoding()
void dng_camera_profile::SetHueSatMapEncoding (uint32 encoding) inline
Sets the hue sat map encoding (see ProfileHueSatMapEncoding tag) to the specified encoding.
SetLookTableEncoding()
void dng_camera_profile::SetLookTableEncoding (uint32 encoding) inline
Sets the LookTable encoding (see ProfileLookTableEncoding tag) to the specified encoding.
SetName()
void dng_camera_profile::SetName (const char * name) inline
Setter for camera profile name.
Parameters
name Name to use for this camera profile.
SetProfileCalibrationSignature()
void dng_camera_profile::SetProfileCalibrationSignature (const char * signature) inline
Sets the profile calibration signature (see ProfileCalibrationSignature tag) to the specified string.
SetReductionMatrix1()
void dng_camera_profile::SetReductionMatrix1 (const dng_matrix & m)
Setter for first of up to two dimensionality reduction hints for four-color cameras. This is an optional matrix that maps four components to three. See Appendix 6 of the DNG 1.1.0 specification.
SetReductionMatrix2()
void dng_camera_profile::SetReductionMatrix2 (const dng_matrix & m)
Setter for second of up to two dimensionality reduction hints for four-color cameras. This is an optional matrix that maps four components to three. See Appendix 6 of the DNG 1.1.0 specification.
SetUniqueCameraModelRestriction()
void dng_camera_profile::SetUniqueCameraModelRestriction (const char * camera) inline
Setter for camera unique model name to restrict use of this profile.
Parameters
camera Camera unique model name designating only camera this profile can be used with. (Empty string for no restriction.)
SetWasBuiltinMatrix()
void dng_camera_profile::SetWasBuiltinMatrix (bool state = true) inline
Sets internal flag to indicate this profile was originally a built-in matrix profile.
SetWasReadFromDisk()
void dng_camera_profile::SetWasReadFromDisk (bool state = true) inline
Sets internal flag to indicate this profile was originally read from disk.
SetWasReadFromDNG()
void dng_camera_profile::SetWasReadFromDNG (bool state = true) inline
Sets internal flag to indicate this profile was originally read from a DNG file.
UniqueCameraModelRestriction()
const dng_string& dng_camera_profile::UniqueCameraModelRestriction () const inline
Getter for camera unique model name to restrict use of this profile.
Return values
Unique model name of only camera this profile can be used with or empty if no restriction.
UniqueID()
dng_fingerprint dng_camera_profile::UniqueID () const
Getter for camera profile unique ID. Use this ID for uniquely identifying profiles (e.g., for syncing purposes).
References dng_fingerprint::IsValid(), dng_stream::Put(), and dng_stream::SetLittleEndian().
The documentation for this class was generated from the following files:
dng_camera_profile.h
dng_camera_profile.cpp