DNG SDK 1.5: dng_write_tiles_task Class Reference
dng_write_tiles_task Class Reference
Public Member Functions
dng_write_tiles_task (dng_image_writer &imageWriter, dng_host &host, const dng_ifd &ifd, dng_basic_tag_set &basic, dng_stream &stream, const dng_image &image, uint32 fakeChannels, uint32 tilesDown, uint32 tilesAcross, uint32 compressedSize, uint32 uncompressedSize)
void Process (uint32 threadIndex, const dng_rect &tile, dng_abort_sniffer *sniffer)
and progress updates.
Public Member Functions inherited from dng_area_task
dng_area_task (const char *name="unnamed dng_area_task")
const char * Name () const
virtual uint32 MaxThreads () const
virtual uint32 MinTaskArea () const
operation. (Partitions can be smaller due to small inputs and edge cases.)
virtual dng_point UnitCell () const
virtual dng_point MaxTileSize () const
virtual dng_rect RepeatingTile1 () const
virtual dng_rect RepeatingTile2 () const
virtual dng_rect RepeatingTile3 () const
virtual void Start (uint32 threadCount, const dng_rect &dstArea, const dng_point &tileSize, dng_memory_allocator *allocator, dng_abort_sniffer *sniffer)
virtual void Finish (uint32 threadCount)
dng_point FindTileSize (const dng_rect &area) const
void ProcessOnThread (uint32 threadIndex, const dng_rect &area, const dng_point &tileSize, dng_abort_sniffer *sniffer, dng_area_task_progress *progress)
virtual dng_base_tile_iterator * MakeTileIterator (uint32 threadIndex, const dng_rect &tile, const dng_rect &area) const
virtual dng_base_tile_iterator * MakeTileIterator (uint32 threadIndex, const dng_point &tileSize, const dng_rect &area) const
Protected Member Functions
void ProcessTask (uint32 tileIndex, AutoPtr< dng_memory_block > &compressedBuffer, AutoPtr< dng_memory_block > &uncompressedBuffer, AutoPtr< dng_memory_block > &subTileBlockBuffer, AutoPtr< dng_memory_block > &tempBuffer, uint32 &tileByteCount, dng_memory_stream &tileStream, dng_abort_sniffer *sniffer)
void WriteTask (uint32 tileIndex, uint32 tileByteCount, dng_memory_stream &tileStream, dng_abort_sniffer *sniffer)
Protected Attributes
dng_image_writer & fImageWriter
dng_host & fHost
const dng_ifd & fIFD
dng_basic_tag_set & fBasic
dng_stream & fStream
const dng_image & fImage
uint32 fFakeChannels
uint32 fTilesDown
uint32 fTilesAcross
uint32 fCompressedSize
uint32 fUncompressedSize
std::atomic_uint fNextTileIndex
dng_mutex fMutex
dng_condition fCondition
bool fTaskFailed
uint32 fWriteTileIndex
Protected Attributes inherited from dng_area_task
uint32 fMaxThreads
uint32 fMinTaskArea
dng_point fUnitCell
dng_point fMaxTileSize
dng_string fName
Additional Inherited Members
Static Public Member Functions inherited from dng_area_task
static void Perform (dng_area_task &task, const dng_rect &area, dng_memory_allocator *allocator, dng_abort_sniffer *sniffer, dng_area_task_progress *progress)
Member Function Documentation
Process()
void dng_write_tiles_task::Process (uint32 threadIndex, const dng_rect & tile, dng_abort_sniffer * sniffer) virtual
and progress updates.
Process one tile or fully partitioned area. This method is overridden by derived classes to implement the actual image processing. Note that the sniffer can be ignored if it is certain that a processing task will complete very quickly. This method should never be called directly but rather accessed via Process. There is no allocator parameter as all allocation should be done in Start.
Parameters
threadIndex 0 to threadCount - 1 index indicating which thread this is. (Can be used to get a thread-specific buffer allocated in the Start method.)
tile Area to process.
sniffer dng_abort_sniffer to use to check for user cancellation
Implements dng_area_task.
References dng_host::Allocate(), dng_host::Allocator(), and AutoPtr< T >::Reset().
The documentation for this class was generated from the following files:
dng_image_writer.h
dng_image_writer.cpp