DNG SDK 1.5: dng_file_stream Class Reference
dng_file_stream Class Reference
A stream to/from a disk file. See dng_stream for read/write interface.
#include <dng_file_stream.h>
Public Member Functions
dng_file_stream (const char *filename, bool output=false, uint32 bufferSize=kDefaultBufferSize)
Public Member Functions inherited from dng_stream
dng_stream (const void *data, uint32 count, uint64 offsetInOriginalFile=kDNGStreamInvalidOffset)
bool SwapBytes () const
void SetSwapBytes (bool swapBytes)
bool BigEndian () const
void SetBigEndian (bool bigEndian=true)
bool LittleEndian () const
void SetLittleEndian (bool littleEndian=true)
uint32 BufferSize () const
Returns the size of the buffer used by the stream.
void SetBufferSize (dng_memory_allocator &allocator, uint32 newBufferSize)
Change the buffer size on the stream, if possible.
uint64 Length ()
uint64 Position () const
uint64 PositionInOriginalFile () const
uint64 OffsetInOriginalFile () const
const void * Data () const
dng_memory_block * AsMemoryBlock (dng_memory_allocator &allocator)
void SetReadPosition (uint64 offset)
Seek to a new position in stream for reading.
void Skip (uint64 delta)
bool DataInBuffer (uint32 count, uint64 offset)
Quick check to see if data range in completely buffered.
void Get (void *data, uint32 count, uint32 maxOverRead=0)
void SetWritePosition (uint64 offset)
Seek to a new position in stream for writing.
void Flush ()
Force any stored data in stream to be written to underlying storage.
void SetLength (uint64 length)
void Put (const void *data, uint32 count)
uint8 Get_uint8 ()
void Put_uint8 (uint8 x)
uint16 Get_uint16 ()
void Put_uint16 (uint16 x)
uint32 Get_uint32 ()
uint32 Get_uint32_LE ()
void Put_uint32 (uint32 x)
uint64 Get_uint64 ()
void Put_uint64 (uint64 x)
int8 Get_int8 ()
void Put_int8 (int8 x)
int16 Get_int16 ()
void Put_int16 (int16 x)
int32 Get_int32 ()
void Put_int32 (int32 x)
int64 Get_int64 ()
void Put_int64 (int64 x)
real32 Get_real32 ()
void Put_real32 (real32 x)
real64 Get_real64 ()
void Put_real64 (real64 x)
void Get_CString (char *data, uint32 maxLength)
void Get_UString (char *data, uint32 maxLength)
void PutZeros (uint64 count)
void PadAlign2 ()
Writes zeros to align the stream position to a multiple of 2.
void PadAlign4 ()
Writes zeros to align the stream position to a multiple of 4.
uint32 TagValue_uint32 (uint32 tagType)
int32 TagValue_int32 (uint32 tagType)
dng_urational TagValue_urational (uint32 tagType)
dng_srational TagValue_srational (uint32 tagType)
real64 TagValue_real64 (uint32 tagType)
dng_abort_sniffer * Sniffer () const
void SetSniffer (dng_abort_sniffer *sniffer)
virtual void CopyToStream (dng_stream &dstStream, uint64 count)
void DuplicateStream (dng_stream &dstStream)
Protected Member Functions
virtual uint64 DoGetLength ()
virtual void DoRead (void *data, uint32 count, uint64 offset)
virtual void DoWrite (const void *data, uint32 count, uint64 offset)
Protected Member Functions inherited from dng_stream
dng_stream (dng_abort_sniffer *sniffer=NULL, uint32 bufferSize=kDefaultBufferSize, uint64 offsetInOriginalFile=kDNGStreamInvalidOffset)
virtual void DoSetLength (uint64 length)
Additional Inherited Members
Public Types inherited from dng_stream
enum { kSmallBufferSize = 8 * 1024, kBigBufferSize = 64 * 1024, kDefaultBufferSize = kSmallBufferSize }
Detailed Description
A stream to/from a disk file. See dng_stream for read/write interface.
Constructor & Destructor Documentation
dng_file_stream()
dng_file_stream::dng_file_stream (const char * filename, bool output = false, uint32 bufferSize = kDefaultBufferSize)
Open a stream on a file.
Parameters
filename Pathname in platform synax.
output Set to true if writing, false otherwise.
bufferSize size of internal buffer to use. Defaults to 4k.
References ReportError(), ThrowOpenFile(), and ThrowSilentError().
The documentation for this class was generated from the following files:
dng_file_stream.h
dng_file_stream.cpp