DNG SDK 1.5: dng_date_time_storage_info Class Reference
dng_date_time_storage_info Class Reference
Store file offset from which date was read.
#include <dng_date_time.h>
Public Member Functions
dng_date_time_storage_info ()
The default constructor initializes to an invalid state.
dng_date_time_storage_info (uint64 offset, dng_date_time_format format)
Construct with file offset and date format.
bool IsValid () const
uint64 Offset () const
dng_date_time_format Format () const
Detailed Description
Store file offset from which date was read.
Used internally by Adobe to update date in original file.
Warning
Use at your own risk.
Member Function Documentation
Format()
dng_date_time_format dng_date_time_storage_info::Format () const
Get for format date was originally stored in file. Throws a dng_error_unknown exception if offset is invalid.
Exceptions
dng_exception with fErrorCode equal to dng_error_unknown if offset is not valid.
References IsValid(), and ThrowProgramError().
IsValid()
bool dng_date_time_storage_info::IsValid () const
Predicate to determine if an offset is valid.
Return values
true if offset is valid.
Referenced by Format(), and Offset().
Offset()
uint64 dng_date_time_storage_info::Offset () const
Getter for offset in file.
Exceptions
dng_exception with fErrorCode equal to dng_error_unknown if offset is not valid.
References IsValid(), and ThrowProgramError().
The documentation for this class was generated from the following files:
dng_date_time.h
dng_date_time.cpp