DNG SDK 1.5: dng_color_space Class Reference
dng_color_space Class Reference
An abstract color space.
#include <dng_color_space.h>
Public Member Functions
const dng_matrix & MatrixToPCS () const
const dng_matrix & MatrixFromPCS () const
bool IsMonochrome () const
virtual const dng_1d_function & GammaFunction () const
Getter for the gamma function for this color space.
bool IsLinear () const
Returns true if this color space is linear. (I.e. has gamma 1.0.)
real64 GammaEncode (real64 x) const
Map an input value through this color space's encoding gamma.
real64 GammaDecode (real64 y) const
virtual bool ICCProfile (uint32 &size, const uint8 *&data) const
Protected Member Functions
void SetMonochrome ()
void SetMatrixToPCS (const dng_matrix_3by3 &M)
Protected Attributes
dng_matrix fMatrixToPCS
dng_matrix fMatrixFromPCS
Detailed Description
An abstract color space.
Member Function Documentation
GammaDecode()
real64 dng_color_space::GammaDecode (real64 y) const inline
Map an input value through this color space's decoding gamma (inverse of the encoding gamma).
References dng_1d_function::EvaluateInverse(), and GammaFunction().
ICCProfile()
bool dng_color_space::ICCProfile (uint32 & size, const uint8 *& data) const virtual
Getter for ICC profile, if this color space has one.
Parameters
size Out parameter which receives size on return.
data Receives bytes of profile.
Return values
Returns true if this color space has an ICC profile, false otherwise.
Reimplemented in dng_space_GrayGamma22, dng_space_GrayGamma18, dng_space_ProPhoto, dng_space_ColorMatch, dng_space_AdobeRGB, and dng_space_sRGB.
IsMonochrome()
bool dng_color_space::IsMonochrome () const inline
Predicate which is true if this color space is monochrome (has only a single column).
Referenced by dng_render::Render().
MatrixFromPCS()
const dng_matrix& dng_color_space::MatrixFromPCS () const inline
Return a matrix which transforms Profile Connection Space data into this color space.
MatrixToPCS()
const dng_matrix& dng_color_space::MatrixToPCS () const inline
Return a matrix which transforms source data in this color space into the Profile Connection Space.
The documentation for this class was generated from the following files:
dng_color_space.h
dng_color_space.cpp