DNG SDK 1.5: dng_date_time.h File Reference
dng_date_time.h File Reference
#include "dng_classes.h"
#include "dng_string.h"
#include "dng_types.h"
Classes
class dng_date_time
Class for holding a date/time and converting to and from relevant date/time formats.
class dng_time_zone
Class for holding a time zone.
class dng_date_time_info
Class for holding complete data/time/zone information.
class dng_date_time_storage_info
Store file offset from which date was read.
Enumerations
enum dng_date_time_format { dng_date_time_format_unknown = 0, dng_date_time_format_exif = 1, dng_date_time_format_unix_little_endian = 2, dng_date_time_format_unix_big_endian = 3 }
Tag to encode date represenation format.
Functions
void CurrentDateTimeAndZone (dng_date_time_info &info)
void DecodeUnixTime (uint32 unixTime, dng_date_time &dt)
Convert UNIX "seconds since Jan 1, 1970" time to a dng_date_time.
dng_time_zone LocalTimeZone (const dng_date_time &dt)
Detailed Description
Functions and classes for working with dates and times in DNG files.
Enumeration Type Documentation
dng_date_time_format
enum dng_date_time_format
Tag to encode date represenation format.
Enumerator
dng_date_time_format_exif
Date format not known.
dng_date_time_format_unix_little_endian
EXIF date string.
dng_date_time_format_unix_big_endian
32-bit UNIX time as 4-byte little endian
Function Documentation
CurrentDateTimeAndZone()
void CurrentDateTimeAndZone (dng_date_time_info & info)
Get the current date/time and timezone.
Parameters
info Receives current data/time/zone.
Referenced by LocalTimeZone().
LocalTimeZone()
dng_time_zone LocalTimeZone (const dng_date_time & dt)
Return timezone of current location at a given date.
Parameters
dt Date at which to compute timezone difference. (For example, used to determine Daylight Savings, etc.)
Return values
Time zone for date/time dt.
References CurrentDateTimeAndZone(), and dng_date_time::IsValid().